### ISSUE TITLE
I love this router!

### ISSUE THREAD

**Issue by wetneb** [abrensch/brouter#100]
Hi - there does not seem to be any designated way to communicate enthusiasm about this tool. I don't have any particular issue to report, I just want to say that it's a fantastic service that I have used for thousands of kilometers and it just works great. I mostly use it in the UK on a recumbent with the fastbike profile and it's marvelous. I compute the routes via brouter-web and upload them to my Garmin unit.

Keep up the awesome work!

(feel free to close this issue of course, as it is not actually an issue!)

**Comment by abrensch** [comment]
Thanx!

You can also check the google-group as a designed way for non-software feedback: https://groups.google.com/forum/#!forum/osm-android-bikerouting
