### ISSUE TITLE
unclassified surface gravel

### ISSUE THREAD

**Issue by opendcc** [abrensch/brouter#102]
Hallo,

nachdem ich Sonntag da grob mit dem Rennrad reingeraten bin: überörtliche Straßen sind in OSM als unclassified zu taggen, können aber durchaus sehr schlechte Oberflächen haben. (Beispiel: https://www.openstreetmap.org/#map=17/47.84584/12.28566) Das Tagging der Straße ist korrekt, auch die Angabe der smoothness ist da.

Ich würde mir wünschen, dass brouter solche Oberflächengüten (gravel, smoothness=bad) in den Einstellungen fastbike* berücksichtigt. Vielen Dank!

Wolfgang

**Comment by utack** [comment]
Servus Wolfgang,

die Profile von Arndt haben generell eine Priorität auf schnelle Rechenzeit und schauen nicht näher auf "surface" oder "smoothness" bei Straßen  
Hast du mal die neuen "vm-forum" profile getestet die mit der neuesten Version vom BRouter kommen?

**Comment by grmpl** [comment]
Hallo,
die fastbike-Profile berücksichtigen sehr wohl die Oberfläche. 
Es fehlt aber leider der unpaved-switch bei "unclassified", der bei anderen Straßen berücksichtigt wird.

Statt
  switch    highway=unclassified                      1.1
müsste es so heißen:
  switch    highway=unclassified                      switch isunpaved 10 1.1
