### ISSUE TITLE
More details about elevation costs?

### ISSUE THREAD

**Issue by wetneb** [abrensch/brouter#105]
Hi!
I am curious about the algorithm to evaluate elevation cost. I tried searching around but could not find how it works exactly. Could you indicate me where to look?

I have just been on a ride and ended up climbing an insanely steep road (more than 20% at some places), to the point that I had to walk. 
I am therefore wondering if I could build my own profile where very steep roads would be penalized.
I have read https://github.com/abrensch/brouter/blob/448bb11ad4f852c3b75da91c91ead9a13d672916/misc/readmes/profile_developers_guide.txt but could not understand the meaning of the elevation-related parameters.

If you are curious about which route, here is the example: http://brouter.de/brouter-web/#zoom=15&lat=43.23943&lon=-3.28908&layer=OpenStreetMap&lonlats=-3.269849,43.230602|-3.294439,43.241701&nogos=&profile=fastbike&alternativeidx=0&format=geojson

**Comment by poutnikl** [comment]
As an auxiliary unofficial material, you may find as useful the links below.
Particularly search for uphillcost and uphillcutoff
The latter is a slope triggering penalty (%), the former the progressive penalty rate.

E.g if the values are 3.0(cutoff) and 60(cost),
then 
- the cutoff is subtracted from slope
- if result >0, this is taken as a slope
- there is computer elevation change from the above slope and the distance.
- elevation difference is multiplied by the cost (60)

https://github.com/poutnikl/Brouter-profiles/wiki/Glossary
https://github.com/poutnikl/Brouter-profiles/wiki/

**Comment by quaelnix** [comment]
> I am therefore wondering if I could build my own profile where very steep roads would be penalized.

You can avoid such steep climbs by choosing the following profile options:
![uphillcutoff](https://github.com/abrensch/brouter/assets/122357328/ee7bbf33-3c25-4032-a53f-6c1f90049d75)
