### ISSUE TITLE
Routing over highway=construction

### ISSUE THREAD

**Issue by hsimpson00** [abrensch/brouter#106]
Brouter is routing over highway=construction Ways. This can't be correct.

Example: The Donau-Radweg in Austria, which is closed down due to workings on the dyke until 2020: https://www.openstreetmap.org/way/505769307

Even if there are cycle-routes on this way, Brouter shouldn't even consider to unse such ways!

Regards

**Comment by utack** [comment]
Duplicate of  
https://github.com/abrensch/brouter/issues/62
