### ISSUE TITLE
Release hotfix with new version

### ISSUE THREAD

**Issue by jo-so** [abrensch/brouter#109]
Please give your “hotfix” release from 2018-04-12 a new version number to distinguish it from the former version. This one was uploaded to [f-droid](https://f-droid.org/de/packages/btools.routingapp/). The package gets no update now, because the source code version did not increase.

Can you add git tags to the repository, too?

**Comment by Phyks** [comment]
@abrensch Latest F-Droid version is 1.4.11 from last year https://f-droid.org/fr/packages/btools.routingapp/. Not sure what is to be done here (F-Droid side or BRouter side) but could you update the F-Droid version? Thanks!

**Comment by Phyks** [comment]
This is actually blocked by https://github.com/abrensch/brouter/issues/178
