### ISSUE TITLE
elevation display problem by round trip

### ISSUE THREAD

**Issue by mebels** [abrensch/brouter#111]
The elevation box has a problem to display the elevation and different two lines, when the lines are to nearby on bigger streets, or is overlapped, by routing at a round trip on the same street.
OK, the elevation box is only a module, but i don't remember the name to write the issue to the right place. sorry.

**Comment by Phyks** [comment]
I think this is a BRouter-web (https://github.com/nrenner/brouter-web / http://brouter.de/brouter-web/) issue. I cannot reproduce it, it seems to have been fixed, see e.g.

http://brouter.de/brouter-web/#map=18/48.83556/2.35012/standard,Waymarked_Trails-Cycling&lonlats=2.348977,48.835836;2.350945,48.83649;2.348676,48.835801

cc @nrenner

**Comment by zod** [comment]
As @Phyks mentioned this issue (if it still applies) should be reported at brouter-web
