### ISSUE TITLE
Why does BRouter still draw routes across a bridge which is totally blocked because of construction work?

### ISSUE THREAD

**Issue by tracker51** [abrensch/brouter#114]
Hi,

OSM map has been updated as to this issue on August 31st but BRouter doesn't seem to have noticed it. How long will it take until bikers won't being misguided any more?
Best regards

tracker51

**Comment by abrensch** [comment]
the bike rofiles (at least trekking + fastbike, can't tell for others) don't consider highway=construction as a total block, just higher penalty.

You need additional access-tagging (e.g. access=no) in order to get a full block for bikes.

**Comment by tracker51** [comment]
Hello,

many thanks for the information. Please understand that I'm sort of
surprised: the bridge has been tagged by me "temporary:access=no".
Isn't this tagging sufficient to prohibit routing across the bridge?
To prevent such routing until end of construction I've tagged
"access=no".

Best regards

Reinhard

abrensch schrieb:
