### ISSUE TITLE
lookups.dat request: busway tag

### ISSUE THREAD

**Issue by Phyks** [abrensch/brouter#119]
Hi,

It seems that BRouter is not currently considering `busway` tag in OSM data. Then, a route such as http://www.brouter.de/brouter-web/#map=18/48.82360/2.32775/OpenStreetMap&lonlats=2.32672,48.82308|2.327599,48.823999 is highly penalized.

The configuration on the ground is a shared busway but the busway is contraflow (`busway=opposite_lane`). As BRouter does not consider `busway` tag, it is not possible to edit the `onewaypenalty` to account for this case.

What about adding `busway=opposite_lane` to the `lookups.dat`?

Thanks!

**Comment by Phyks** [comment]
Hmmm, I might be missing something with the way `lookups.dat` file works.

I put, right before the `---context:node` line:

```
busway;0 opposite|opposite_lane|opposite_track
busway:left;0 opposite|opposite_lane|opposite_track
busway:right;0 opposite|opposite_lane|opposite_track

```

which, as far as I understood, should extract interesting `busway` values as well.


When [dumping statistics](https://github.com/abrensch/brouter/blob/master/brouter-map-creator/src/main/java/btools/mapcreator/OsmCutter.java#L98) from my `pbf` extract, I can see these tags listed. However, when routing with `brouter-web` and having a look at the "data" tab, I cannot see the added `busway` lookups in the output :/

Thanks!

**Comment by poutnikl** [comment]
By default, Brouter considers and data tab lists only those tags used explicitly in the profile.

To list all rd5 tags for listed ways/nodes, one has to explicitly set a profile variable ( which I do not remember or find right now) as true/1

**Comment by Phyks** [comment]
Ah, indeed, I missed this. I'm interested in the profile variable if someone remembers it, but otherwise my lookups.dat is indeed working fine for me. Thanks for the tip!

**Comment by abrensch** [comment]
> To list all rd5 tags for listed ways/nodes, one has to explicitly set a profile variable ( which I do not remember or find right now) as true/1

See the dummy profile, this is using this profile variable to process unused tags:

http://brouter.de/brouter/profiles2/dummy.brf
