### ISSUE TITLE
Isochrone

### ISSUE THREAD

**Issue by krakentom** [abrensch/brouter#124]
Add Isochrones to BRouter. Obtains areas of reachability from given locations.

How it works: https://maps.openrouteservice.org/
Git: https://github.com/GIScience/openrouteservice

**Comment by poutnikl** [comment]
It has a prerequisite of the routing to evaluate the route travel time. 

BRouter routing is not based on travel time ( aside of the new kinematic car routing ) 
The ETA calculation (estimated time of arrival) for bike and foot travel is on the very Alfa stage yet.

**Comment by abrensch** [comment]
sure, nice feature, but not on the priority list for BRouter I'm afraid.

**Comment by Phyks** [comment]
Now that we have travel time computation (for bike mode), I'm wondering whether this could actually be done easily. I don't know anything about isochrone computation algorithm? Has anyone some insights about it? Is it just repeated routing computations or does it require some real kinematic model?

Thanks!
