### ISSUE TITLE
Crossing nogo sometimes result in weird route

### ISSUE THREAD

**Issue by Phyks** [abrensch/brouter#129]
Hi,

Sometimes, when adding a nogo circle, the resulting route can be quite unexpected.

Here is an example:

http://brouter.de/brouter-web/#map=19/48.81771/2.32037/OpenStreetMap&lonlats=2.319322,48.817627|2.320454,48.817373&nogos=2.319818,48.81764,25

Without the nogo, the route looks like (as expected)
<img width="705" alt="capture d ecran 2018-12-03 a 11 43 47" src="https://user-images.githubusercontent.com/3856586/49369059-c86d7280-f6f0-11e8-8cfe-2695a9dab85e.png">

With the nogo, the route looks like
<img width="706" alt="capture d ecran 2018-12-03 a 11 43 43" src="https://user-images.githubusercontent.com/3856586/49369120-f357c680-f6f0-11e8-9963-36300608c425.png">

This is quite unexpected, especially the right part where it goes **beyond** the end point.

The expected route with a nogo should rather be something like
<img width="749" alt="capture d ecran 2018-12-03 a 11 44 16" src="https://user-images.githubusercontent.com/3856586/49369098-e1762380-f6f0-11e8-9a5b-00237c14327a.png">

**Comment by abrensch** [comment]
Hi Lucas,

yeh, that's "same segment search" und there are afew known problems...

same segment means that both start-and endpoint share the same way segment

**Comment by Phyks** [comment]
Hi,

Oh, ok I missed the fact that there are some known problems about same segment searches. Thanks for the info! This is a very special use case which is not so common, that's not a big deal. I'll just take it into account for my nogo tests :)

Thanks!
