### ISSUE TITLE
Please consider cycleway:surface in lookups.dat

### ISSUE THREAD

**Issue by utack** [abrensch/brouter#131]
The tagging for cycleway surface using "cycleway:surface" is on the rise, according to the OSM weekly blog. It is used on over 5300 ways already.
https://wiki.openstreetmap.org/wiki/Key:cycleway:surface
I think this is a great key to have for a bike router, please consider adding it to lookups.dat
Thank you

![export](https://user-images.githubusercontent.com/8551234/49693409-43f87500-fb72-11e8-88af-d54c78832727.png)

**Comment by poutnikl** [comment]
It is a pity, as such tags for particular cases unnecessarily complicate things, as there is already general tag surface=.

**Comment by Phyks** [comment]
Hi!

This is done in [this commit](https://github.com/abrensch/brouter/commit/619e2d6cd7bb7c7e79bbdcfe83877eed22d0f2a6) (not yet part of a PR). Could you have a look and let me know what you think about it? I would be interesting about second opinions about the profiles part in particular :)

Best,

**Comment by Phyks** [comment]
Hi @utack, would you have a specific example in mind where taking cycleway surface into account would change the result from the routing? I'd like to add a unittest for it in https://github.com/phyks/broutertesting. Thanks!

**Comment by poutnikl** [comment]
Why should have cycleway:surface=* different routing effect, compared to surface=* ?

Physical effect on biker experience and preference
does not depend on how it is mapped ?

**Comment by Phyks** [comment]
Typically, I can imagine a paved street having a cycleway with asphalt surface. Then, with the current profiles, the cycleway would be considered as having the `surface` (which is the one of the street) and be penalized when in fact the `cycleway:surface` would leverage this penalty.

**Comment by utack** [comment]
@Phyks I will get back to you  
The real-world cases I can think of are vast (cobblestone on the bike path, asphalt on the road), but the mapped ones are still rare.
The ones I found I will report to you!

**Comment by Phyks** [comment]
@utack Thanks! You can also add some in OSM data if you know them and they are not mapped :p

@poutnikl Exactly, that's what I'd like to add a test in https://github.com/Phyks/BrouterTesting for. :)

**Comment by theraser** [comment]
I just noticed that the changes at lookups.dat are already applied, maybe we can close this issue here? Or is there something more to do?

Sadly the cycleway:surface tags aren't used by brouter-web, I just created an issue over there: https://github.com/nrenner/brouter-web/issues/438
