### ISSUE TITLE
Missing elevation data for specific routes

### ISSUE THREAD

**Issue by nrenner** [abrensch/brouter#137]
Reported in nrenner/brouter-web#147 by @MichaelK92.

http://brouter.de/brouter-web/#map=17/44.44707/15.18322/OpenStreetMap&lonlats=15.183293,44.447082|15.181603,44.448656

        "coordinates": [
          [15.183296, 44.447090],
          [15.183191, 44.447111],
          [15.183030, 44.447200],
          [15.182328, 44.447885],
          [15.181645, 44.448615, 37.5],
          [15.181602, 44.448655, 37.5]
        ]

Moving the start point past the previous node in the curve, some elevation data is filled in:
http://brouter.de/brouter-web/#map=17/44.44707/15.18322/OpenStreetMap&lonlats=15.18339,44.447082|15.181603,44.448656

        "coordinates": [
          [15.183390, 44.447079, 27.0],
          [15.183354, 44.447079, 27.5],
          [15.183191, 44.447111, 27.5],
          [15.183030, 44.447200, 27.5],
          [15.182328, 44.447885, 27.5],
          [15.181645, 44.448615, 37.5],
          [15.181602, 44.448655, 37.5]
        ]

Ways:
https://www.openstreetmap.org/way/253261970
https://www.openstreetmap.org/way/253354195

**Comment by bagage** [comment]
Another example (bridge is the issue): https://brouter.damsy.net/latest/#map=15/45.1781/4.8188/standard&lonlats=4.814286,45.18863|4.811883,45.184122|4.814329,45.180613

**Comment by nrenner** [comment]
Out of interest I took a closer look at the elevation data for those cases (GeoTIFF from http://srtm.csi.cgiar.org/srtmdata/, [converted](https://github.com/nrenner/leaflet-raw-dem#usage) to BIL format, and to ASCII for debugging with [MapcreatorTest.java](https://github.com/abrensch/brouter/blob/master/brouter-map-creator/src/test/java/btools/mapcreator/MapcreatorTest.java)):

### Coastal road, Rudelić-Draga

http://brouter.de/brouter-web/#map=18/44.44725/15.18269/osm-mapnik-german_style&lonlats=15.181603,44.448656;15.183572,44.447143

![Screenshot Leaflet-raw-DEM - Rudelić-Draga](https://user-images.githubusercontent.com/1092030/58658834-be37d400-8321-11e9-975d-888a90ba719b.png)

*Screenshot [leaflet-raw-dem srtm_40_04_bil.zip](http://nrenner.github.io/leaflet-raw-dem/?url=http://norbertrenner.de/dem/cgiar-csi-4.1/srtm_40_04_bil.zip#zoom=17&lat=44.447457&lon=15.18232)*

The red cells are voids (no data), the [CGIAR CSI SRTM](http://srtm.csi.cgiar.org/) has shorelines cut out ([FAQ](http://srtm.csi.cgiar.org/faq/)).

BRouter interpolates height within a block of four cells, if one of these cells has no data, the elevation of the node is also set to no data:

```
31  54    
11  30    30  56
          nd  27    27  40
= 37.5              nd  16    40  25
          = n/d               16  11
                    = n/d
                              = 27.5
```

https://github.com/abrensch/brouter/blob/ab2f5e3ae0f9ddbc16ef4a557bb78ac9d038a4fb/brouter-map-creator/src/main/java/btools/mapcreator/SrtmRaster.java#L49-L62


### Ferry, Bremerhaven

http://brouter.de/brouter-web/#map=12/53.5235/8.5707/osm-mapnik-german_style&lonlats=8.584442,53.538267;8.565903,53.529595;8.545475,53.520411

![Screenshot Leaflet-raw-DEM - Bremerhaven](https://user-images.githubusercontent.com/1092030/58658860-c98aff80-8321-11e9-9727-496a86551b7d.png)

*Screenshot [leaflet-raw-dem srtm_38_02_bil.zip](http://nrenner.github.io/leaflet-raw-dem/?url=http://norbertrenner.de/dem/cgiar-csi-4.1/srtm_38_02_bil.zip#zoom=12&lat=53.5235&lon=8.5707)*

The shoreline with no data reaches into the river mouth where the ferry crosses.


### Bridge, Saint-Vallier

https://brouter.damsy.net/latest/#map=15/45.1781/4.8188/standard&lonlats=4.814286,45.18863;4.811883,45.184122;4.814329,45.180613

The river has [elevation data (srtm_37_03_bil.zip)](http://nrenner.github.io/leaflet-raw-dem/?url=http://norbertrenner.de/dem/cgiar-csi-4.1/srtm_37_03_bil.zip#zoom=17&lat=45.183923&lon=4.81248), but BRouter is removing elevation from bridges and tunnels, in order to interpolate between start and end elevation:

https://github.com/abrensch/brouter/blob/c89058ee631ed0fc595e822d74a0cd9f0366fe62/brouter-map-creator/src/main/java/btools/mapcreator/OsmNodeP.java#L52-L56

This just doesn't work if a route point as start of a segment is on the bridge.


So this is generally working as designed and these exceptional cases are probably hard to improve, therefore closing.
