### ISSUE TITLE
Possibility about more high resolution dem?

### ISSUE THREAD

**Issue by 1stgongsin** [abrensch/brouter#144]
Hi,.
Now rd5 segment generation script uses srtm(90m resolution) from CGIAR
"ArcInfo ASCII" version.
I have more high resolution DEM files(under 30m) for my region and want to make my own rd5 files.
hgt file didn't work with process_pbf_planet.sh
I converted my dem files to arcinfo ascii format but it didn't work,
Only 90m SRTM work? 

Is there any way?

**Comment by abrensch** [comment]
Actually there is support for 30m SRTM, but I never took it productive.

It's not that it does not work, it's just that I failed to prove that it's actually any better then the 90m data, so the never-change-a-working-system rule applied.

It's that (more than 2 years old) commit: https://github.com/abrensch/brouter/commit/561b60c5cbc43c9f3f1625ef3bd0b7a3b020a4c5

It involves another pre-processor that
- converts the 1*1 degree tiles to 5*5 degree tile
- adds an  "extended border" to these tiles
- transfers the CGIAR void fillings to these tiles
- stores them in a compressed binary format (".bef") that parses faster then a text/zip file 

Background is that:
- the brouter pre-processor needs to access a 5*5 tile at a time
- if you apply certain median filters you need extened border to prvent edge effects at the tile boundary
- the 1*1 srtm tiles have dubious and inhomogenuos void fillings 

However, if you don't worry about these details an can do a little Java, you could just look at the class "PosUnifier" ( https://github.com/abrensch/brouter/blob/master/brouter-map-creator/src/main/java/btools/mapcreator/PosUnifier.java ), which is the only place where the DEM data is actually accessed - and there's no rocket science in it, so you can as well insert your own adapter

**Comment by 1stgongsin** [comment]
Thank you very much for the answer, abrensh!
