### ISSUE TITLE
[Question]Routing for slightly disconnected line

### ISSUE THREAD

**Issue by 1stgongsin** [abrensch/brouter#145]
Hello.
I have my own osm(mapsforge) map of my country. and It has much more mountain road than
official openstreetmap. I made brouter segments(.rd5) with my own mapsforge map.
 Problem is that mountain road has very much part of slightly disconnected. So when I routing with
BRouter, result is very long detour. Below picture, I want route A to B direct black line, but result is red
line(long detour) because of short part of disconnect. ( I use trekking.brf mainly)

![33](https://user-images.githubusercontent.com/35750045/52836798-7a80dc00-312f-11e9-858e-fecec4c0bfef.jpg)

Is there a way to ignore 'short-cut-part' and routing directly?
It's serious problem because there are Hundreds of thousands of this 'short-cut' of mountain road.
Is that possible by editing trekking.brf?

Best regards.

**Comment by danfos** [comment]
I think the better solution is to fix the map; in many countries there are many, many was with only 10-30 meter between them.
