### ISSUE TITLE
[feature] Click on data line pans to location

### ISSUE THREAD

**Issue by MaartenDeen** [abrensch/brouter#148]
I would be a great help that when you click on a line in the data window, the map pans to where this location is. Currently if you want to look for a location to match the result of the rules against the location, you have to zoom out and find it by the yellow color of the route.

**Comment by Phyks** [comment]
:+1:

This issue would however rather fit in https://github.com/nrenner/brouter-web which is the repository for the web interface (this one is for the backend code, server or Android app).

**Comment by MaartenDeen** [comment]
Thanks. I was a bit blind for the difference between the two. I've created the request there.
