### ISSUE TITLE
Configuration for better performance of BRouter server?

### ISSUE THREAD

**Issue by Phyks** [abrensch/brouter#150]
Hi,

I have a BRouter server running at http://brouter.phyks.me/ offering some of my custom profiles (and focusing on mainland France area). I noticed that it is often quite slow and unresponsive, especially for long routes such as https://brouter.phyks.me/#map=10/49.3153/1.2051/OpenStreetMap&lonlats=2.345924,48.853419|1.053314,49.455599 (which actually results in a timeout most of the time).

After some testing around, it seems one of the main issue is actually a caching issue. For the example above, I get a timeout at the first run, but it works on subsequent queries. Looks like a slow loading of data from the disk and on subsequent calls everything is already available in cache.

I am running the BRouter server with the default command line from https://github.com/abrensch/brouter/blob/master/misc/scripts/standalone/server.sh:
```
/usr/bin/java -Xmx128M -Xms128M -Xmn8M -DmaxRunningTime=300 -cp /home/www/brouter/brouter-src/brouter-server/target/brouter-server-1.4.11-jar-with-dependencies.jar btools.server.RouteServer /home/www/brouter/segments4 /home/www/brouter/brouter-src/misc/profiles2 /home/www/brouter/customprofiles 17777 1
``` 

I guess I could play with `Xm*` options from Java command line to allow more RAM and have more efficient caching. What is the best strategy here (how is it handled in brouter.de for instance?)?

Thanks!

**Comment by abrensch** [comment]
>> I guess I could play with Xm* options from Java command line to
>> allow more RAM and have more efficient caching.

No that would be counterproductive.

If it's a caching-issue, then it's the operating-systems file-system-cache. And all the memory that you put in -Xmx is not aviáilable any more for file-system caching.

RD5's are read by random access in blocks of 1/32 degree * 1/32 degree, so 25.600 blocks per rd5. On a spinning disk with 20ms access time that would be 512 Seconds to read the file.

On brouter.de/brouter-web, you so almost no trace of that access time in the runtime profiles, which means it's either all  cached (possible for 5 GB world rd5 on an 8 GB host), or it's all fast-access solid-state-disk.

BRouter has a build-in profiler: if you place a "stacks.txt" into it's base-folder (=parent-dir of the profile-folder), then a thread-dump will be written each second into that file. Can you send me such a file?

regards, Arndt

**Comment by Phyks** [comment]
> If it's a caching-issue, then it's the operating-systems file-system-cache. And all the memory that you put in -Xmx is not aviáilable any more for file-system caching.

> RD5's are read by random access in blocks of 1/32 degree * 1/32 degree, so 25.600 blocks per rd5. On a spinning disk with 20ms access time that would be 512 Seconds to read the file.

Oh ok, thanks for the details on the way RD5 files are read! I was thinking there was an additional cache mechanism within BRouter. My server is running with regular 7200 rpm hard drives and the order of magnitude seems right for the behavior I was experiencing yesterday: first access is very long and subsequent calls (when the file is in system's cache) are performing better.

Additionally, brouter.de has probably enough usage so that the RD5 files are more or less always available in system cache.

> BRouter has a build-in profiler: if you place a "stacks.txt" into it's base-folder (=parent-dir of the profile-folder), then a thread-dump will be written each second into that file. Can you send me such a file?

Oh, I did not knew about this! (It might be worth documenting it somewhere in https://github.com/abrensch/brouter/tree/master/misc/readmes :)

My `stacks.txt` output is at https://gist.github.com/Phyks/c7906b72548ce2eeef7ae48a1f3d2cc2, for a typical "long" route on which it takes 13s to load the route. This is quite fast actually (and it seems mainly due to the route computation), I cannot reproduce very long and caching-like issues at the moment. I'll try to produce a `stacks.txt` file when I manage to reproduce it.

**Comment by abrensch** [comment]
This build-in stack sampling is good because it works in any environment, even on Android..

But as most samplers it has the problem of the "safepoint bias" which makes results hard to read when it comes to microbenchmarking individual methods.

If you are interested you might have a look at the "async profiler" ( https://github.com/jvm-profiling-tools/async-profiler ). However, that just working Linux 64 bit dedicated server, seems not to work on virtual servers.

**Comment by Phyks** [comment]
Thanks for the tip! I I'll have a look next time I encounter issues.
