### ISSUE TITLE
Move standalone scripts to brouter-web?

### ISSUE THREAD

**Issue by nrenner** [abrensch/brouter#163]
I'm thinking about making a separate all-in-one release zip for brouter-web that also includes the standalone server with a current version of the brouter.jar and scripts. This would make local brouter-web [installation](https://github.com/nrenner/brouter-web#installation) a bit easier and ensure matching client and server versions.

I originally proposed (#11) to add the standalone scripts to the brouter [release zip](http://brouter.de/brouter/revisions.html) (in folder `standalone`). But now that the actual app release cycles are less frequent and with a potential, separate all-in-on zip for brouter-web, should we remove those scripts from the brouter repository and zip and move to brouter-web?

Is anyone using those [standalone scripts](https://github.com/abrensch/brouter/tree/master/misc/scripts/standalone) except for brouter-web?

**Comment by rkflx** [comment]
IIRC QLandkarte GT and QMapShack also support BRouter (I did not check how the integration is done, though, probably by launching the jar directly?). Nevertheless, in general there might be existing or future clients besides brouter-web, so I think there are still use cases for an easy way to get started with the git version of BRouter.

It's probably not really relevant whether there's a script in the repo, or the README has enough details. However, at least some form of documentation wrt. which parameters the jar is expecting should be provided.

(Of course crafting an all-in-one zip for brouter-web could still be done in addition.)

**Comment by Phyks** [comment]
> Nevertheless, in general there might be existing or future clients besides brouter-web, so I think there are still use cases for an easy way to get started with the git version of BRouter.

:+1: I was using the standalone scripts as a quickstart for many projects. It's also nice to have in BRouter repo (although probably the same goal could be achieved with documentation) as this is acting as a form of documentation / entrypoint as well (I started there when I first arrived to the BRouter repo).

**Comment by Phyks** [comment]
@nrenner I've recently added documentation in BRouter repo concerning the standalone scripts (https://github.com/abrensch/brouter#run-the-brouter-http-server). Not sure what the decision is here, but since we are a couple using these outside of brouter-web context, it might be worth keeping them.

What do you think?

**Comment by nrenner** [comment]
So I guess it makes sense to keep the scripts in this repo. Will open a new issue about a separate standalone zip once we have that.
