### ISSUE TITLE
Support for turning restrictions

### ISSUE THREAD

**Issue by wetneb** [abrensch/brouter#167]
It could be interesting to add support for turning restrictions. They can be useful even for bicycles, in the following example: http://brouter.de/brouter-web/#map=15/51.9455/-1.3253/standard&lonlats=-1.336298,51.951928;-1.279392,51.810431&profile=fastbike (note that this is in the UK, so left-hand drive)

There are signs on Oxford Road explicitly forbidding the U-turn proposed by brouter, and for a good reason: this is a dual carriageway! It requires you to shift to the fast lane, go on the traffic island, and then merge back into the fast lane of the other direction, and shift back to the slow lane. (I have done this twice and it felt quite sketchy both times)

The problem was kindly fixed by OSM user trigpoint (https://www.openstreetmap.org/note/1827891) by adding a turn restriction but as far as I am aware this is not supported by brouter so far.

Note that I am not familiar at all with how turning restrictions are modeled in OSM so I have no idea if this is doable or not.

**Comment by abrensch** [comment]
Well there are turn restrictions, but they are not widely used for bike profile.

One exception is the recumbent bike profile, but you see it also doesn't wor in this case, and this is because TRs with "via-ways" are not supported:

http://brouter.de/brouter-web/#map=16/51.9439/-1.3235/standard&lonlats=-1.325289,51.943046;-1.325418,51.941896&profile=vm-forum-liegerad-schnell

TRs with via-ways are not supported by most routers, so if you want it to be effective, you should consider a solution with just normal TRs (with via-nodes)

**Comment by Phyks** [comment]
> Well there are turn restrictions, but they are not widely used for bike profile.

I've just discovered support for turn restrictions was supported by BRouter through the `considerTurnRestrictions` parameter (https://github.com/abrensch/brouter/blob/67df0743cdcb61a01e7b8d6aa81dd5a4f4e610ed/misc/profiles2/vm-forum-liegerad-schnell.brf#L20).

I was not aware of this configuration variable. What about:
- [ ] Adding a description for it in the `profile_developer_guide.txt` readme file (https://github.com/abrensch/brouter/blob/master/misc/readmes/profile_developers_guide.txt)?
- [ ] Adding it in the fastbike/trekking profile with an explicit listing of the default value (that is `assign considerTurnRestrictions false;`), to make it more easily discoverable when customizing a bike profile?

I can write a PR for both if you want.


> TRs with via-ways are not supported by most routers, so if you want it to be effective, you should consider a solution with just normal TRs (with via-nodes)

Tagging question here, how would you represent this "no U turn" restriction with normal TRs with via-nodes? Would you have two "no left turn" TRs (highway to small way + small way to highway on the other side)?

By the way, the TR OSM wiki page seems to lack infos about tagging correctly for routers https://wiki.openstreetmap.org/wiki/Relation:restriction :/

Thanks!
