### ISSUE TITLE
Support living_street tag

### ISSUE THREAD

**Issue by Phyks** [abrensch/brouter#174]
Hi,

It seems BRouter supports the `highway=living_street` tag (of course), but I could not find anything related to the `living_street=yes` tag. This tag is quite old, and rather undocumented (https://wiki.openstreetmap.org/wiki/Key:living_street), it is even considered a trolltag.

However, it is used 250k times around the world (https://taginfo.openstreetmap.org/keys/living_street#overview) which seems more than enough to be considered as a de facto tag and taken into account in BRouter.

So, what about adding `living_street=yes` support in `lookups.dat` and update the profiles so that `living_street=yes` is considered as a `highway=living_street` (or with a slight penalty)?

I can handle the changes if there is a consensus on this.

Best,

**Comment by abrensch** [comment]
sure, go ahead. But we should scan teh open issues for all other pending lookup.dat requests, there's also issue #166 by you, and in the google group there's something about stop signs:
