### ISSUE TITLE
Follow GPX track in OSMAnd with BRouter routing - missing options

### ISSUE THREAD

**Issue by Phyks** [abrensch/brouter#175]
Hi,

I have my OSMAnd set up to always use BRouter as the routing device (for my regular use case which is routing on the go). Sometimes, I prepare my trip with BRouter-web and export a GPX track which I then use within OSMAnd on the go (with the "route with the GPX file" options of OSMAnd).

I noticed that when BRouter is selected as a routing backend, I only have two options when routing with a GPX trace:
1. Offline computation of the route
2. Shortest route

While, when the default OSMAnd backend is selected, I have three different options:
1. Invert GPX trace
2. Follow the full trace
3. Compute a route for the first and last segments.

In particular, there is no way to invert a GPX trace when using OSMAnd + BRouter. My typical use case for this is when having a round trip GPX trace, and missing an instruction. I accidentally branched to the wrong way and was about to go across the GPX trace backwards, but could never fix the BRouter + OSMAnd guiding (I would have to invert the GPX trace).

I don't know much about Android interaction between OSMAnd and BRouter. Would it be something easy to add? Otherwise, does it mean I should stick to default OSMAnd routing when routing along a prepared GPX trace?

Thanks!
Best,

**Comment by abrensch** [comment]
There's a difference between Locus, where it's author is actively developing BRouter integration, and OsmAnd where we are just tolerated and BRouter integratio  would have been completely broken in OsmAnd 3.x if not Volker would have done some rescue work.

In that constallation it's not realistic to streamline BRouter integration, it's just realistic to keep it running. I saw you are coming to Heidelberg? Good chance to meet Victor and convince him to promote BRouter integration as a supported and tested feature...

I saw you are coming to Heidelberg? Good chance to meet Victor

**Comment by Phyks** [comment]
> In that constallation it's not realistic to streamline BRouter integration, it's just realistic to keep it running.

Indeed, this is too optimistic then and this one can be safely closed. I'll have a look at Locus map, which I've never used much.


> I saw you are coming to Heidelberg? Good chance to meet Victor and convince him to promote BRouter integration as a supported and tested feature...

Indeed, I'm going to SOTM. If I meet Victor, I might give it a try :) Are you going as well to SOTM?
