### ISSUE TITLE
Waypoint exported in GPX trace matched with the trace

### ISSUE THREAD

**Issue by Phyks** [abrensch/brouter#181]
Hi,

I got a report by email from a BRouter user (see https://groups.google.com/forum/#!topic/osm-android-bikerouting/ceUFvc4sFdQ as well) that when exporting waypoints in BRouter (GPX format), the exported points are simply POIs in the track, and have no link with the route.

Instead of exporting them as

```
<wpt lat="51.0555984795495" lon="4.00492429733276">
	<name>Foo</name>
	<type>via</type>
</wpt>
```

it would be better to add the info in the exported track

```
<rtept lat="51.0551323" lon="4.0006357">
    <name>Start</name>
    <type>Via</type>
</rtept>
```

This however is probably difficult to achieve as the route can sometimes not match with the waypoints. Think of a route such as http://brouter.de/brouter-web/#map=19/48.81899/2.31979/standard&lonlats=2.319708,48.81916;2.31829,48.81853&profile=hiking-beta for instance where start and end points are the POIs inside the building and don't match a point in the track.

cc @bagage

**Comment by nrenner** [comment]
I thought using separate waypoints was the whole point of your PR #170? We discussed this in [#91 (comment)](https://github.com/abrensch/brouter/issues/91#issuecomment-498683747).

Exporting a GPX `rte` with `rtept`s is a separate feature and covered by nrenner/brouter-web#16 and probably what #91 really means. IMO `rtept`s are only valid within a `rte` tag, see 
http://www.topografix.com/GPX/1/1/#type_rteType

And I think for both types of export (`wpt` and `rte`+`rtept`) the coordinates should be what the user entered (as currently implemented), not the ones matched to the road network, that's the router's task. 

Why would using the matched coordinates make a difference?

**Comment by Phyks** [comment]
Indeed, my use case just required to have the waypoints exported somewhere along the GPX track. No need for anything else for me.

Closing this one in favor of #91 and https://github.com/nrenner/brouter-web/issues/16. I forgot about these :/
