### ISSUE TITLE
profile developers guide update

### ISSUE THREAD

**Issue by zossebart** [abrensch/brouter#184]
Hi,

I think it's about time to update the profile developers guide. 
I recently searched quite some time to find the exact parameter name 'processUnusedTags' for some profile debugging work for example. 
Maybe at least a complete list of all official and inofficial builtin parameters and a short description what they do would help a lot.
Although @poutnikl wrote a very nice and extensive Wiki and Glossary, not even he has all the parameters covered. There are also some helpful (german) comments in the 'vm-forum-liegerad' - profiles which could be incorporated into the "official" guide.

I could try to enhance the docs by myself and issue a pullrequest, but I'm not sure if I fully understand all the parameters and their effects...

**Comment by abrensch** [comment]
Hi Zossebart,

yes, there's a lot of material that needs an update (and a cleanup from legacy stuff)

- the Play-Store description (english + german)
- the readme
- the website-texts

And we need more + multilanguage readme/docu that can be directly launched
from the BRouter-App  ( especially on Osmand integration )

I agree the profile developers guide also needs some update + polish, but it's not a priority on my personal list, so if you work on that I promise to merge it.

regards, Arndt

**Comment by Phyks** [comment]
@zossebart It would be great if you have any PR for this, in my opinion! In particular, the `profile_developers_guide.txt` lacks details about the global variables available, which are listed in https://github.com/abrensch/brouter/blob/master/brouter-core/src/main/java/btools/router/RoutingContext.java#L127-L188.

(See for instance https://github.com/abrensch/brouter/issues/167#issuecomment-506821319).

**Comment by zossebart** [comment]
Unfortunately, I'm very busy with other things right now. I created the issue mainly to not forget about it and to discuss it with others.
One first step should be to complete the list of builtin variables, @Phyks comment should be helpful for this.
In a second step, the variables could be described in more detail.

I could do the first step, but do not have the time right now to do the second.
Maybe @poutnikl could help here, as he already documented some variables in his Wiki?

**Comment by poutnikl** [comment]
i will join, just what time will allow

**Comment by Phyks** [comment]
- [ ] Just came across https://github.com/abrensch/brouter/issues/183#issuecomment-531560068 which could likely use some documentation / be a question in a profile development FAQ.

**Comment by EssBee59** [comment]
Hello Phyks,

As discussed in the last days, I agre with the need for an update of the project documentation.

I started working on an update of the developers guide. Hope to have a draft in the next days…
How should I send it to the Reviewers?

Regards
Ess bee

**Comment by poutnikl** [comment]
The native GitHub way is to create a fork of BRouter repository ( 1 click within GitHub ), make the update and then create the Pull request ( again within GitHub )

**Comment by abrensch** [comment]
> As discussed in the last days, I agre with the need for an update of the project documentation.

Well, for the profile_developers_guide there were recent updates, see

https://github.com/abrensch/brouter/commits/master/misc/readmes/profile_developers_guide.txt

So maybe I should have closed this issue? But anyway, feel free to come up with something new. Either as a pull request, or just email to me.
