### ISSUE TITLE
Regression assign  avoid_toll = false

### ISSUE THREAD

**Issue by poutnikl** [abrensch/brouter#197]
In my recent pull request there were introduced 3 logical parameters for  avoiding tolls, motorways and unpaved way,

It was done intentionally with assigned value 0, instead of false, as the former works, while the latter does not.

The reason for that was, it is currently hardcoded in Locus to recognize the code. It was my fault not  mentioning that.

When values 0 were later replaced by false, Locus stopped recognizing these configurable parameters.

Using false for logical constants definitely makes sense, but I suggest postponing it until Locus adapts to different or both syntax.

**Comment by Phyks** [comment]
> Using false for logical constants definitely makes sense, but I suggest postponing it until Locus adapts to different or both syntax.

Is there already a Locus-specific bug to track this?

**Comment by poutnikl** [comment]
I suppose there is not.

 I guess it may not be even a bug, as Boolean BRouter constants were implemented later, after originally using just 0/1.

**Comment by poutnikl** [comment]
@menion : "Hello Libor,
done (will be already in next 3.40 version)."

**Comment by menion** [comment]
Hi,
in next Locus Map version will be also supported for these true/false values.

Online BRouter portal is currently adapting this syntax, check [here](https://github.com/nrenner/brouter-web/issues/223#issuecomment-527108637). So it will be fine-tuned in the next months I believe.

**Comment by poutnikl** [comment]
At  https://github.com/poutnikl/Brrouter-profiles/ in the sdbat branch is development version of Android/termux bash script, with added  generation ability of any thinkable profile from car-fast, based   on assign command value substitution. It is easily expandable just by adding few lines.

Those few lines are like

```
function brcarexec { 
replaceone avoid_toll false 0 $src  $src-temp
replacetwo avoid_motorways false 0 avoid_unpaved false 0 $src-temp car-fast-gen
rm $src-temp.brf
replaceone vmax 160 90  car-fast-gen  car-eco-gen
replacetwo recup_efficiency 0.7 0.0  f_recup 400 0   car-fast-gen  car-norecup-gen
}
```



called like

```
./sedbatch remote master copy all brcar

```

( currently switching %parameters% temporarily back from false to 0 )

Read the embedded comments.

**Comment by poutnikl** [comment]
The latest Lucy's release already accepts the false for %parameter%, therefore closing the issue.
