### ISSUE TITLE
Implement XML and JSON encoding

### ISSUE THREAD

**Issue by nrenner** [abrensch/brouter#201]
Implement `escapeXml10` and `escapeJson` methods in [`StringUtils.java`](https://github.com/abrensch/brouter/blob/master/brouter-util/src/main/java/btools/util/StringUtils.java).

see also:
- #196
- 89ef900b7c0199c3ad7d13eb39be5c7cb1e2bb2a
- nrenner/brouter-web#194

Below some links of implementations for reference, mainly for XML, JSON needs more research. Haven't checked license compatibilty.

### XML (text content)

The basic characters that need encoding seem to be `& < >` (for text content only, not sufficient for attribute values). Implementations also replace/encode control characters, some Unicode ranges and invalid Unicode surrogate pairs, but maybe we can ignore those for now.

- [Apache Commons Text](http://commons.apache.org/proper/commons-text/)
  - [StringEscapeUtils.escapeXml11 docs](https://commons.apache.org/proper/commons-text/javadocs/api-release/org/apache/commons/text/StringEscapeUtils.html#escapeXml10-java.lang.String-)
  - [StringEscapeUtils.escapeXml11](https://github.com/apache/commons-text/blob/8e31edfe60027e374129ae9c92050dfecd5321e4/src/main/java/org/apache/commons/text/StringEscapeUtils.java#L115-L164)
  - [EntityArrays.BASIC_ESCAPE](https://github.com/apache/commons-text/blob/8e31edfe60027e374129ae9c92050dfecd5321e4/src/main/java/org/apache/commons/text/translate/EntityArrays.java#L361-L375)  
    - `& < > "`
- [OWASP Java Encoder Project](https://www.owasp.org/index.php/OWASP_Java_Encoder_Project)
  - [Encode.forXmlContent docs](https://owasp.github.io/owasp-java-encoder/encoder/apidocs/org/owasp/encoder/Encode.html#forXmlContent-java.lang.String-)
  - [XMLEncoder.CONTENT](https://github.com/OWASP/owasp-java-encoder/blob/bc9a85723f3c1b4819d9aa8aa1b539787128e4ea/core/src/main/java/org/owasp/encoder/XMLEncoder.java#L107-L113)
    - `& < >` (only for text content, not for attribute values!)
- [StAX](https://docs.oracle.com/javase/tutorial/jaxp/stax/index.html) - [OpenJDK](https://openjdk.java.net/)
  - [XMLStreamWriterImpl.writeXMLContent](https://hg.openjdk.java.net/jdk/jdk/file/80b27dc96ca3/src/java.xml/share/classes/com/sun/xml/internal/stream/writers/XMLStreamWriterImpl.java#l1401)
    - `& < >`
- [JAXB - Eclipse Implementation](https://github.com/eclipse-ee4j/jaxb-ri)
  - [MinimumEscapeHandler.escape](https://github.com/eclipse-ee4j/jaxb-ri/blob/afa88da958e1cfb953fb4c38f0b4a1cfec608162/jaxb-ri/runtime/impl/src/main/java/com/sun/xml/bind/marshaller/MinimumEscapeHandler.java#L29)
    - `& < > \r` (+ `" \n` for attribute values)

### JSON

- [OWASP JSON Sanitizer](https://www.owasp.org/index.php/OWASP_JSON_Sanitizer)
  - [docs](https://github.com/owasp/json-sanitizer#input)
  - [JsonSanitizer.java](https://github.com/OWASP/json-sanitizer/blob/master/src/main/java/com/google/json/JsonSanitizer.java)
  - does a lot more than we actually want (see also [motivation](https://www.owasp.org/index.php/OWASP_JSON_Sanitizer#tab=Motivation)): ensures that the output is valid JSON while we only need to make sure that the plain text to insert doesn't mess up the surrounding JSON
- ...?

**Comment by abrensch** [comment]
I coded something simple ( https://github.com/abrensch/brouter/commit/f59cbbb5adcd012e180e139aa03665ff840f4fb4 )

Not hunting for100% performance, and not treating these very special unicode cases, but I guess it's good enough.

**Comment by nrenner** [comment]
Great, thanks!
