### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by zzptichka** [abrensch/brouter#206]
I'm running an instance of brouter on Amazon EC2 instance with 1GB of RAM and monitoring memory usage with top.
After each call to brouter, free memory counter goes down by about 9-10MB. Eventually it eats up all memory (there is no swap) and I can't even kill brouter, so the EC2 instance needs complete reboot.
Any idea what's going on?

```:~$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)```

**Comment by abrensch** [comment]
Sounds like you didn't set the -Xmx ?

Usually, it defaults to something like half the available system memory, but maybe that doesn't work on EC2

Try with:

-Xmx128m -Xms128m -Xmn32m

When still problems, look at the heap state (jmap -heap <pid>, jmap -histo <pid>) to understand whats going on.
