### ISSUE TITLE
restrictions do not always work

### ISSUE THREAD

**Issue by polyscias** [abrensch/brouter#210]
Still playing with an urban profile that has decent penalties for for traffic lights I did see some strange behavior with respect to restrictions. Looking better I see them working sometimes perfectly but something they seem to be completely ignored independent from traffic lights.

Using the normal Trekking Bike, Original profile I see:

![Screenshot_20191207_102006](https://user-images.githubusercontent.com/6134878/70372114-d1c88680-18d2-11ea-839a-889b94e19672.png)
http://brouter.de/brouter-web/#map=18/51.89250/4.46095/standard&lonlats=4.461986,51.893651;4.461498,51.893457

It looks like it is completely ignoring the only_straight_on restriction from cycleway towards the Waalhaven Noordzijde

![Screenshot_20191207_102404](https://user-images.githubusercontent.com/6134878/70372159-5ca98100-18d3-11ea-8cdf-f84df7948afd.png)
https://www.openstreetmap.org/relation/10352481#map=19/51.89307/4.46154

**Comment by polyscias** [comment]
Searching further I see more bad behavior but also correct behavior:

![Screenshot_20191207_102623](https://user-images.githubusercontent.com/6134878/70372179-aeeaa200-18d3-11ea-8d3b-445a0ed6242e.png)
http://brouter.de/brouter-web/#map=19/51.83119/4.70600/standard&lonlats=4.706062,51.831216;4.705777,51.831279&profile=car-eco

Big 2,8 km detour because of only_straight_on restriction:

![Screenshot_20191207_094729](https://user-images.githubusercontent.com/6134878/70371698-3d5c2500-18ce-11ea-84b9-ae942c8daf40.png)
https://www.openstreetmap.org/relation/2116528#map=19/51.83082/4.70672

For now I am seeing bad behavior for the Trekking profile/cylcing and not for the car-eco profile/driving.

**Comment by abrensch** [comment]
By default, Turn-Restrictions are considered for car-profiles only ("validForCars")

To consider Turn-Restrictions for a bike profile as well, you can set:

assign considerTurnRestrictions true

See the recum

**Comment by abrensch** [comment]
... bent bike profile for an example:

http://brouter.de/brouter/profiles2/vm-forum-liegerad-schnell.brf

**Comment by polyscias** [comment]
Thanks, just also found in the code that indeed the reason is the considerTurnRestrictions flag

It looks like car profiles (incl. liegerad-schnell) are pessimistic while bicycle profiles are by default optimistic :wink:
