### ISSUE TITLE
For a beter understanding of "voice hint" generation

### ISSUE THREAD

**Issue by EssBee59** [abrensch/brouter#212]
Hello,
I am using the "voice hint" Generation in Brouter for OSMAND (it is much better as generating simple trak´s, as only the really necessary intructions are generated) 
But I do not understand the full behaviour of the Brouter: some times,for me unexpected voice hints are generated.
An example:
Using the standard "trekking" profile with "assign   turnInstructionMode  = 3"

In the  direction „W-S“, no "turn left" hint is generated, this is OK according to the "priority classifier" of the profile.
http://brouter.de/brouter-web/#map=16/49.9525/8.6071/standard&lonlats=8.610655,49.953827;8.605032,49.950213

But by the same route in the opposite direction (N-O), a "turn right" voice hint is generated!
http://brouter.de/brouter-web/#map=17/49.95415/8.60752/standard&lonlats=8.605032,49.950213;8.610655,49.953827

Can some body help me to explain this behaviour?
Regards
Ess Bee

**Comment by abrensch** [comment]
Hi Ess Bee,

well, it's not really documented, but this is the way it is designed.

You could look in the source code and look for the variable "hasSomethingMoreStraight":

https://github.com/abrensch/brouter/blob/master/brouter-core/src/main/java/btools/router/VoiceHintProcessor.java
