### ISSUE TITLE
bicyle:oneway=no still adds costs

### ISSUE THREAD

**Issue by jnns** [abrensch/brouter#214]
![grafik](https://user-images.githubusercontent.com/206281/72837304-93bed080-3c8e-11ea-85ae-d4bc59cb9a93.png)

[This street](https://www.openstreetmap.org/way/36739044) seems to meet all the requirements for routing bicycles through it in both directions yet brouter only allows to ride it along the directions that motor vehicles are allowed to travel.  

Interestingly, it has a tag `bicycle:oneway=no` and  the default (Trekking) profile has this to say about oneway streets:

```
assign badoneway =
       if reversedirection=yes then
         if oneway:bicycle=yes then true
         else if oneway= then junction=roundabout
         else oneway=yes|true|1
       else oneway=-1

assign onewaypenalty =
       if ( badoneway ) then
       (
         if ( cycleway=opposite|opposite_lane|opposite_track ) then 0
         else if ( oneway:bicycle=no                         ) then 0
         else if ( highway=primary|primary_link              ) then 50
         else if ( highway=secondary|secondary_link          ) then 30
         else if ( highway=tertiary|tertiary_link            ) then 20
         else 4.0
       )
       else 0.0
```

If it is changed to `assign onewaypenalty = 0.0` brouter correctly takes the straight route. Why is that and how can it be fixed?

Thanks for putting the effort into this great project by the way! :+1:

**Comment by abrensch** [comment]
>> Why is that and how can it be fixed?

maybe just turn the "bicycle:oneway" to "oneway:bicycle" ?

seems to be a spelling problem
