### ISSUE TITLE
IDEA run configuration paths inconsistent with server.sh

### ISSUE THREAD

**Issue by nrenner** [abrensch/brouter#217]
The `server.sh` script and the [readme](https://github.com/abrensch/brouter#download-them-from-brouterde) assume the `segments4` and `customprofiles` directories to be in the `misc` directory, while the IDEA configuration (#194) has them outside the brouter project dir:

https://github.com/abrensch/brouter/blob/3170f031cc6b46da5b926e08373d7c72e9f664c6/misc/scripts/standalone/server.sh#L21-L29

https://github.com/abrensch/brouter/blob/f1c2b6e412b48f92624ea6139e36cb5d3de41b36/.idea/runConfigurations/RouteServer.xml#L5-L6

I would propose to adjust the IDEA configuration to match the `server.sh` paths and could make a PR for that (I personally created a soft link for `segments4` to a dir somewhere else).

@bagage what is your opinion?

**Comment by bagage** [comment]
Yes sure no problem!
