### ISSUE TITLE
brouter ignoring bicycle=no 

### ISSUE THREAD

**Issue by natrius** [abrensch/brouter#226]
https://www.openstreetmap.org/way/32519777 tagged with vehicle=forestry. In austria it is not allowed to cacle through a forest-path/way if its marked as such. As its not default in germany for example we try to add bicycle=no as well, but this seems to get ignored by brouter. Example http://h2096617.stratoserver.net/brouter-web/#map=17/48.09227/16.20783/osm-mapnik-german_style&lonlats=16.20904,48.091603;16.20816,48.090528 

I get it ignoring the vehicle=forestry but why ignore the bicycle=no ? The austrian law can be found here https://www.ris.bka.gv.at/GeltendeFassung.wxe?Abfrage=Bundesnormen&Gesetzesnummer=10010371 and its § 33. (3) in case you want to read it as well. A related discussion in the austrian forum can be found here https://forum.openstreetmap.org/viewtopic.php?id=68674 just in case.

**Comment by abrensch** [comment]
bicycle=no is not ignored - it leads o a costfactor of about 5 ( see the "$/km = 5350" in the data tab)

So this is the dismount-fallback: if you are allowed to walk, then you are allowed o push your bike.

vehicle=forestry is ignored by intention. It's the same in germany, that from reading the regulations it forbids biking - but it's just not the real-life, as many many signed biking routes use such ways.

Please don't use http://h2096617.stratoserver.net This is the OLD server. Routing requests are forwarded to the new server, but I will stop tha in the near future, and the version of BRouter-Web is not up to date

regards, Arndt

**Comment by wolfbert** [comment]
> vehicle=forestry is ignored by intention. It's the same in germany, that from reading the regulations it forbids biking - but it's just not the real-life, as many many signed biking routes use such ways.

A bicycle is a vehicle, and recreational cycling is not a forestry purpose. Consequently, `vehicle=forestry` means no cycling.

As mentioned above, in Austria cycling on forestry roads is prohibited by default. This can be indicated by a traffic sign (which is tagged as `vehicle=forestry`, about 10.000 cases) or the default (which has not been tagged so far, but may in the future be tagged in the same manner in certain situations).

In case signed routes use forestry roads, these roads are tagged `bicycle=yes` or `motor_vehicle=forestry`, thereby giving permission to bicycles.

I therefore request that `vehicle=forestry` be supported (if not already), as is the case with many other current routers.

**Comment by mcliquid** [comment]
I would propose to create a new issue instead. It's better for visibility and then Linkin to this issue.
