### ISSUE TITLE
Download Manager - not running in background 

### ISSUE THREAD

**Issue by francwalter** [abrensch/brouter#227]
Hallo
The Download Manager is a useful thing, but it is cancelling its download, when in background.
Would it be possible to create an icon in the Notification Bar for running downloads, so they cannot be killed by the system?
The running download blocks the whole phone, and it is not fast, so it takes a good while.
A little background task could solve this.

I know that I can download the segments directly but this is also not so handy.

Thanks.
frank

**Comment by zod** [comment]
Fixed as part of #312
