### ISSUE TITLE
Brouter-Web on mobile: adjust route in between two waypoints

### ISSUE THREAD

**Issue by tauwael** [abrensch/brouter#232]
Previously Brouter-Web (mobile) had the functionality to adjust the route between two waypoints by adding a third waypoint. All you had to do was to click the route and swipe that new waypoint to wherever you want.

This seems to be omitted since the new major update. I was quite used to doing this, so it's hard for me now having to remove all waypoints up to the part I want to adjust. 

A fix would be highly appreciated. 

Kudos to you guys!

**Comment by nrenner** [comment]
Can you please open this issue in the brouter-web repository, thanks:
https://github.com/nrenner/brouter-web/issues/new

**Comment by quaelnix** [comment]
https://github.com/nrenner/brouter-web/issues/285
