### ISSUE TITLE
IGN Scan25

### ISSUE THREAD

**Issue by denisn79** [abrensch/brouter#235]
This map named as "IGN Scan 25" was very useful for France but doesn't work any more, could it be possible to make it working again? 

I use this other map within Locus MAP without any problem, slighly different but ok

http://gpp3-wxs.ign.fr/iv2suivbu1mzyabwnr4k1w2n/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&LAYER=GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-EXPRESS.CLASSIQUE&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&FORMAT=image/jpeg

**Comment by poutnikl** [comment]
It may rather belong to either LocusMap helpdesk/forum, either to nrenner/BRouter-web repository issues. As I connot imagine what BRouter engine would do with such a map.
