### ISSUE TITLE
Slow routing with car 

### ISSUE THREAD

**Issue by MaartenDeen** [abrensch/brouter#237]
When I do [this](http://brouter.de/brouter-web/#map=14/51.2068/4.4671/standard&lonlats=4.505693,51.211749;4.435387,51.198331&profile=car-fast) route, the standard car(fast) routing turns off the motorway, takes secondary and tertiary roads and joins the motorway later for a route of 6,9 km and 14 minutes.
https://i.imgur.com/6UbbVYC.jpg

My idea is that [this motorway route](http://brouter.de/brouter-web/#map=14/51.2068/4.4671/standard&lonlats=4.505693,51.211749;4.470921,51.21124;4.435387,51.198331&profile=car-fast) should be faster, but it is given as 6,7 km and 15 minutes, giving an average speed of 27 km/h on the motorway.
https://imgur.com/4gWFFuD.jpg

Why is the profile calculating such a low speed for that second route? This looks incorrect to me and I assume this is the reason why it does not prefer the motorway.
Maxspeed is filled in on almost all road segments. The motorway has 120, 100 and 70 km/h, the route through Deurne 70 and mostly 50 km/h.

**Comment by abrensch** [comment]
You can see the calculated speed-profile (faked into the elevation diagram) by adding to th profile:

assign showspeed = true
assign inverseRouting = true

that shows a section of 2 m/s. Looking in the data-tab shows "surface=unknown" and looking into OSM databse says "surface=as". I think it's really not a defined value for surface, so it's wrong tagging.

You can also notice that your via-point adds to the time, by beeing assumed as a stop-position. So better use nogos when comparing times of routing alternatives.

regards, Arndt

**Comment by MaartenDeen** [comment]
I'm sure that surface needs to be asphalt. I've corrected it.

That assign thing is new to me. Why does the speed go to 72 km/h as 1.535 km and then go up to 100 km/h again? And similar things happen a number of occasions, not only at the intermediate point and the incorrect surface. Does that also lower the average speed? It shouldn't.

**Comment by abrensch** [comment]
> Why does the speed go to 72 km/h as 1.535 km and ...  similar things ... Does that also lower the average speed? It shouldn't.

That's the kinematic model, it derives implicit speed-limits from a "filtered curvature"

Maybe the formulas need more fine-tuning, but it works pretty good on average.

Code is here: https://github.com/abrensch/brouter/blob/master/brouter-core/src/main/java/btools/router/KinematicPath.java

It start's at 10 degree curves, limiting to 20 m/s (72 kmh). This happened at km 1.535

**Comment by MaartenDeen** [comment]
Problem went away with correcting the surface tag.
