### ISSUE TITLE
Desirability vs speed

### ISSUE THREAD

**Issue by folke** [abrensch/brouter#240]
I'm not entirely sure how I could create a profile that prefers (cost) routes with a lower speed.

Is this something that is currently possible?

An example would be a mountaineering profile that prefers large elevations (high elevation change lowers the cost), but of course the speed of hiking on those routes would be a lot lower. Or said differently, the difficulty of those segments would be higher.

So in the example above, I would be able to use the cost as a way to see how well the route matches with the profile and speed to determine difficulty (compared to default speed)

Side question: in the hiking beta profile, I'd don't find where the default speed is configured. Does brouter have defaults instead? Or did I miss something in the profile definition?

**Comment by poutnikl** [comment]
Not exactly what you look for, but you can get inspired by profiles Trekking-No-Flat and Trekking-hilly-paths from

https://github.com/poutnikl/Brouter-profiles/tree/master/BikeProfiles

Both are on demand custom profiles, addressing the desire to ride rather small paths/roads and avoiding flat roads, each with different approach.

Hiking-beta is a very obsolete beta version of my hiking profiles https://github.com/poutnikl/Brouter-profiles/

There is no explicit speed calculation in the profile, as then current BRouter implementation did not provide any.
The current BRouter calculate speed from the slope profile via some public formula, but it may be incorrect in extreme terrain.

**Comment by poutnikl** [comment]
Note that profile-wise options to prefer high slope ways are very limited and tricky. It can be done only by using costfactor higher then up/downhillcostfactors, and/or indirectly by high preference of small OSM ways, that are supposed to be more hilly.

**Comment by folke** [comment]
Thank you so much for the comprehensive answer!

I'll look into the profiles.
