### ISSUE TITLE
BRouter ignoring way with access=no foot=yes in hiking profile

### ISSUE THREAD

**Issue by bagage** [abrensch/brouter#247]
See [there](https://brouter.damsy.net/latest/#map=17/45.10118/5.06606/standard&lonlats=5.066425,45.10416;5.06386,45.097284&profile=hiking-beta) for instance.

### Steps to reproduce

1. Find some way with `access=no` and `foot=yes` tags. (via [overpass](https://overpass-turbo.eu/s/UAh) for instance)
2. Try to do some routing with BRouter, with `hiking profile` 

### Expected behavior

Way should be considered for routing

### Actual behavior

Way is being ignored even in hiking profile.

**Comment by poutnikl** [comment]
Is it the same for my hiking profiles from poutnikl/Brouter-profiles, or the hiking template from master or develop branch of poutnikl/Hiking-Poutnik ? As the BRouter-web hiking-beta is very obsolete beta version.

**Comment by poutnikl** [comment]
Even the original Hiking beta [routes through](http://brouter.de/brouter-web/#map=16/49.2880/16.6623/standard,Waymarked_Trails-Cycling,route-quality&lonlats=16.662247,49.288131;16.664071,49.285821&profile=hiking-beta) highway=path, access=no bicycle=no, foot=yes

**Comment by poutnikl** [comment]
I noticed there is the different problem - in OSM mapping. The highway=footway with access=no foot=yes has costfactor 1.37. The highway=unclassified has costfactor 2.25. Most of that footway is routable. But at the upper end the connection to the road is broken. Even the shortest routes are lead by a long detour.

**Comment by hungerburg** [comment]
Such paths - access=no;foot=yes - are taken just fine, e.g. https://brouter.de/brouter-web/#map=14/47.3469/11.4534/osm-mapnik-german_style,route-quality&lonlats=11.425599,47.329901;11.438345,47.34558 - at least, if there are no alternatives.
