### ISSUE TITLE
Differences in elevation data

### ISSUE THREAD

**Issue by mjaschen** [abrensch/brouter#252]
A user of my BRouter-web instance at https://brouter.m11n.de/ reported that planned routes show different elevation gain values compared to http://brouter.de/brouter-web/ and https://brouter.damsy.net/.

Example:

- http://brouter.de/brouter-web/#map=12/47.6109/13.3233/osm-mapnik-german_style&lonlats=13.173508,47.596162;13.159105,47.609957;13.164812,47.614305;13.278303,47.626269;13.289439,47.615221;13.311026,47.593837;13.304396,47.594488;13.173631,47.596202
- https://brouter.damsy.net/latest/#map=13/47.6075/13.2502/osm-mapnik-german_style&lonlats=13.173589,47.596187;13.161804,47.614709;13.277732,47.62617;13.311081,47.59381;13.304191,47.59456;13.173676,47.596216
- https://brouter.m11n.de/#map=13/47.6082/13.2557/osm-mapnik-german_style&lonlats=13.173514,47.59617;13.162783,47.614415;13.278418,47.626301;13.289509,47.614929;13.311087,47.593799;13.304168,47.594563;13.173617,47.596195

My guess is that brouter.de and brouter.damsy.net use the same routing data (https://brouter.de/brouter/segments4/) and therefore produce the same results.

My BRouter-web instance is a different story as I'm building the rd5 files by myself. I'm using the “SRTM 90m Digital Elevation Database v4.1” ([downloaded from here](https://drive.google.com/drive/folders/0B_J08t5spvd8RWRmYmtFa2puZEE)).

@abrensch mentioned [here](https://github.com/abrensch/brouter/issues/199#issuecomment-601366622), that there're differences in the SRTM files used for creating his rd5 files and the ones downloaded at a later time. 

I'd like to find out if the mentioned differences have their origin in the different versions of the SRTM data. @abrensch, can you help me to get the SRTM data files that are currently used for generating the rd5 files for brouter.de?

**Comment by abrensch** [comment]
Hi,

I sent you an email with a download link to the files that I am using.

Created from cgiar's srtm 90m data plus some Lidar for northern europe, and converted to a proprietary, binary format ("bef" = Brouter Elevation File)

regards, Arndt
