### ISSUE TITLE
Feature request : draw a straight path between 2 waypoints

### ISSUE THREAD

**Issue by alkuznik** [abrensch/brouter#260]
During a course, I sometimes take small paths or shortcuts which are not shown on the maps and that can be temporary, or I go through an open area, or pathes exist at low tide... To prepare other courses, it would be desirable to be able to represent them. But modifying a map is very difficult, it would be easier to modify a route. Could we have an option allowing to have a straight path between two waypoints, whether or not there is a possible route: the easiest (?) would be to be able to indicate (and trace) that from the current waypoint to the next one that I will create, the path is straight.
Related request : routing across areas #108

**Comment by nrenner** [comment]
What client/app are you using?

For BRouter-Web, see [Allow straight lines · Issue #68 · nrenner/brouter-web](https://github.com/nrenner/brouter-web/issues/68)

**Comment by alkuznik** [comment]
Thank you for your answer. I generate routes on my PC then transfer them on my android smartphone using either Guru Maps or ActiMap. 
Regards, 
alkuznik 


De: "Norbert Renner" <notifications@github.com> 
À: "abrensch/brouter" <brouter@noreply.github.com> 
Cc: "alkuznik" <ajzk2@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Dimanche 12 Juillet 2020 14:05:04 
Objet: Re: [abrensch/brouter] Feature request : draw a straight path between 2 waypoints (#260) 





What client/app are you using? 

For BRouter-Web, see [ https://github.com/nrenner/brouter-web/issues/68 | Allow straight lines · Issue #68 · nrenner/brouter-web ]
