### ISSUE TITLE
crossing highway not possible - wrong routing

### ISSUE THREAD

**Issue by chri2** [abrensch/brouter#269]
There is absolutely no way to cross highway A7 in the place where brouter suggests - neither on foot nor on bike:

http://brouter.de/brouter-web/#map=15/51.5625/9.8897/osm-mapnik-german_style&lonlats=9.886625,51.565434;9.881691,51.568847

Correct would be e.g. the routing like taken from openstreetmap.org using GraphHopper for bike:

https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=51.5648%2C9.8867%3B51.5688%2C9.8819#map=15/51.5638/9.8848

**Comment by poutnikl** [comment]
It is rather an OSM mapping issue. The section across the motorway is mapped as ```highway=unknown```, what BRouter used as a penaliyed, but passable highway.

**Comment by mjaschen** [comment]
It's actually mapped as `highway=razed` (https://www.openstreetmap.org/way/250373235). But I'd consider that a mapping issue, too.

`highway=razed` is [marked as deprecated in the wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Drazed) and should be changed to [the proper lifecycle prefix](https://wiki.openstreetmap.org/wiki/Key:razed:). *taginfo* shows only [664 world-wide uses of `highway=razed`](https://taginfo.openstreetmap.org/tags/highway=razed).

**Comment by poutnikl** [comment]
@mjaschen It may be related to BRouter grouping of supposedly similar tagvalues. BRouter-web shows  unknown.

**Comment by chri2** [comment]
@mjaschen Just found that out, too :) - thanks. Furthermore the connecting `highway=track` to the south and north do not exist (anymore). Everything is overgrown with thorny bushes and trees.

Anyway, brouter shouldn't use `highway=razed` in my opinion.

**Comment by abrensch** [comment]
Yes, "razed" shows up as "unknown" cause it's not in the lookups.dat, and the bike profiles use the optimistic approach of considering unkown as routable.
There's "abandoned" (3800 usages in taginfo) in the lookups.dat and the profiles, will add "razed" (600 usages in taginfo) as well

thanx, Arndt

**Comment by chri2** [comment]
For the actual case I just submitted changes to openstreetmap.org ...

**Comment by mjaschen** [comment]
Looks better now :-)

![](https://static.marcusjaschen.de/dump/covert/g6z2l05tuwgdu523k43irbb182yfer6abg44q8ha/brouter-269.jpg)

**Comment by quaelnix** [comment]
Support for `highway=razed` was added with: https://github.com/abrensch/brouter/commit/1e542d19b7c45a4ee685acf20a858934bb4e2f6c
