### ISSUE TITLE
Routing issue with ferries in Oslo

### ISSUE THREAD

**Issue by larsalonian** [abrensch/brouter#272]
Routing along ferry routes in Oslo has some strange behaviour. Brouter routes me [almost all the way](http://brouter.de/brouter-web/#map=13/59.8880/10.6433/standard,HikeBike.HillShading,Waymarked_Trails-Cycling,route-quality&lonlats=10.732306,59.913078;10.661218,59.876698) from Oslo to Nesoddtangen along the most direct ferry route, but if I [set my destination to Nesoddtangen](http://brouter.de/brouter-web/#map=13/59.8801/10.6418/standard,HikeBike.HillShading,Waymarked_Trails-Cycling,route-quality&lonlats=10.732306,59.913078;10.65659,59.870081) I'm forced to take a different ferry and longer route.

There seems to be some [hidden point](http://brouter.de/brouter-web/#map=17/59.87189/10.65606/standard,HikeBike.HillShading,Waymarked_Trails-Cycling,route-quality&lonlats=10.732306,59.913078;10.657887,59.871639) along the shortest route where routing flops from one ferry route to the other. The ferry route at this point is continuous so the tags don't change, so it must be a routing issue.

I've checked the OpenStreetMap data and the whole ferry route is tagged with `bicycle=yes`.

**Comment by abrensch** [comment]
That's just cost-math

Ferries have a high cost-factor and a high "initial-cost" which is counted for entering a ferry route

The the router prefers low ferry-distance and a low number of ferry-route-enterings

So your "hidden point" is just the cost-equalness at 46.2k, as you can see in the statistics-bar at the bottom of the brouter-web frame.

**Comment by larsalonian** [comment]
Thank you for the explanation. This isn't a realistic way people would use the ferry in Oslo -- cycling an extra 6km to take a slightly shorter ferry route. Is there a way to improve the routing locally or is it only a global ferry cost function which can be updated?

**Comment by theraser** [comment]
You can modify your local profile settings to lower the costs for ferries. Just allow them in general at the "global" section:
```
assign allow_ferries = true
```

Then lower the costs for ferries to a lower value. The default is 5.67 but you want a lower one for Oslo. Just play around using brouter-web where you can edit your profile and test the results:
```
#
# steps and ferries are special. Note this is handled
# before the cycleroute-switch, to be able
# to really exlude them be setting cost to infinity
#
if ( highway=steps ) then ( if allow_steps then 40 else 10000 )
else if ( route=ferry   ) then ( if allow_ferries then 5.67 else 10000 )
```

In your specific example a ferry cost factor of 4.7 does the trick, but it may vary depending of the distance. You just lower the cost for a ferry, but if there is a cheaper alternative using a cycle track this one would be choosen.
