### ISSUE TITLE
Integration guide

### ISSUE THREAD

**Issue by andreynovikov** [abrensch/brouter#291]
Hi, I'm the author of Trekarta application. I plan to add cycling activity in next version, and my users asked me if I can integrate with your routing application. I have tried it and it looks very promising. But I could not find any integration guide.

**Comment by poutnikl** [comment]
You may try to ask to share the integration experience, as Menion, the author of LocusMap application, integrated Brouter into the incoming Version 4. ( Version 3 is integrated via Brouter API )

https://github.com/asamm/brouter

**Comment by abrensch** [comment]
Well, there's not really an integration guide.

For the traditional integration as a separate process (communication via android intends) you could habe a look at the github-repos of OsmAnd or CGeo.

For in-process integration (as Locus 4 will do it) you might start by looking at the BRouter-Web sever process and reverse engeneer something like an API from there.

regards, Arndt
