### ISSUE TITLE
Support paths with segregated cycleways

### ISSUE THREAD

**Issue by flyingOwl** [abrensch/brouter#292]
For a better bicycle routing, I would like to distinguish between "bad" paths that are also used by pedestrians and "good" paths, that have separate lanes.

A bad path might have the following tags:

```
highway=path
bicycle=designated
foot=designated
lit=no
segregated=no
```
See: https://www.openstreetmap.org/way/791351847

A good path might have the following tags:

```
highway=path
bicycle=designated
foot=designated
segregated=yes
oneway:bicycle=yes
sidewalk:surface=paving_stones
cycleway:surface=asphalt
traffic_sign=DE:237
```
See: https://www.openstreetmap.org/way/894661677

Currently they both translate to the following tags in brouter (at least that's what the brouter-web display in the table):

```
highway=path
foot=designated
bicycle=designated
```

They only differ in `oneway:bicycle=yes`, which is only relevant for avoiding one-way streets.

There are already a lot of paths which use `segregated`, for example in Berlin: https://overpass-turbo.eu/s/155l

It would be great if brouter would support this tag for routing (profiles). Having the surface tags available would also be nice :smiley:

**Comment by polyscias** [comment]
For the current list of supported tags, see https://github.com/abrensch/brouter/blob/master/misc/profiles2/lookups.dat

surface is supported, but the default Trekking profile does not use it. Look for an alternative profile like one from https://github.com/poutnikl/Brouter-profiles/wiki

The segregated key is supported but also that is not used in the default Trekking profile, you could try adding it yourself.

**Comment by flyingOwl** [comment]
Oh damn it!

I thought, the "WayTags" on brouter-web are a complete list of all available tags. I added some ifs to check for "segregated" ways to my routing profile and it worked and showed up in the WayTags list.

Thanks for the lookups.dat @polyscias!

Closing issue because support is already there!

**Comment by nrenner** [comment]
> I thought, the "WayTags" on brouter-web are a complete list of all available tags.

By default, only tags used in the profile are shown, setting the profile option `processUnusedTags=true` shows all, e.g. in  [trekking.brf](https://github.com/abrensch/brouter/blob/372a04a6cf4608cf14bc7045aed9499012a23f52/misc/profiles2/trekking.brf#L18).

**Comment by laem** [comment]
I must admit that I don't understand why [this instance](https://brouter.m11n.de/brouter-engine/brouter?lonlats=-4.524436,48.401258|-4.525423,48.400318&profile=safety&alternativeidx=0&format=geojson) returns all the tags, including segregated, whereas the [official one](https://brouter.de/brouter?lonlats=-4.524393,48.401343|-4.530251,48.397611&profile=safety&alternativeidx=0&format=geojson) does not.

**Comment by nrenner** [comment]
It seems like the other instance has the above mentioned `processUnusedTags` flag  active by default for some reason.

**Comment by mjaschen** [comment]
> `processUnusedTags` flag active by default for some reason.

The track analysis is incomplete in many cases if `processUnusedTags` isn't enabled. Enabling that flag for all profiles is the easiest workaround.

**Comment by poutnikl** [comment]
> > `processUnusedTags` flag active by default for some reason.
> 
> The track analysis is incomplete in many cases if `processUnusedTags` isn't enabled. Enabling that flag for all profiles is the easiest workaround.

I assume you mean it in context of webclient - server backend. For android client - Brouter app backend it would lead to slowing down routing.

**Comment by mjaschen** [comment]
> I assume you mean it in context of webclient - server backend.

Yes, of course. Sorry for not mentioning this.
