### ISSUE TITLE
Exclude highway=razed from routing

### ISSUE THREAD

**Issue by bus-mt** [abrensch/brouter#293]
BRouter routes over ways tagged with highway=razed. Example: https://brouter.de/brouter-web/#map=14/52.0361/9.4109/OpenTopoMap,HikeBike.HillShading&lonlats=9.391594,52.047476;9.419489,52.018909 includes https://www.openstreetmap.org/way/358348988/history which goes straight through a power plant.
BRouter should ignore ways tagged as highway=razed.

**Comment by polyscias** [comment]
Have a look at https://wiki.openstreetmap.org/wiki/Tag:highway%3Drazed and you see why this tag is ignored.

Have a look at [taginfo](https://taginfo.openstreetmap.org/tags/?key=highway&value=razed) and you see the numbers are that small it is not surprise it is ignored.

**Comment by mjaschen** [comment]
see PR #294

**Comment by mjaschen** [comment]
It seems that this is a tagging issue. Thanks @polyscias for pointing this out.

**Comment by bus-mt** [comment]
Makes sense. I looked it up in wiki, but only in the german translation where the additional clear hint is missing.

**Comment by abrensch** [comment]
I added alias-values to the lookup.dat:

  proposed planned virtual
  abandoned disused razed demolished dismantled

that's the simplest solution, because it does not require to change profiles
