### ISSUE TITLE
cleanup distance calculation

### ISSUE THREAD

**Issue by abrensch** [abrensch/brouter#3]
3 issues with distance calculation in BRouter:
- duplicate code ( 3 implemantions of public in calcDistance )
- significant distance mismatch compared to other tools evaluating the tracks (earth radius?)
- fails at lon = 180 degree 

However, as distance calucation is called frequently within brouter, any cleanup also must obey the performance constraints

**Comment by Phyks** [comment]
Hi,

I ran a quick test on this one. I'm not exactly sure where the `calcDistance` formula is coming from in BRouter (there are some magical constants, especially the `0.0…01234134` and the `57.3`). 

I tested with a simple segment of about 880 meters and I get:
* 881.6690494652235 from BRouter `calcDistance`. If I don't take any `cos` approximation, I get 889.7434180976005.
* 880.5645655193547 using the [Haversine formula](https://en.wikipedia.org/wiki/Haversine_formula) (no approximations made in the computation of cosine etc).

Concerning the performance constraint, a possible idea would be to precompute a table of values for cosine and sine functions and use it, rather than using a Taylor expansion which might not be optimal.

I think the Haversine formula is the best one for distance computation, but I might be wrong / missing something.

**Comment by nrenner** [comment]
Here the Leaflet implementation:

[LatLng.distanceTo](https://leafletjs.com/reference-1.3.4.html#latlng-distanceto) ([CRS.Earth.distance](
https://github.com/Leaflet/Leaflet/blob/736bd586975987e7429ed0f737dc1c9b51927b03/src/geo/crs/CRS.Earth.js#L17-L32)):

```js
// Mean Earth Radius, as recommended for use by
// the International Union of Geodesy and Geophysics,
// see http://rosettacode.org/wiki/Haversine_formula
R: 6371000,

// distance between two geographical points using spherical law of cosines approximation
distance: function (latlng1, latlng2) {
    var rad = Math.PI / 180,
        lat1 = latlng1.lat * rad,
        lat2 = latlng2.lat * rad,
        sinDLat = Math.sin((latlng2.lat - latlng1.lat) * rad / 2),
        sinDLon = Math.sin((latlng2.lng - latlng1.lng) * rad / 2),
        a = sinDLat * sinDLat + Math.cos(lat1) * Math.cos(lat2) * sinDLon * sinDLon,
        c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    return this.R * c;
}
```

**Comment by Phyks** [comment]
I've just came across https://blog.mapbox.com/fast-geodesic-approximations-with-cheap-ruler-106f229ad016 actually, which is really interesting and might be a perfect match for BRouter. 

Testing code is available at https://gist.github.com/Phyks/2cc48655128f494e400e158ac73f214d.

Typical output is

```
Leaflet implementation:
2.188  # time in s
967.6145333662444  # distance in meters
Current BRouter implementation:
0.007
989.0
Mapbox CheapRuler implementation:
0.056
968.1670119067338
```

The `CheapRuler` code is very fast and gives really accurate results apparently. The overhead is actually coming from the precomputation of the sine values, so this is really a fixed overhead. If you take this one out, it is as fast as the current BRouter implementation.

**Comment by Phyks** [comment]
@nrenner I made a first PR to go in this direction, available at https://github.com/abrensch/brouter/pull/128. If you have knowledge about Java / the backend part of BRouter, feel free to review please :)

Some things are left untouched and could probably be improved, but I'd rather have a first smaller PR with feedback and finish the work afterwards if it is worth it.

Best,

**Comment by abrensch** [comment]
@phyks: I merged your PR and created a second commit with further refactoring. Still needs some testing but looks good. thanx

**Comment by abrensch** [comment]
I'm not yet done resolving test regressions, I will close this here when I'm done. regards, Arndt

**Comment by abrensch** [comment]
> Sure. I found a slight regression due to a bug

thanx, was looking yesterday evening at this line but too tired to see the obvious...

I think there's at least one more in RequestContext.calcAngle, just by (late evening...) code reading, angle calculation ot covered by junit, will need to add a test.

regards, Arndt

**Comment by Phyks** [comment]
Indeed, I missed this typo https://github.com/abrensch/brouter/pull/117/commits/1a2a1164f970817cc8e84e9d53ce8d1290b5ff60#diff-094c17b75f2b091424022f85943c99f4R429. One of next (long termish) goals could probably be to improve the coverage of unit tests, it's super useful! :)

**Comment by abrensch** [comment]
closed. thanx Phyks
