### ISSUE TITLE
foot maxspeed hardcoded

### ISSUE THREAD

**Issue by pkundrat** [abrensch/brouter#301]
Issue #125 implemented ETA computation for bike and hike with nice variables for bike, but for hiking, the max speed is 
hardcoded at 6 (brouter-core/src/main/java/btools/router/StdPath.java line 255)

[https://en.wikipedia.org/wiki/Tobler%27s_hiking_function](Wiki on Tobler hiking function)
The velocity on the flat terrain is 5 km / h, the maximum speed of 6 km / h is achieved roughly at -2.86.
On flat terrain this formula works out to 5 km/h. For off-path travel, this value should be multiplied by 3/5, for horseback by 5/4

So i suggest we reuse maxspeed variable from bike profiles, so that various hiking profiles could redefine this to get proper ETA.

Maybe the same can be achieved by uphillcost/downhillcost, but if you want to create a profile that matches your performance, the fiddling with those values to get the expected result is rather finicky.

**Comment by afischerdev** [comment]
It affects the StdPath class which enables speed handling only for foot or bike. I'd like to enable others as well.
I'd like to fix this with a call of rc.maxSpeed which is init at readGlobalConfig() with 6 when footMode. Profile can overwrite this.
For all others (none foot or bike) speed is forewarded  with speed = wayMaxspeed.

**Comment by afischerdev** [comment]
This brings me to other speed related things on the json format:

- there is a 'showspeed' parameter for json export to show speed instead of elevation..
  What about a new array 'speeds' like the 'times' array from #298 ?
  
- there is a 'speedprofile' array that is shown when 'vmax' is set in profile. But this removes the 'messages' array.
  What about a switch 'sendSpeedProfile' in the profile and then it comes additional to messages?

**Comment by abrensch** [comment]
>> This brings me to other speed related things on the json format:
>>
>> there is a 'showspeed' parameter for json export to show speed instead of elevation..

that's a debug hack and it's intended to see the calculated speed in the elevation diagram

>> there is a 'speedprofile' array that is shown when 'vmax' is set in profile.
>> But this removes the 'messages' array. What about a switch 'sendSpeedProfile'
>> in the profile and then it comes additional to messages?

ja, that's another hack for a (yet) unpublished client for electric car routing.
The change you propose is o.k., however I wasn't sure what I can add to a geo-json
while keeping it valid geo-json

**Comment by afischerdev** [comment]
Ok, I also use the showspeed for debug only. I leave it as before.

I made a short test with a [geojson validator](https://www.npmjs.com/package/geojson-validation).
All situations where valid: with voicehints, speedprofile, messages and mixed.
So I think we can add 'showSpeedProfile'.
