### ISSUE TITLE
default value for "considerTurnRestrictions"

### ISSUE THREAD

**Issue by EssBee59** [abrensch/brouter#307]
Hello,

I observed, that the option "considerTurnRestrictions" is set to false in some profiles (fastbike, fastbike-lowtraffic).
I think, for security reasons, it should be better to set the option to "true" in the standard profiles, so the user could by need change it at own risk (assuming he knows what he is doing)
Here an example showing a routing with the "false" value:
http://brouter.de/brouter-web/#map=16/49.9999/8.6704/osm-mapnik-german_style&lonlats=8.665552,50.001174;8.66993,49.999023&profile=fastbike
Regards
Ess Bee

**Comment by polyscias** [comment]
Yes, I see also the rational for enabling Turn restrictions by default, I think the reason behind disabling it were problems expected where a turn restriction is not valid for cycling. 

I checked https://taginfo.openstreetmap.org/relations/restriction#roles and I do not see any turn restriction with bicycle= so nobody did ever see the need to add bicycle=yes/no and therefore there is no reason to expect problems.

**Comment by afischerdev** [comment]
Ok, I think so.
I'll set on the next update for RoutingContext

`considerTurnRestrictions = 0.f != expctxGlobal.getVariableValue( "considerTurnRestrictions", carMode ? 1.f : 0.f );`

to true for all.

**Comment by EssBee59** [comment]
Thank all for understanding!
I think, the example given above shows the risk associated with a default value to false 
(a turn left at this place is stricly forbidden and very very dangerous)
Ess Bee

**Comment by polyscias** [comment]
Had a look at this again in the light of nrenner/brouter-web#469

I see the check I did in the second message of this topic is not correct, the right thing to do is to check

https://taginfo.openstreetmap.org/keys/restriction#combinations

So there are at the moment 1 628 123 restrictions in OSM of which 188 have _bicycle=_

But for the [restriction mentioned in the issue](https://www.openstreetmap.org/relation/3517068) it looks to me like the expectation there is that "except=bicycle" is interpreted. 
_except=_ is used 9979 times in combination with a restriction. That is also the official way to do it according to [Relation:restriction](https://wiki.openstreetmap.org/wiki/Relation%3Arestriction)

**Comment by abrensch** [comment]
I talked about the relevant TR mapping some time ago: https://youtu.be/eO-9wW1aOJI?t=841

At that time, the mapping with the "except" syntax was dominant, but the "restriction:<mode>" syntax on the rise

BRouter can only handle the "except" syntax.

In addition, BRouter cannot handle TRs with "via ways". But this is also not widely used.

**Comment by polyscias** [comment]
> BRouter can only handle the "except" syntax.

Good to know, nice to have that documented here.

**Comment by polyscias** [comment]
I had a look at taginfo to see how often except and "restriction:" is currently used:

```
bicycle               5633 +   73 - bit 0
psv                   3458 +   31 - bit 3
bus                   1500 +  838
motorcar              1139 +   47 - bit 1
moped                 1104
emergency              674
hgv                    520 + 1106 - bit 4
motorcycle             375 +   12
agricultural           319        - bit 2
taxi                   266
destination            188
residents              171
foot                   151
mofa                   116
school_bus              78
delivery                66
permit_holders          54
tram                    47
resident                30
police                  26
goods                   19
forestry                17        - bit 2
```

The first number is the number of times for except; the "+ <number> is for "restriction:". The bit is according to the code in OsmCutter.java#L272

Would make sense to combine psv and bus I think.

So not missing too much for bicycle, but quite a lot for bus/hgv

One relevant difference between except and "restriction:" is that except is negative and "restriction:" positive
