### ISSUE TITLE
Unable to build on latest master commit 14d5a2c

### ISSUE THREAD

**Issue by hersle** [abrensch/brouter#320]
Hello!

As of the latest master commit 14d5a2c, I am unable to build brouter. I do

```
    git clone https://github.com/abrensch/brouter.git
    git checkout 14d5a2c
    ./gradlew clean build
    ./gradlew fatJar
```

The build completes with no errors, but no `.jar`-files are generated. Attempting to start the server with
```
./misc/scripts/standalone/server.sh
```
gives the errors
```
ls: cannot access '../../../brouter-server/target/brouter-server-*jar-with-dependencies.jar': No such file or directory
Error: Could not find or load main class ......segments4
Caused by: java.lang.ClassNotFoundException: //////segments4
```
By trial and error, I managed to build the project using Maven by reverting to cdac1cc:
```
git checkout cdac1cc
mvn install
./misc/scripts/standalone/server.sh
```
With this, the build completes, `.jar`-files are generated as expected and everything works.

I am just "passing by" and trying to install `brouter` to set up my own local [brouter-web](https://github.com/nrenner/brouter-web) server. I have absolutely no knowledge of Maven and Gradle, but would just like to let you all know in case anything has went by unnoticed, and perhaps help others trying to install `brouter` locally.

**Comment by afischerdev** [comment]
Thanks for the report.
Right, this part is missing
This should be part of the migration from maven to gradle #313 #315 #316 
I'll add this next week.

**Comment by afischerdev** [comment]
@hersle 
Please give it a try and close if it works for you.

**Comment by hersle** [comment]
Thank you!

`./gradlew build fatJar` works now, and the server runs fine.

I am closing this issue, but would also just like to note that the build instructions in README.md seem slightly outdated and contain some typos that I think can be confusing for some people.

**Comment by afischerdev** [comment]
@hersle 
Thanks for the test.
Please give me an idea what do you mean with
> Outdated instruction
And with the typo - I'm not a native speaker so it would be hard to find.

**Comment by hersle** [comment]
I see no problems at all with the language - it is only the commands I was thinking of:

* Is the part about building without the Android app with `gradlew clean build -x :brouter-routing-app:build` necessary? It seems to me that this is handled automatically by `settings.gradle` when `local.properties` with `sdk.dir=...` does not exist.
* I think `gradlew farJar` should be `gradlew fatJar`.
* I am new to gradle etc. and found it a little confusing that the `gradlew` commands referred to the local included script, and initially thought I was missing some system-installed program. Perhaps the commands could say `./gradlew` instead, to make it more obvious?

**Comment by afischerdev** [comment]
@hersle 
Great thanks for the clearing.
- I like the exclude and I use it often - it saves time for me, when I have the sdk.dir set but don't need the app. e.g. server testing
- `gradlew farJar` I've looked to this so many times that I didn't see that.
- `./gradlew` is a good idea. I think Win users will notice it.

**Comment by hersle** [comment]
Sounds very good! Your first point makes a lot of sense. I fixed the mistake, added `./gradlew ...` and also made some other changes in #325.
