### ISSUE TITLE
Customizable Go circles

### ISSUE THREAD

**Issue by theHedster** [abrensch/brouter#329]
Hedley Finger via googlegroups.com 
09:09 (12 minutes ago)
to OSM

I assume these are for Covid-19 circumscribed areas (in lockdowns, the circle centred on your home to which you are confined). Instead of having a button for 15 km and another for 10 km, why not have a customisable circle. In Australia, there are different circular areas to which you are confined during Covid-19 lockdown (in Victoria, 5 and 20 km depending on severity of infection outbreak).

You should be able to add multiple circles to form a Venn diagram showing overlapping areas where people can legally meet.

Regards,
Hedley

**Comment by polyscias** [comment]
This repo is for the brouter Android/Java app, this problem seems to be for the brouter website.

Please move it to https://github.com/nrenner/brouter-web/issues
