### ISSUE TITLE
Topography shadows suddenly changes then is too light

### ISSUE THREAD

**Issue by GuillaumeHM** [abrensch/brouter#330]
Hello there,
I'm a new user of brouter website and I'm not sure what the bug is exactly but behavior is very strange and final result isn't satisfying.
Indeed, topography shadows are too light so it's difficult to understand the topography (while transparency cursor is at max). See picture 2. Shadows contrast is ok on picture 1 for me :
![1](https://user-images.githubusercontent.com/16307397/131956308-15169787-e9e7-4e6e-96c3-455afe4a17af.png)
![2](https://user-images.githubusercontent.com/16307397/131956310-428c7711-e4fe-4d0a-8d8f-9191d5d98a63.png)

Here is what happen :
On page load, shadows contrast is finally like picture 2 (with primarly rendering as picture 1 for a very quick time). If I unzoom and zoom-in again, I sometimes can get back contrast like picture 1.
But even if I can get satisfying contrast, it sometimes suddenly changes back to the bad one. Or it does if I move the map or zoom-in a level more.

Bug reproduced on both https://brouter.damsy.net and http://brouter.de/brouter-web/
I'm ready to help testing or giving more details.

Thank you !

**Comment by polyscias** [comment]
Probably good to mention also which browser you are using and the version.

But this problem should be moved to https://github.com/nrenner/brouter-web/issues, this is the repo for the Andriod/Java app, that repo for the website.

**Comment by GuillaumeHM** [comment]
> Probably good to mention also which browser you are using and the version.

Obviously, thank you.
 
> But this problem should be moved to https://github.com/nrenner/brouter-web/issues, this is the repo for the Andriod/Java app, that repo for the website.

I close this one and create a new one in the web repo.
