### ISSUE TITLE
Possible memory leak in DirectWeaver

### ISSUE THREAD

**Issue by demiantres** [abrensch/brouter#331]
In the DirectWeaver.java, line 181: Linking can create a cycle. I am not certain if the garbage collector ever frees the cyclic OsmNodes.

**Comment by abrensch** [comment]
It does. If there is no more memory-path to a set of interlinked objects, they are collected, no matter what the structure of this set of objects looks like.

In BRouter, the only memory paths to the instance graph are via the set of hollow nodes, and via the set of open paths.
