### ISSUE TITLE
Will there be a new release?

### ISSUE THREAD

**Issue by demiantres** [abrensch/brouter#370]
Hi,

The last release is fairly old (1.6.0?). Is it "safe" to use the master branch when directly integrating the BRouter library into my project or is using the official release the best way to go?

Greetings,

**Comment by afischerdev** [comment]
Sorry I missed: new release coming soon.

**Comment by demiantres** [comment]
Thanks for the Git actions hint. I want to calculate the route between multiple way points using BRouter using different BRouter profiles.

**Comment by zod** [comment]
If you are writing an android app and want to avoid managing the routing data (rd5) yourself you can use the service interface of the BRouter app. The user is then able to manage the data using the BRouter app and your project can calculate routes.
