### ISSUE TITLE
Routing straight on  when trail does'nt exist on map

### ISSUE THREAD

**Issue by ArnoEtxe** [abrensch/brouter#371]
Hi, and thanks for this tool.

Just a suggestion for improvement: when a trail does not exist on the map, in hiking mode, to be able to trace portions of routing in straight lines.
With a right click for example.
And by counting the distance and the altitude.

Best regards
Arnaud Etchegoyhen
a.etchegoyhen@gmail.com

**Comment by abrensch** [comment]
That's https://github.com/nrenner/brouter-web/issues/68

you may also try the "hidden feature" that's best explained here:

https://www.marcusjaschen.de/blog/2021/brouter-direkte-verbindung-zwischen-zwei-wegpunkten/
