### ISSUE TITLE
OsmAnd Brouter no connection - since target Android 11

### ISSUE THREAD

**Issue by vshcherb** [abrensch/brouter#374]
Hello, we've encontoured following issue that OsmAnd couldn't detect to Brouter since it targets Android 11.

https://github.com/osmandapp/OsmAnd/issues/13313

First we've thought it's related to storage, but then we've checked the code and didn't notice what could be the issue. 
https://github.com/osmandapp/OsmAnd/blob/feadaa0da5804d9f3312e6df852ef96093fb82ec/OsmAnd/src/btools/routingapp/BRouterServiceConnection.java#L28

Do you have any ideas? We still hope to use AIDL to connect to BRouter App and use it.

**Comment by afischerdev** [comment]
Hard to say. For me the interface is still working in the old way.
But I have an idea. Please add this in manifest:

```
    <queries>
        <package android:name="btools.routingapp" />

```

**Comment by vshcherb** [comment]
Thanks !!! Fixed and works https://github.com/osmandapp/OsmAnd/pull/13328
