### ISSUE TITLE
car routing then direct line

### ISSUE THREAD

**Issue by abdullahO2** [abrensch/brouter#387]
Thank you for your efforts in this software, and I tried it and found it useful and wonderful, but in my country (Saudi Arabia) there are large desert areas without roads and sometimes we need to go to a place inside that desert, and BRouter does not support routing for places where there are no roads, so I have a suggestion to put a profile that supports A route to the nearest nearby road and then puts a direct line to the specified waypoint, and this solution is found in many applications such as Navitel and Osmand (example):

![image](https://user-images.githubusercontent.com/61907628/147856008-e4fd52c8-7735-4bd0-ac46-16b191dd7b91.png)

If this solution is possible, please guide me on how to do it, thank you

**Comment by abrensch** [comment]
No, in BRouter-(Web), Waypoints are always matched to the routable-network.

There's a hidden feature for some sort of "beeline-routing", by putting a nogo-circle over 2 Waypoints ( see here for details: https://www.marcusjaschen.de/blog/2021/brouter-direkte-verbindung-zwischen-zwei-wegpunkten/ )

that's good if you need a connection within your route where there's no mapped way. But it doesn't help you for off-road start- or detination-points.

**Comment by abdullahO2** [comment]
Thank you, I was hoping to find this solution for applications that depend on BRouter, like Orux, Locus and others, Regards

**Comment by polyscias** [comment]
It is not that if Brouter would add support for direct lines, Apps like Orux, Locus and OsmAnd would directly support direct lines, these Apps have to communicate their desires to BRouter and such new functionality will need code changes in these Apps.

In the link @abrensch posted you can see BRouter has already a way to do this using No-Go-Area's the problem is on the App side to support this. Note that Apps might also support this but just calling Brouter multiple times, only for the pieces so the route where the user wants routing.

Adding this functionality to the Apps, see also [Allow straight lines #68](https://github.com/nrenner/brouter-web/issues/68) seems to be the hard problem, especially the user interface. So if you want this, you better check these Apps, see if there is already a "direct line" request and if not add one.

**Comment by abdullahO2** [comment]
Thank you very much for explaining that, regards

**Comment by abdullahO2** [comment]
Related discussion:
https://github.com/devemux86/cruiser/discussions/204

**Comment by abdullahO2** [comment]
@afischerdev @abrensch Does the current state of development allow for the development of something for this proposal? This is a video to understand the intended proposal:
[ straight line - normal routing - straight line ](https://www.youtube.com/watch?v=ketZyL-vUCU)
and here are clips demonstrating this feature in other applications and drawing a direct line without user interaction:
https://youtu.be/yvXSpP_dkdQ
https://youtu.be/1dD6SDb0Z6Q
https://youtu.be/3Gu9WlyYLRc
 This feature is especially crucial for us in our country, where many places are not accessible by roads, but it is still possible to drive a car through them. Incorporating this feature into the application would make a significant difference to users, and we hope you will consider our suggestion.

Thank you for your attention to this matter.
Best regards,
Abdullah Abdulrahman

**Comment by devemux86** [comment]
@abdullahO2 

Do you ask BRouter to automatically generate straight lines when waypoints are far from the road?
Start and end waypoints or also via points?

All of these seem more suitable for implementation in applications than on the router.

I know I said to implement it in [Cruiser](https://github.com/devemux86/cruiser). :slightly_smiling_face:

**Comment by abdullahO2** [comment]
@devemux86 Thank you so much for explaining that! I understand it makes more sense to handle the "straight line" feature on the app side, given what you've said about complexity and user experience. My knowledge of the development side is limited, so I really appreciate you shedding light on this approach. I'll keep an eye out for updates in Cruiser!

**Comment by afischerdev** [comment]
Sorry for the delay. I had to reactivate my code for this feature.
 I have solution that works almost as expected.
![offroad](https://github.com/user-attachments/assets/4cfedb84-6bc1-434a-a4f0-6c671e98f43d)
But this is in a developer state and need more action.
Example with other context - boat should not go across the shore:
![waterway](https://github.com/user-attachments/assets/881d1b66-7076-4beb-aca6-7d876536f6a8)

And I had some miraculous results - endpoints are very near to each other:

![problem_2](https://github.com/user-attachments/assets/2a81b6ac-bf4c-4b94-b812-d1480bc2e47a) ![problem_1](https://github.com/user-attachments/assets/81d69e2e-5120-44d9-9228-cfc7dda1825a)

I'll go on with this, but my time is very rare, so it will take a while.

**Comment by devemux86** [comment]
@afischerdev 

How does it work, is it optional?
Because there will be users who don't like routes outside the road network.

Does it generate straight line instructions at start / end?

**Comment by afischerdev** [comment]
@devemux86 
> How does it work, is it optional?

Yes, the plan is a switch for the profiles, something like `enableDynamicDistance `.

> Does it generate straight line instructions at start / end?

Yes, when distance between waypoint and crosspoint greater then x then a beeline is created.
May be you like to have a look at this export. 
[testtrack0.gpx](https://github.com/user-attachments/files/16612829/testtrack0.gpx.txt)

**Comment by afischerdev** [comment]
@devemux86 
Yes, all export formats

**Comment by abdullahO2** [comment]
@afischerdev and @devemux86

I am absolutely thrilled to see this progress!  Thank you both so much for your hard work and dedication to this feature. It's incredibly encouraging to see it coming to life.  Knowing that it will be optional and available in multiple export formats is fantastic.

This functionality will be a game-changer for users in areas with limited road networks, like where I live. Your efforts are truly appreciated and will make a significant difference.

Thank you again for considering this proposal and for all the progress you've made. I'm eagerly looking forward to seeing the final implementation!

Best regards,

Abdullah Abdulrahman

**Comment by devemux86** [comment]
@afischerdev Thanks for this implementation!

I started testing the API and the received routes from BRouter (GeoJSON format).
(tested with `assign use_dynamic_range   = true`)

The voice hints seem to be missing at the start of beelines?
- [Route 1](https://brouter.de/brouter-test/#map=16/37.7541/-25.2650/standard&lonlats=-25.267135,37.757704;-25.265701,37.755261&profile=car-fast): there are not any voice hints.
- [Route 2](https://brouter.de/brouter-test/#map=16/37.7541/-25.2650/standard&lonlats=-25.267135,37.757704;-25.264542,37.751544&profile=car-fast): there is only 1 beeline voice hint at the start of 1st beeline.

**Comment by afischerdev** [comment]
@devemux86 
Thanks for the nice samples

Route 1: I can follow this and get same result - no voicehints in json. But I have two in Locus export (gpx, timode02)
              I'll take a look.

Route 2: looks alright for me. First point has a beeline voicehint, a second voicehint at junction. The last point does not meet the generate beeline rule - it is less then 250m away from street. Please see [this](https://brouter.de/brouter-test/#map=15/37.7506/-25.2664/standard&lonlats=-25.267135,37.757704;-25.264542,37.751544&nogos=-25.26405,37.753073,250)

**Comment by afischerdev** [comment]
I think I found the reason:
When we have no detours we don't generate voicehints.
Please [see](https://github.com/abrensch/brouter/blob/adf6bb556935e8d8f662717c26f8a6ba94de60e7/brouter-core/src/main/java/btools/router/OsmTrack.java#L455)
I'll prepare a PR later on.

**Comment by devemux86** [comment]
@afischerdev Thanks, now it seems to work ok. :+1: 

I included it into the latest Cruiser for more user testing:
- https://github.com/devemux86/cruiser/discussions/204#discussioncomment-11284031

**Comment by abdullahO2** [comment]
I used this profile:
[Car profile.txt](https://github.com/user-attachments/files/17817692/Car.profile.txt)

Maybe there was a mistake in my editing of the profile that caused this problem, or maybe there was a problem with the map data.

**Comment by abdullahO2** [comment]
> @abdullahO2 Can you provide a route example as BRouter website link?
> 
> Also please mention what profile you use and what routing options.

https://brouter.de/brouter-test/#map=7/24.431/49.015/standard&lonlats=47.21911,25.997484;51.294883,21.534438

![image](https://github.com/user-attachments/assets/f2bcaee4-579c-49be-ab05-9f9909997ba0)

**Comment by afischerdev** [comment]
With the car profile I got the same error message. With the trekking profile I got a route.
I'll look after this.

**Comment by afischerdev** [comment]
As I said the trekking profile delivers a route. 
I didn't control all roads, but a road near to target has a highway=track and that is not defined in variable `caraccess`.
When you add a line like

`switch and highway=track use_dynamic_range    1
`

You will get a route.
So I think an offroad profile should enable that.

**Comment by devemux86** [comment]
@afischerdev The mentioned profile [above](https://github.com/abrensch/brouter/issues/387#issuecomment-2486076365) contains the `use_dynamic_range`.

**Comment by afischerdev** [comment]
@devemux86 
Ok, I only had a look at the standard profile.
But with this custom profile I get the same route. For me it works.

**Comment by afischerdev** [comment]
@devemux86 
That was not the plan. I'll test it.

**Comment by afischerdev** [comment]
@devemux86 
Here are my results for the parameter `profile:correctMisplacedViaPoints=1`
[Example](https://brouter.de/brouter-web/#map=18/50.00216/8.55370/standard&lonlats=8.553114,50.001561;8.552996,50.002343;8.553844,50.002595)
![snap](https://github.com/user-attachments/assets/8c3a7bbc-06fb-434e-9180-bc88c5c6d298)

Note: this only works in the library. The web client collects data segment by segment.

**Comment by devemux86** [comment]
@afischerdev Thanks very much for checking this! :+1: 

> The web client collects data segment by segment.

I forgot this part. :slightly_smiling_face:

**Comment by devemux86** [comment]
@afischerdev 

Can you check if alternative routes work with the latest code?
I always receive the same route regardless the `alternativeidx`.

While alternatives exist and I can get them with the 1.7.7 code.

**Comment by devemux86** [comment]
@afischerdev The problem seems to be from commit https://github.com/abrensch/brouter/commit/504f8197e6070350bbf1c3ef4407255d98fd3e68.
Without this change the alternative routes work again.

**Comment by afischerdev** [comment]
@devemux86 
Yes, I think so. I've found it as well.
But I'm fighting against some other things of current version. I can't say if I find that today - have to leave soon.

**Comment by afischerdev** [comment]
@devemux86
Alternative routes and END point calculation should run in a better way now. Please see #742.
Available also on test server

**Comment by devemux86** [comment]
@afischerdev Thanks, now it seems to work properly. :+1:
