### ISSUE TITLE
Add lookup support for "level" tag

### ISSUE THREAD

**Issue by theraser** [abrensch/brouter#388]
It would be nice to get access to this tag to be able to get more information about subways/bridges and especially their (standalone) ramps. At the moment we can only prefer/avoid the subways/bridges itself using i.e. "bridge=yes"/"tunnel=yes", but not their ramps which may lead to routing problems.

Example:
Subway which we can prefer/avoid using "tunnel=yes": https://www.openstreetmap.org/way/8055786
Ramp to/from subway which connects two levels and which we cannot prefer/avoid at the moment: https://www.openstreetmap.org/way/198238776

https://wiki.openstreetmap.org/wiki/Key:level
https://taginfo.openstreetmap.org/keys/level#values

![grafik](https://user-images.githubusercontent.com/7988080/147915935-d39b8e9f-1786-45ca-aca2-b025379ee768.png)

**Comment by polyscias** [comment]
I do not know why one should prefer/avoid subways/bridges apart from the slope up/down. If that is "the problem" the solution is I think https://wiki.openstreetmap.org/wiki/Key:incline, [brouter has support for that](https://github.com/abrensch/brouter/blob/15e84c81ea23408abde8605bd57a87a777003ce2/misc/profiles2/lookups.dat#L335), if not, it would help if you can give an example on why to prefer/avoid subways/bridges.

Thanks for the example; I am surprised to see _level=-1;0_ to be used for the way, it means according to the wiki is "a room which goes over (spans) two levels.". I think that is a poor description for this way, it is just a ramp and not something on two levels.

**Comment by theraser** [comment]
In my case I generally would like to avoid footways with _bicycle=yes_ at a bicycle profile with the exception of bridges and subways and its corresponding ramps as these are quite important shortcuts. For bridges/subways itself this is easy, but I do not see any other way then using _level_ tags for the ramps. _incline_ would be possible, but then I have to include **all** ways with some incline - no matter if they're connecting two levels or not. Besides that I would not know any useful way to use _incline_ in Brouter profiles since there are a lot of different ways to tag it (i.e. up/down/5%/-10%).

I don't know any other option than _level=-1;0_ for tagging a ramp which **connects** two levels of a way. But maybe my "logical" approach is a little too much for Brouter :-)

**Comment by polyscias** [comment]
Instead of going into the problem on how to recognize the ramp, how about the access paths, https://www.openstreetmap.org/way/508439726 and https://www.openstreetmap.org/way/198238772 in this case?

Those do not have the level or incline key, so how should brouter know how these two are fine while other highway=footway + bicycle=yes ways are no good? Any idea for that?

I think the best you thing you can do is give highway=footway + bicycle=yes a moderate penalty always, that will cause brouter not to take it unless it means a reasonably big detour.

**Comment by theraser** [comment]
That's a really good point, thanks! The problem with other connecting ways crossed my mind these days, but did not think enough about it. I will try your more general approach using penalties and hope the best :-)
