### ISSUE TITLE
Download Manager is not selectable in version 1.6.3

### ISSUE THREAD

**Issue by finkandreas** [abrensch/brouter#389]
Since the latest update I do not have the chance to download/update map files. The only way to see the download manager again is to delete the folder `segments4`, then I get at startup the download manager. However sometimes I just want to download an additional tile without re-downloading already available tiles.
Do I miss something? Is there a way to open the download manager with version 1.6.3?

**Comment by zod** [comment]
The Download Manager should be available from the main menu. What do you see when you start the app when some tiles are already downloaded?

**Comment by abrensch** [comment]
>> the Download Manager should be available from the main men

... if an internet connection is available

**Comment by finkandreas** [comment]
This is the very first screen I see:
![Screenshot_20220107-121904](https://user-images.githubusercontent.com/15714790/148537097-90ee1942-cb42-4000-9d4e-cab0c8b4e5c9.png)

Then I can click on a profile, and either assign it in server mode or calculate a route. Then BRouter exits again

**Comment by zod** [comment]
The code for detecting if an internet connection is available was changed in 1.6.3 (see also #321). Which android version are you running? Is there anything special about it?

@abrensch I think it's confusing to show the dialog only when the connection is available without informing the user _why_ it isn't shown when no connection is available.

**Comment by finkandreas** [comment]
I'm on Android 8.1.0, Phone is a Moto G5. Nothing very special about my phone, the only interesting thing that could come to my mind is that I'm usually not logged in to the google account, i.e. there's no Google Account in `System --> Users & Accounts`.

**Comment by finkandreas** [comment]
I think I know the problem know. I have a Wireguard VPN. Somehow this makes brouter believing that I have no internet connection. Disabling the VPN tunnel allows me to open the download manager. From my side this can be closed as I have a workaround.

**Comment by ajay-gh** [comment]
Workaround or not, I agree with the comment by abrensch, not to see the dialog because "Brouter believes" that there is no internet access, is poor policy and confusing. So please DO NOT close this issue, fix it if possible. 
My own tests show that there are more then one environmental conditions which Brouter interprets falsely as "no internet". The proper solution is, let Brouter ignore all this, let it assume there is internet, and if a download fails, let Brouter just say so - like hundreds of other apps do. Thanks
