### ISSUE TITLE
Street names in navigation (OsmAnd)

### ISSUE THREAD

**Issue by vziaifqg** [abrensch/brouter#39]
Using BRouter as a service in OsmAnd 1.9.5 gives me excellent directions, but no street names. Do you happen to know in which software that limitation occurs (BRouter or OsmAnd)? Using the default router in OsmAnd gives me street names while navigating.

**Comment by abrensch** [comment]
BRouter does not deliver street names by design. They are not contained in the rd5 data files

**Comment by 0709wiwiwi** [comment]
https://github.com/abrensch/brouter/issues/55#issuecomment-1162874311
