### ISSUE TITLE
Allow also to collect statistics for ways surface from a GPX

### ISSUE THREAD

**Issue by afischerdev** [abrensch/brouter#397]
Would be a very good function to allow also to collect statistics for ways surface from a GPX (useful for gravel/MTB)

_Originally posted by @utagawal in https://github.com/abrensch/brouter/issues/222#issuecomment-1027856759_

**Comment by utagawal** [comment]
Context / Usage : Mountain Biking

When sending a GPX for processing (snapping on the map)it be possible nice to be able to get the below  : 
% of paved surface : X%
% of unpaved surface : Y%
% of unknown surface : Z%

Ultimate intention is to offer the possibility for Mountain Bikers be sure the track is gonna be great experience (eg avoid asphalt)

**Comment by afischerdev** [comment]
I understand your wishes but I think it should be more general. 
Others may be like to see e.g. asphalt and avoid cobblestone.
In my sample you have all available tags on a way and you could parse it for your needs.

**Comment by utagawal** [comment]
Indeed it would work based on your suggestion as a raw response
My suggestion takes it a little bit further allowing the API to send a more high level answer (could be an other parameter to calculate the %)

Whatever is implemented in that direction would definitely be a great help.

**Comment by nrenner** [comment]
@afischerdev isn't it too early to talk about improved response formatting while we don't have a way to turn an external GPX input into a route (map matching)?

@utagawal don't know about your use case, but [BRouter-Web](https://brouter.de/brouter-web/) client has a simple feature to manually load a GPX track and convert it into a route (Load > Load Track as Route) by turning simplified track points into via points and it then can show surface statistics and others for that route.

**Comment by utagawal** [comment]
@nrenner This is for www.utagawaVTT.com, (our site promoting MTB tracks exchange) : when a user uploads a GPX on the site we're looking for a way to get back the %age of asphalt as an additional information for the ones who are going to download the GPX track.

**Comment by afischerdev** [comment]
@nrenner From my point of view this is an output feature only. Why not having information in gpx that we have in json export too?
But you are right map matching is still a big wish.

**Comment by nrenner** [comment]
> Why not having information in gpx that we have in json export too?

I don't really mind. It's just not clear to me yet if the current request by @utagawal for statistics "**from** a GPX" implies that the output should also be GPX - or rather (Geo)JSON that we already provide?

In theory I understand the desire that all output formats should contain the same information. But GPX has a special schema where I find it awkward to add additional information: either by defining an extension or by putting it into comments, where each consumer has to write it's own little parser. And I don't know if it's worth the effort, as I don't see an actual use case or demand for it.

**Comment by utagawal** [comment]
Let me clarify, from a GPX means the input to the API/function is a GPX file. No specific request to have the output in GPX, could GeoJSON as long as it could be parsed.

**Comment by afischerdev** [comment]
Fine, nothing to do. Json will be fit your needs.

@nrenner Yes, parsing that is the hell - see voice hints. And there should be at least one consumer.
