### ISSUE TITLE
Add mtb:scale:uphill

### ISSUE THREAD

**Issue by carg0cult** [abrensch/brouter#40]
http://wiki.openstreetmap.org/wiki/Key:mtb:scale#mtb:scale:uphill.3D0-5
This will be useful to calculate uphillCostFactor

**Comment by zossebart** [comment]
I would also like to have this in the data files. I already asked for this in the brouter google group [https://groups.google.com/d/msg/osm-android-bikerouting/hVRgvEjYd_Y/t3_wtnOGBAAJ](https://groups.google.com/d/msg/osm-android-bikerouting/hVRgvEjYd_Y/t3_wtnOGBAAJ) but got no answer...

**Comment by zossebart** [comment]
should be done since commit e217f12e71d9cba039194cf48d3a7f171573d341 (v1.4.4), so can be closed...

**Comment by utack** [comment]
Yep...can this be closed?

**Comment by utack** [comment]
@carg0cult @abrensch could someone close this?
