### ISSUE TITLE
Tire rolling resistance

### ISSUE THREAD

**Issue by utagawal** [abrensch/brouter#401]
Just found out about Tire rolling resistance :  https://www.bicyclerollingresistance.com/mtb-reviews

Would it be interesting to use these additionnal input data to improve the analysis on Energy spent while biking on the track selected by BRouter ?

**Comment by polyscias** [comment]
The profiles do already have the Rolling resistance coefficient:

`assign C_r        = 0.01   # %C_r% | Rolling resistance coefficient (dimensionless), for travel time computation | number`

See [Rolling resistance coefficient](https://en.wikipedia.org/wiki/Rolling_resistance#Rolling_resistance_coefficient)

You can change this parameter to match the tire.

**Comment by utagawal** [comment]
Very good ! Then it is probably something to do in brouter-web
@nrenner any plans to have a more high level profile editor that could be more user friendly like https://www.bosch-ebike.com/fr/service/assistant-dautonomie/

**Comment by poutnikl** [comment]
You can even tweak other parameters of the bicycle kinematic model, like the total mass ( expedition mode with loaded bicycle ) and effective mechanical sustained cycling power, according to your experience. In such a case, Brouter reports to LocusMap during routing very good ETA, based on your condition and the load.

**Comment by nrenner** [comment]
> @nrenner any plans to have a more high level profile editor that could be more user friendly like https://www.bosch-ebike.com/fr/service/assistant-dautonomie/

@utagawal The `C_r` parameter can also be set in the Options UI (for the session):

![image](https://user-images.githubusercontent.com/1092030/158225299-6863bee3-4167-4b9d-b28b-900828c7b2c1.png)

Lots of room for improvement of course, but no specific plans at this point.
