### ISSUE TITLE
Add lookup support for concrete:lanes and concrete:plates surfaces

### ISSUE THREAD

**Issue by FFMbyBicycle** [abrensch/brouter#404]
Currently these tags are not available at the lookup table and it would be nice to use them for more detailed (bicycle) routing.

https://taginfo.openstreetmap.org/tags/surface=concrete%3Aplates

https://taginfo.openstreetmap.org/tags/surface=concrete%3Alanes

**Comment by mjaschen** [comment]
Maybe #61 helps to solve your problem.

**Comment by FFMbyBicycle** [comment]
Thanks, that solves my issue! Did not expect this, sorry
