### ISSUE TITLE
run on UBports Linux mobile phone

### ISSUE THREAD

**Issue by magdesign** [abrensch/brouter#405]
Hello, thanks for this great project!
Trying to run **brouter** on a OP-6 with [UBports](https://ubports.com/) OTA-22 .

cloned the repo and compiled *.jar with:
`./gradlew clean build fatJar`
which worked without error.

Now trying to run **brouter** locally with:
`java -Xmx128M -Xms128M -Xmn8M -DmaxRunningTime=300 -cp brouter-1.6.3-all.jar btools.server.RouteServer segments4 profiles2 customprofiles 17778 3 127.0.0.1`

Which gives me a terminal response of :
` BRouter 1.6.3 / 21122021`

While opening a browser and visiting` 127.0.0.1` or` 127.0.0.1:17778` nothing appears.

So I tried to run **brouter** with:
` java -Xmx128M -Xms128M -Xmn8M -DmaxRunningTime=300 -cp brouter-server-1.6.3.jar btools.server.RouteServer segments4 profiles2 customprofiles 17778 3 127.0.0.1`

Which gives me a terminal response of :

```
Exception in thread "main" java.lang.NoClassDefFoundError: btools/router/ProfileCache
	at btools.server.RouteServer.main(RouteServer.java:349)
Caused by: java.lang.ClassNotFoundException: btools.router.ProfileCache
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 1 more

```

Any hints on how to run this great piece of software offline on a Linux phone?

**Comment by abrensch** [comment]
>> While opening a browser and visiting 127.0.0.1 or 127.0.0.1:17778 nothing appears.

What do you expect? That's just the server instance, that will not deliver any Web-Page.

Something like this should give you a json-response:

http://127.0.0.1:17778/brouter?lonlats=6.960043,50.910664|6.962451,50.911868&profile=trekking&alternativeidx=0&format=geojson

>> brouter-server-1.6.3.jar gives NoClassDefFoundError: btools/router/ProfileCache

because that's a package-only jar. brouter-1.6.3-all.jar is the full one.
