### ISSUE TITLE
Unable to generate segment file correctly?

### ISSUE THREAD

**Issue by xieyongchao2** [abrensch/brouter#415]
Unable to generate segment file correctly? process_ pbf_ planet. The SH script runs normally. You can only see the generated files in the nodetiles and traffic directories under the TMP directory. But I don't know what these files are used for

**Comment by mjaschen** [comment]
I've also had some problem to get this running but figured it out eventually. I've built a Docker image which provides an one-stop solution for this problem (and wrote some documentation for it). Maybe it's useful for you: https://github.com/mjaschen/brouter-routingdata-builder

**Comment by quaelnix** [comment]
> process_ pbf_ planet

Try the production variant of the script: [process_pbf_planet_production.sh](https://github.com/abrensch/brouter/blob/master/misc/scripts/mapcreation/process_pbf_planet_production.sh).
