### ISSUE TITLE
How to get the elevation of each point?

### ISSUE THREAD

**Issue by xieyongchao2** [abrensch/brouter#418]
How to get the elevation of each point?But not a paragraph

**Comment by poutnikl** [comment]
Laconic questions should not expect good elaborated answers. Omitting important context/background triggers misinterpretation and clarification.

**Comment by xieyongchao2** [comment]
Maybe I didn't say enough. Maybe it's because I'm a beginner. In fact, my question is how to get the elevation data of a certain position on the map?

**Comment by polyscias** [comment]
Getting the elevation data of a certain position on the map is not something brouter or brouter-web provides, that is not one of the  goals. Internally brouter has height data, but only for all points that the internal data has.

If you want to have the elevation data for every point, Credits mentioned on https://brouter.de/
