### ISSUE TITLE
Add routing for trams

### ISSUE THREAD

**Issue by Dimitar5555** [abrensch/brouter#421]
Is it possible to add routing for trams? It should work the same way that train routing works.

**Comment by polyscias** [comment]
Yes, that is possible, just give it a try on [brouter-web](http://brouter.de/brouter-web), select the Rail profile and then edit the profile (press the T key) and change:
```
assign costfactor
  switch railway=rail 1
  switch railway=narrow_gauge 1
  100000
```
into:

```
assign costfactor
  switch railway=tram 1
  100000 
```
I think it will not give the best results always, I think you will be better off with something like https://github.com/geofabrik/OpenRailRouting

**Comment by zod** [comment]
Duplicate of #409
