### ISSUE TITLE
Polylines make too big of a nogo zone

### ISSUE THREAD

**Issue by lpalazzi** [abrensch/brouter#432]
This might just be a more general question about how polygon/polyline nogo areas work, but let me highlight an example of what I'm talking about.

Here is the route generated without any nogos:
![image](https://user-images.githubusercontent.com/33534854/169400241-48cf4e03-7785-4285-9a49-22ba1cb66116.png)

And here is the same route with the two nogos in red:
![image](https://user-images.githubusercontent.com/33534854/169400402-ea855805-9946-407b-bfb1-21e0dbc37444.png)

My question is why wouldn't the route be allowed to pass through that gap between the two polyline nogos? It seems to me that a polyline is creating a bigger nogo area than just the line itself, and I'm wondering if there is a way around this to make just the line itself the nogo area

**Comment by afischerdev** [comment]
Could you tell us please how did you produce this 2. picture?
I did a test with nogo points, seems to work.

![web-router-points](https://user-images.githubusercontent.com/23175706/169513795-c1d23552-58c4-4814-82b4-b61e8b9e13b1.png)

And I did an Android test too

![Screenshot_20220520-123301](https://user-images.githubusercontent.com/23175706/169513848-7e18d455-e04e-42df-a479-b1e06862571e.png)

For this I have defined two nogo lines - routed with BRouter. This is exported and stored in the BRouter import/tracks directory.
Seems to work as well.

**Comment by lpalazzi** [comment]
We're using only the brouter server in a project we are working on, and our own frontend webpage built with leaflet.js (our frontend is forked from [CyclOSM](https://github.com/cyclosm/cyclosm-cartocss-style/)). 

We're not using nogo circles as you used in your first picture, we're using nogo polylines which we store as GeoJSON objects in a database:
  
![image](https://user-images.githubusercontent.com/33534854/169542929-9780d98e-78dd-4e2d-ae94-b3c1a3fb9671.png)

**Comment by lpalazzi** [comment]
Nevermind I found the bug in our code, we were not inserting the "|" character between polylines when parsing our database collection. Works now, thanks! 

![image](https://user-images.githubusercontent.com/33534854/169549359-b20e912a-145a-49ae-8ffb-da4022399c53.png)
