### ISSUE TITLE
Hiking beta doesn't work, cycling yes

### ISSUE THREAD

**Issue by Davdinunu** [abrensch/brouter#438]
I tried to create a path with hiking (beta) routing but it doesn't work (see below link),
with the same points cycling routing works (simple changing the profile and refresh page) it works. 

http://brouter.de/brouter-web/#map=14/44.3853/9.4674/standard&lonlats=9.442406,44.370281;9.441977,44.386017;9.444659,44.394065;9.444863,44.394046&profile=hiking-beta

**Comment by zod** [comment]
We've recently updated the hiking profile provided by BRouter to `hiking-mountain` (#424) but this change is not yet visible on http://brouter.de/brouter-web. The updated profile works correctly.

You can manually check if it works by uploading [hiking-mountain.brf](https://raw.githubusercontent.com/abrensch/brouter/master/misc/profiles2/hiking-mountain.brf) as custom profile.

@nrenner Does it require a brouter-web release before the profile is updated?

**Comment by poutnikl** [comment]
I have tried the latest generated, not yet published version of  hiking-mountain-SAC3 profile in Locusmap planner for the route and it seemed working.

**Comment by nrenner** [comment]
I'm about to make a release anyway, so not worth investigating.

**Comment by zod** [comment]
The updated profile is deployed to brouter.de and the route now works with the hiking profile

http://brouter.de/brouter-web/#map=14/44.3853/9.4673/standard&lonlats=9.442406,44.370281;9.441977,44.386017;9.444659,44.394065;9.444863,44.394046&profile=hiking-mountain
