### ISSUE TITLE
brouter can't traverse a bridge

### ISSUE THREAD

**Issue by edrex** [abrensch/brouter#44]
I've run into a way that brouter should traverse, but won't, with the `fast-bike` profile while trying to find a cycling route from Portland, Oregon to a trailhead in Washington State (just trying out brouter). It's causing an epic reroute through different counties.

I'm assuming it's either

 - an error in the OSM data,
 - or some complication in the OSM data which is confusing brouter.

Here is a simple test case with the start and end on either side of [the problem way (OSM)](https://www.openstreetmap.org/#map=19/45.64118/-121.92823), with `car-test` profile:

<img width="292" alt="screen shot 2015-08-26 at 2 58 41 pm" src="https://cloud.githubusercontent.com/assets/14615/9507459/41fd3e10-4c03-11e5-9061-8419ece2ff33.png">

and with `bike-fast` profile:

<img width="282" alt="screen shot 2015-08-26 at 2 59 03 pm" src="https://cloud.githubusercontent.com/assets/14615/9507462/46e04ecc-4c03-11e5-89d2-c0b2c386c346.png">

The bridge is one-way for car traffic and has a bike lane going the other way. Bikes going with the direction of car traffic are supposed to ride in the lane.

**Comment by edrex** [comment]
I tried this with @osmandapp routing and it too is unwilling to route over the bridge.

**Comment by abrensch** [comment]
It is highway=motorway_link, and standard "fastbike" does avoid motorways in any case.

We already noticed that this is not appropriate for all countries, and created a profile "fastbike-asia-pacific" that evaluates the access-rules in a more formal way, so if you use that, this bridge tagged as motoway_link, bicycle=yes, oneway:bicylce=no is accessible in both directions with no problem.

**Comment by edrex** [comment]
Thanks for explaining what's going on @abrensch, makes sense. Is `fastbike-asia-pacific` much slower to evaluate, or does it give undesirable results in some cases? Just wondering if it would make sense long term to try to create a single profile which works well in all countries.

**Comment by abrensch** [comment]
>> Is fastbike-asia-pacific much slower to evaluate, or does it give undesirable results in some cases?

No speed issue.

The motorway access-rule is "standard" fastbike is just a precaution.

I did not evaluate whether you have more false positiives or false negatives on motorways if you use the correct access logic from fastbike-asia-pacific e.g. in germany. However, a false-positive here is a security issue, while a false-negative is just an annoyance.

This correct access logic does not only enable bike access on motorways for bicycle=yes, but also for access=yes or vehicle=yes - this is where I think the falso positives could originate from. Should do some quality assurance before enabling that as the default.

Another difference between fastbike and fastbikle-asia-pacific is teh handling of highway=trunk. In germany, there are trunks without any formal bike access restriction that you never would consider for biking. This is why trunks are strongly avoided in "fastbike". But this is something that does not work e.g. in Japan or Australia.
