### ISSUE TITLE
Brouter, Update segments?

### ISSUE THREAD

**Issue by troNpo** [abrensch/brouter#440]
Hello !!I am an Oruxmaps user and I use Brouter as an external router.I wonder what is the update policy for the trails? I guess Brouter web will have an automatic update regarding to what's new in openstreetmap.But how does the app work?Every time I  like I manually delete my zones in the Brouter app, and I download again with the intention of updating,I don't know if I can do it by doing this...?As a user, it would be very useful for the app to have a "button" to activate the update of downloaded zones, or to be able to program these update somehow.Thanks a lot.

**Comment by troNpo** [comment]
perfect!! it was just what I wanted, thank you very much, previously I deleted the files  rd5, and it downloaded again, but I see that it did not need to delete first.Thank you for assisting me.

**Comment by troNpo** [comment]
@puchero forgive my ignorance, for "differential update"

**Comment by troNpo** [comment]
@puchero excuse my ignorance,the update depends on the area where I use the router? and when updating I only download,the routing segments, what am I missing?

**Comment by poutnikl** [comment]
@troNpo I am confused, it looks like you try to refer to me, but you refer to a username puchero instead.

Brouter  routing data (downloaded from OSM and processed) are stored for map areas organized in tiles 5x5 latitude/longitude degrees in RD5 files. The most convenient way to download/update them is doing so manually within the download manager of BRouter application by selection respective tiles for download/update on a map.

When the selected tile files is not present, or is older than like 7-8 days, the full file is downloaded, with the variable size, up to like (AFAIK) 120 MB per tile, depending on area map complexity.

When the selected tile files is present and not more than 7-8 days old, only the difference data between current file and latest downloaded file is downloaded. It is typically just few MB. It does not necesserily mean it is faster, as there is data processing, but it safe a lot of data when updating frequently.

**Comment by troNpo** [comment]
I'm perfectly clear, thank you very much for your explanation and patience.I do not handle GitHub chat well, as you have seen Excuse me. Thank you and congratulations for your work.
