### ISSUE TITLE
calculated Ascend  by many route points

### ISSUE THREAD

**Issue by EssBee59** [abrensch/brouter#447]
Hello,

By tests I had strange results of the "Ascend" values:
The same route was first calculated using 2 route points:

..  /#map=9/49.5609/8.7849/osm-mapnik-german_style&lonlats=8.695385,50.049443;8.400141,48.994887&nogos=8.718114,49.844412,7592&profile=fastbike

 And calculated again using "load track as route" with many many route points:

#map=9/49.5248/8.5468/osm-mapnik-german_style&lonlats=8.695385,50.049441;8.696078,50.015579;8.692667,50.013593;8.681951,50.002069;8.673,49.952945;8.66268,49.938421;8.654979,49.922663;8.645936,49.919934;8.644594,49.914688;8.626644,49.914914;8.592385,49.906424;8.592707,49.903379;8.596987,49.900936;8.598296,49.898634;8.592832,49.898308;8.587181,49.884648;8.587544,49.880483;8.565639,49.880208;8.564302,49.878494;8.565378,49.870567;8.555909,49.869326;8.558342,49.858865;8.554241,49.858185;8.563602,49.83028;8.579536,49.827873;8.585696,49.818927;8.589711,49.809926;8.598318,49.801335;8.603595,49.78372;8.614832,49.775124;8.609304,49.771297;8.613415,49.760774;8.610703,49.753771;8.608928,49.730673;8.607837,49.730824;8.608183,49.728731;8.606042,49.726821;8.603016,49.726838;8.601434,49.7249;8.601445,49.722046;8.603923,49.719583;8.609102,49.70751;8.610549,49.699174;8.609878,49.692959;8.603045,49.681727;8.602953,49.678327;8.586694,49.675153;8.583344,49.670759;8.585177,49.667411;8.584414,49.66548;8.581112,49.662955;8.568061,49.659746;8.567662,49.655329;8.564732,49.652662;8.567661,49.651145;8.567184,49.645433;8.571854,49.628704;8.574874,49.622249;8.578454,49.61863;8.583938,49.60642;8.580043,49.598718;8.580119,49.595677;8.589471,49.587875;8.589651,49.579288;8.58334,49.557641;8.587103,49.553257;8.586083,49.552542;8.587968,49.54932;8.592195,49.547645;8.587683,49.543852;8.590044,49.536246;8.58869,49.535335;8.594183,49.532988;8.592789,49.528829;8.594621,49.524807;8.592068,49.522524;8.59384,49.521132;8.59785,49.507833;8.599751,49.507443;8.599024,49.505095;8.601228,49.504605;8.602167,49.500572;8.601869,49.484303;8.59514,49.474578;8.601691,49.47253;8.598333,49.468899;8.607474,49.457476;8.609184,49.450727;8.614268,49.44674;8.603894,49.440069;8.599238,49.425917;8.594122,49.418093;8.594863,49.416052;8.592568,49.410343;8.592194,49.402601;8.598112,49.395283;8.597236,49.39379;8.598276,49.386807;8.583291,49.365674;8.583284,49.362194;8.573564,49.337168;8.56021,49.329767;8.557246,49.325526;8.564014,49.318819;8.56034,49.313534;8.556701,49.311227;8.562199,49.307412;8.563695,49.304254;8.565308,49.303945;8.57403,49.294597;8.567385,49.293019;8.560059,49.286308;8.566695,49.284879;8.515487,49.204638;8.513076,49.202896;8.507111,49.201804;8.509996,49.198603;8.509698,49.195543;8.492607,49.167516;8.482837,49.158473;8.483883,49.157808;8.482361,49.156878;8.484931,49.153465;8.483568,49.151411;8.484822,49.149859;8.47513,49.137215;8.47661,49.131633;8.474209,49.124839;8.476871,49.120773;8.472669,49.104757;8.41108,49.022813;8.417557,49.017533;8.417594,49.009634;8.412263,49.006093;8.403457,49.005644;8.402916,49.000477;8.404223,48.997042;8.400141,48.994887&nogos=8.718114,49.844412,7592&profile=fastbike

It would be nice to get the same result in both cases (in order to get a better occuracy by comparing different routes)
regards

**Comment by EssBee59** [comment]
I think, this problem is not due to Brouter, it seems a brouter-web issue!

I close this issue

**Comment by EssBee59** [comment]
I open this issue in brouter-web!

**Comment by nrenner** [comment]
### 1. It's not a client issue  

For now, you can still download the full route from the server with the small middle button in the brouter-web Export dialog, without  the client being involved. And grab the server URL in the Network tab of the browser Devtools to download and compare directly from the server (e.g. on Linux command line):

```
curl -s "https://brouter.de/brouter?lonlats=8.695385,50.049443|8.400141,48.994887&nogos=8.718114,49.844412,7592&profile=fastbike&alternativeidx=0&format=gpx" | grep "filtered ascend = "

<!-- track-length = 141774 filtered ascend = 85 plain-ascend = -7 cost=161946 energy=.7kwh time=6h 54m 27s -->
```

```
curl -s "https://brouter.de/brouter?lonlats=8.695385,50.049443|8.696078,50.015579|8.681951,50.002069|8.678888,49.986579|8.659381,49.980925|8.657799,49.979908|8.657829,49.976709|8.654738,49.97645|8.653396,49.966356|8.654837,49.963701|8.654396,49.961745|8.652741,49.961558|8.648838,49.931183|8.641456,49.932475|8.63842,49.928717|8.636968,49.915613|8.625179,49.914626|8.594934,49.906937|8.596957,49.904674|8.598296,49.898634|8.592832,49.898308|8.587181,49.884648|8.587544,49.880483|8.565109,49.879961|8.565378,49.870567|8.555909,49.869326|8.556609,49.864173|8.5551,49.863914|8.554079,49.861235|8.563509,49.830234|8.579481,49.828252|8.589711,49.809926|8.598318,49.801335|8.603307,49.784238|8.623759,49.768397|8.619367,49.755134|8.610746,49.754043|8.608928,49.730673|8.608106,49.731826|8.61173,49.727008|8.613702,49.720747|8.613083,49.717722|8.617599,49.710756|8.61909,49.703464|8.621884,49.70024|8.621736,49.683183|8.619691,49.682607|8.619138,49.677508|8.622508,49.677924|8.626312,49.669239|8.633818,49.661696|8.639895,49.645774|8.638918,49.642212|8.641929,49.635378|8.641447,49.626666|8.648747,49.619997|8.654523,49.611438|8.654651,49.606127|8.651617,49.605591|8.649241,49.596211|8.650442,49.593911|8.649312,49.590623|8.653702,49.582025|8.647076,49.581356|8.647555,49.57614|8.645547,49.576159|8.649503,49.565431|8.644568,49.558343|8.644557,49.556232|8.637377,49.550218|8.63953,49.548764|8.629897,49.546988|8.630903,49.540508|8.621098,49.540354|8.618014,49.527835|8.607652,49.514731|8.601387,49.50273|8.602121,49.499338|8.606584,49.498898|8.608024,49.484571|8.611243,49.484055|8.605428,49.478123|8.60646,49.474282|8.602942,49.473829|8.598333,49.468899|8.607567,49.457456|8.609184,49.450727|8.614268,49.44674|8.603894,49.440069|8.599238,49.425917|8.594122,49.418093|8.594863,49.416052|8.592568,49.410343|8.592194,49.402601|8.598112,49.395283|8.598276,49.386807|8.583131,49.365566|8.583201,49.362154|8.573564,49.337168|8.560242,49.329746|8.554198,49.321757|8.558045,49.317993|8.553959,49.313378|8.562199,49.307412|8.563242,49.304147|8.565147,49.303933|8.569249,49.298638|8.565089,49.29517|8.567619,49.293152|8.560034,49.286254|8.566728,49.285347|8.566429,49.284437|8.533414,49.233241|8.52665,49.220116|8.524666,49.219118|8.515132,49.204171|8.511133,49.202347|8.509686,49.195041|8.496385,49.172822|8.482837,49.158473|8.483883,49.157808|8.482361,49.156878|8.484945,49.153389|8.483568,49.151411|8.483982,49.148585|8.474963,49.136626|8.47661,49.131633|8.474209,49.124839|8.476871,49.120773|8.472669,49.104757|8.41102,49.022734|8.416843,49.018664|8.412667,49.016921|8.411957,49.013721|8.410333,49.013786|8.408311,49.011082|8.41003,49.009664|8.41016,49.006106|8.403457,49.005644|8.402423,48.999287|8.399005,48.998345|8.400141,48.994887&nogos=8.718114,49.844412,7592&profile=fastbike&alternativeidx=0&format=gpx" | grep "filtered ascend = "

<!-- track-length = 144402 filtered ascend = 338 plain-ascend = 52 cost=183194 energy=.7kwh time=6h 39m 5s -->
```

### 2. The tracks are different, so not comparable

The route result differs in multiple places as you can see from differences in the elevation graph and when comparing the second with a loaded track of the first.

**Comment by EssBee59** [comment]
Hello,

For the same route the calculated Ascend seems grantly affected by the number of route-points used.
(It could be a similar problem to the "voiceHint" generation)

The brouter-web generates a request to brouter for each intermediate route, and probbably adds the intermediate ascends
But  it seems the brouter do the same when only 1 request with N route-points is posted.

It could become very difficult to find a solution using brouter-web: I only see a chance by recalculating the ascend in brouter-web itself using the track allready available.

The use case (compare the ascend of existing tracks) is not critical, but if anybody have a solution...

**Comment by EssBee59** [comment]
reopend after clarifications wit brouter-web

**Comment by polyscias** [comment]
> The brouter-web generates a request to brouter for each intermediate route, and probably adds the intermediate ascends

No, there is no way to include intermediate ascends or even heights in a brouter request.

> But it seems the brouter do the same when only 1 request with N route-points is posted.

Not clear to me what you want to say with this sentence.

I tried both commands (without asking for turn instructions) and I am not sure why but I get two .gpx routes that are not exactly the same. In both cases it gives a plain track with (only) the height of every track point, for example:

```
 <trk>
  <name>brouter_fastbike_0</name>
  <trkseg>
   <trkpt lon="8.695385" lat="50.049441"><ele>127.0</ele></trkpt>
   <trkpt lon="8.695385" lat="50.049440"><ele>127.25</ele></trkpt>
   <trkpt lon="8.695393" lat="50.049360"><ele>127.75</ele></trkpt>
   <trkpt lon="8.695295" lat="50.049354"><ele>127.5</ele></trkpt>
   <trkpt lon="8.695253" lat="50.049354"><ele>127.5</ele></trkpt>
   <trkpt lon="8.695252" lat="50.049032"><ele>128.5</ele></trkpt>
   <trkpt lon="8.695229" lat="50.048945"><ele>128.5</ele></trkpt>
   <trkpt lon="8.695223" lat="50.048856"><ele>128.75</ele></trkpt>
   <trkpt lon="8.695228" lat="50.048641"><ele>128.75</ele></trkpt>
   <trkpt lon="8.695243" lat="50.048238"><ele>127.0</ele></trkpt>
   <trkpt lon="8.695244" lat="50.048210"><ele>127.0</ele></trkpt>
   <trkpt lon="8.695245" lat="50.048186"><ele>126.75</ele></trkpt>
   ...
  </trkseg>
 </trk>
</gpx>
```

So brouter only provide the height for every track point, other software can use that information to calculate ascends.

**Comment by EssBee59** [comment]
> So brouter only provide the height for every track point, other software can use that information to calculate ascends.

This was also my thought till yesterday!
But as explained above by Norbert, the ascend is provided in each gpx delivered by brouter (see the second line of the GPX)

**Comment by nrenner** [comment]
brouter-web currently uses the stats provided by brouter, as [GPX](https://brouter.de/brouter?lonlats=8.695385,50.049443|8.400141,48.994887&nogos=8.718114,49.844412,7592&profile=fastbike&alternativeidx=0&format=gpx):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- track-length = 141774 filtered ascend = 85 plain-ascend = -7 cost=161946 energy=.7kwh time=6h 54m 27s -->
<gpx 
```
but actually from [GeoJSON](https://brouter.de/brouter?lonlats=8.695385,50.049443|8.400141,48.994887&nogos=8.718114,49.844412,7592&profile=fastbike&alternativeidx=0&format=geojson):
```json
     "properties": {

        "track-length": "141774",
        "filtered ascend": "85",
        "plain-ascend": "-7",
        "total-time": "24867",
        "total-energy": "2487130",
        "cost": "161946",

```

But yes, clients could calculate those themselves and we will probably do so in the near future, also because of [brouter-web#426](https://github.com/nrenner/brouter-web/issues/426).

**Comment by EssBee59** [comment]
> Not sure if you mean this situation.

Hello,
No, the situation I mean is a route created with different rtept´s.
I think, the ascend calculation is done with a filter, and adding the ascends of many intermediate routes leads to the differences.

(see comment of Norbert above for a future solution in brouter-web)

For Brouter itself: could you check how the ascend is calculated currently when a request contains many rtept´s?
(same as for voiceHint generation: calculation should be done on the whole track, not on the separated intermediate routes)

**Comment by afischerdev** [comment]
@EssBee59 
Thanks for the clearing.
Now I did what you suggested: do the calucation in a post process.
I tested with your first sample (2 points) and made from teh result a 50 point input gpx. 
The diff brings now the same distance and the same  ascend values by the same track points.

**Comment by EssBee59** [comment]
I can confirm, the ascend calculation is now right, also when many route points are used! 
(good to know  that the change leads to a right result, a similar change in brouter-web should also be successfull)

**Comment by quaelnix** [comment]
The non-client side part of this bug was fixed by: https://github.com/abrensch/brouter/pull/498
