### ISSUE TITLE
Could we add OpenCycleMap as one of the available layers in Brouter

### ISSUE THREAD

**Issue by Asteliks** [abrensch/brouter#452]
Hi,
I would like to propose that we add https://www.opencyclemap.org/ to Brouter webpage. Idealy here as one of the main layers:
![image](https://user-images.githubusercontent.com/62251475/180955399-14ff1bdf-d9d6-4667-b986-b46b1c2f8b87.png)

This layer seems to be more useful than the default OSM one as it is trying to improve the visibility of cycle ways. Of course I would prefer CyclOSM but the server is not as fast when it comes to rendering tiles.

**Comment by poutnikl** [comment]
OCM was there for long time, but it has been removed later. AFAIK for data licence reasons, as the fees for data consumption would be too high for Brouter-web.

Note that there is the independent, yet closely related dedicated GitHub project  [Brouter-web](https://github.com/nrenner/brouter-web)

**Comment by nrenner** [comment]
See
- https://github.com/nrenner/brouter-web/issues/145
