### ISSUE TITLE
Access to angle information?

### ISSUE THREAD

**Issue by julianbenner** [abrensch/brouter#46]
If I understand it correctly, it is possible to define a "turncost" variable in the routing profile, which in turn is used to calculate the cost of turns depending on the turn angle.

However, in city traffic, the angle itself is much more important, as it can be used to determine left turns and right turns which should be treated differently. Can I directly access this angle? In general, is there an exhaustive documentation of the routing profile?

**Comment by poutnikl** [comment]
The topic is rather tricky.   There is no way in current Brouter profiles to detect crossroads and to distinguish crossroad_turns  and road_turns. For the crossroads, there is no way to distinguishing the road priority patter either. 

E.g. you are not able to define penalty for passing a crossroad, unless indirectly via turncost and initialcost, what has its own flaws.

Turncost variable is evaluated just as slowing down penalty of a single 90 deg turns, regardless of direction or if being crossroad turn or not. Note that for bicycle the difference between crossroad left and right turns is much smaller than for cars.

Currently the most complete documentation I am aware of is here 
http://brouter.de/brouter/profile_developers_guide.txt

**Comment by abrensch** [comment]
Problem with additional context information in the profile's scope is that it would be no longer context free, making it impossible to use a cache to reduce the number of profile evaluations.

Sure, the performance impact would be not so dramatic, but I would have to distinguish whether or not a profile accesses such information, and that would add to the complexity.

For the similar problem in the 3rd dimension (access to slope information), we came up with another solution for exactly that reason: here we do not use a slope-depended costfactor, but have 3 different costfactors for up, down and even.

I think the junction analysis is an open issue where I probably will come up with some other solution,
