### ISSUE TITLE
oneway:bicycle being ignored by cycling profiles

### ISSUE THREAD

**Issue by joostschouppe** [abrensch/brouter#465]
This road shows up in the wrong direction in all cycle routing profiles https://www.openstreetmap.org/way/23492188 . It's been oneway:bicycle=yes for two years.

**Comment by polyscias** [comment]
Not sure what you are seeing, I [tried brouter-web](http://brouter.de/brouter-web/#map=18/50.80810/4.28987/standard&lonlats=4.28897,50.807884;4.2914,50.808521) and it looks fine to me

**Comment by joostschouppe** [comment]
I must have made a mistake
