### ISSUE TITLE
Merge OSM parsers

### ISSUE THREAD

**Issue by zod** [abrensch/brouter#468]
Currently BRouter contains two parsers for OSM data
* [XML parser](https://github.com/abrensch/brouter/blob/master/brouter-map-creator/src/main/java/btools/mapcreator/OsmParser.java)
* [PBF parser](https://github.com/abrensch/brouter/blob/master/misc/pbfparser/OsmParser.java)

According to the [README of PBF parser](https://github.com/abrensch/brouter/blob/master/misc/pbfparser/README.txt) the XML Parser is just for testing and I found some issues. It doesn't use a XML parser library and therefore rejects some files which are valid XML (e.g. it doesn't parser JOSM exports correctly because of different quotes).

It seems like the PBF parser should be used but it's not integrated into our build because of the osmosis dependency. This causes more work for users. @mjaschen provides a nice [Dockerfile](https://github.com/mjaschen/brouter-routingdata-builder/blob/main/Dockerfile) which handles building BRouter with PBF parser.

We use gradle / maven to get our dependencies and osmosis is available via [maven central](https://central.sonatype.dev/artifact/org.openstreetmap.osmosis/osmosis-osm-binary/0.48.3).

Perhaps we should just remove the XML parser and add osmosis as a dependency for map-creator.

**Comment by polyscias** [comment]
Yes, I think the XML parser should be removed, see [Planet.osm](https://wiki.openstreetmap.org/wiki/Planet.osm):

> PBF (Protocol Buffer Format) is a compact binary format that is smaller to download and much faster to process and should be used when possible. 

The PBF parsing is done using osmosis and that does work nicely for me, I found a problem with extensions but with that patched I was able to generate all .rd5 file for a planet.pbf file.

**Comment by afischerdev** [comment]
@mjaschen 
Yes, I've tested and I found a problem with hgt handling.
A change on this is part of PR #556 ([please see](https://github.com/abrensch/brouter/pull/556/commits/3ea409078ef08d4f912e761916ef09d891c4ed60))

**Comment by mjaschen** [comment]
Ah, I see, thanks for updating me on this. Will follow the PR/discussion :-)

**Comment by zod** [comment]
It was caused by #548 and I've added a PR (#557) which also includes the fix from @afischerdev and uses elevation data in tests which should keep us from breaking this stuff again ;)

**Comment by mjaschen** [comment]
@zod Thanks :-)
