### ISSUE TITLE
Documentation on naming convention for nogo-areas is hard to find

### ISSUE THREAD

**Issue by sjakobi** [abrensch/brouter#475]
I stumbled across a reference to this convention in https://github.com/abrensch/brouter/blob/master/docs/features/vianogo.md.

In order to find more documentation on this I eventually resorted to `git grep convention` which lead me to `docs/users/android_advanced.md`.

Googling for a text passage from that document helped me find https://brouter.de/brouter/readme.txt, but this document is for v1.4 and therefore possibly out of date.

Not sure how to best fix this, but a cross-reference from `vianogo.md` to `docs/users/android_advanced.md` would probably be helpful.

**Comment by zod** [comment]
Thanks for you feedback, I've added the reference as suggested. We have some updated documentation in our docs-folder but they aren't yet published to brouter.de (#373). Currently there is a preview at https://zod.github.io/brouter/

**Comment by sjakobi** [comment]
Whoa! Thanks for addressing this so quickly! :+1:
