### ISSUE TITLE
Problem with roundabout on some bike profiles

### ISSUE THREAD

**Issue by afischerdev** [abrensch/brouter#485]
In the experiments with Dreieich I found an issue on roundabout in some bike profiles. Very short way.

An increase of 'onewaypenalty' could help I think.

Please have a look [here](https://brouter.de/brouter-web/#map=17/50.00114/8.70136/osm-mapnik-german_style&lonlats=8.700753,50.000704;8.702245,50.000664&profile=fastbike) and play around with the other profiles.

BTW: do we have something like a notice 'use at your own risk'?

**Comment by EssBee59** [comment]
Hello,

Using my own profile (fastbike-verylowtraffic) the routing is ok!
http://brouter.de/essbee/#map=19/50.00048/8.70227/osm-mapnik-german_style&lonlats=8.700753,50.000704;8.702245,50.000664

The tags in the critical roundabout part are:
reversedirection=yes highway=residential maxspeed=30 junction=roundabout route_bicycle_lcn=yes

With the following logic the cost ($/km)  would be =  7700, so the right way is calculated

**Comment by zod** [comment]
> An increase of 'onewaypenalty' could help I think.

The oneway penalty assumes that you are allowed to walk in the wrong direction. I think for *fastbike* this assumptions is wrong, because all the road bikers I know would rather ride triple distance instead of walking.

> My profile use the logic below, and the cost ($/km) would be = 7700 in the part of reverse direction, so the right way is calculated !

That code seems identical to the normal [*fastbike*](https://github.com/abrensch/brouter/blob/master/misc/profiles2/fastbike.brf#L126). I guess we need slightly different parameters.

**Comment by quaelnix** [comment]
> An increase of 'onewaypenalty' could help I think.

Yes, I would probably solve it like this:
```
assign onewaypenalty =
         ...
         else if ( oneway:bicycle=no                         ) then 0
         else if ( junction=roundabout                       ) then 60
         else if ( highway=primary|primary_link              ) then 50
```
