### ISSUE TITLE
OSMand path to read coords and nogo areas and to write tracks

### ISSUE THREAD

**Issue by Thunichgud** [abrensch/brouter#491]
LineageOS 18.1 (Android 11)
    OSMand+Live 4.3.4
    BRouter 1.6.3 API 19

Because of the "<ext-SD-Card>=>Android=>data"-restrictions of Android 11, I now installed BRouter as recommended in the directory "Android=>media". With the same reason I installed OSMand also in "Android=>media" and hoped, that BRouter could read the coords there again and could write the tracks directly to the Tracks-directory of OSMand. 
Therefore I wrote as recommended into the storageconfig.txt of BRouter the path to OSMand:
additional_maptool_dir=/storage/<my ext-SD-Card>/Android/media/net.osmand.plus
But BRouter always looks only into its own directory "brouter/import", finds there no coords and aborts. I also tried the path extension to the directory "favorites" of OSMand, but the result was the same. BRouter 1.6.3 ignores the path of the additional_maptool_dir. So it is not possible to read the coords directly from OSMand and to write the tracks also directly to OSMand. This should be changed in next version of BRouter, or is there an other way to solve this problem in 1.6.3 ?

**Comment by afischerdev** [comment]
> But BRouter always looks only into its own directory

Yes, that is the modern way it goes since Android 11. Apps have only file access in there own folders (Android/data or Android/media). 'Data' is not visible anymore, only 'media' is open for other apps like file manager. And this is not changeable via storageconfig.txt.

**Comment by Thunichgud** [comment]
Indeed ? Google shows in Android 11 a very stupid "modern way" and you follow this "modern way" like a blind child ? 
As you wrote, Android/media is visible and open for other apps - also for BRouter.  So BRouter should make it possible again to read the coords and nogos and to write the tracks to ....Android/media/osmand. Otherwise BRouter will be unusable for me and many other people.

**Comment by zod** [comment]
@Thunichgud Is there any reason you aren't able to use th service interface?

**Comment by Thunichgud** [comment]
@zod: I don't understand your question. Which service interface should I use for what ?

BRouter was a very good app, but since the last answer from afischerdev it is dead for me and I think for many other users too. There is no further development planned and the actual version is unusable. I'm sorry about that.

**Comment by devemux86** [comment]
`Android/media` is already marked as [deprecated](https://developer.android.com/reference/android/content/Context#getExternalMediaDirs()), we do not know its future in next Androids.

App folders in `Android/media` can be accessed only by file managers, like [Total Commander](https://play.google.com/store/apps/details?id=com.ghisler.android.TotalCommander).
Normal apps only have access to their own folders in `Android/media`.

Or is there something different?

**Comment by zod** [comment]
OsmAnd can use BRouter using the service interface as described in https://zod.github.io/brouter/users/android_quickstart.html. Access to other apps private storage is getting more complicated with every new android version so BRouter tries to provide a way which works on any android version and is easy to use. By using the service interface you can avoid switching apps and use BRouter directly from OsmAnd.

I don't really get what you mean with there is no development planned as @afischerdev is working on the app.

**Comment by Thunichgud** [comment]
I've tested the service interface in OSMand.
I did prefer the direct use of BRouter because ...
1. OSMand isn't able to calculate long distance routing - also when I use the service interface of BRouter. I know: It is possible to calculate long distances when I use intermediate points but this is inconvenient. It's a real shame for the navigation app OSMand, that it isn't able to calculate long distance routes.
2. OSMand ignores the nogo areas when I use the service interface of BRouter. The nogo area is a very good feature of BRouter.
3. I have no control, which profile of BRouter OSMand uses. The profiles of BRouter are very good.
and ...
4. I like the graphic of BRouter while calculating the route.

Android 10 and 11 killed many good apps. BRouter is one of them and its developers capitulated against the Android dictate.

afisherdev wrote here on Jan. 9, 2023 that this neccessary development is not planned and closed this issue. BRouter is no longer useable and so it is dead. Sorry !

**Comment by afischerdev** [comment]
@Thunichgud 
Yes, we don't go back, we go forward, currently API 33, Android 13.

But you could do your way as before like this:
- copy your favourites.gpx to the BRouter folder ./Android/media/btools.routingapp/brouter/import
- copy your nogo_*.gpx to .../brouter/import/tracks
- start BRouter
- select a profile and two or more points from the fav selection
- and enjoy the calculation graphics
- at least send gpx from BRouter to OSMAnd

**Comment by vodie** [comment]
@Thunichgud 
1. You can calculate long distance routes with the service interface. If the timeout message appear you can restart the calculation in the BRouter app by selecting the <repeat:xxx> profile where xxx is the used profile. When the calculation is done you can restart the routing request in Osmand and the route is because it is already calculated immediately there. If you know the calculation takes to long you can cancel the calculation in Osmand immediately and switch to the BRouter app.
2. If you want to block certain roads you can set avoid road points in Osmand. They are send as 10 meter nogo areas.
3. You can set the used profile for the service interface by selecting Server-Mode after selecting the routing profile in the BRouter-app and check the mode(s) in Osmand it will be used. In Osmand are six modes possible that can be used by BRouter. They are determined by the base profile in Osmand (foot, bike and any other is car) you select when you make a new profile and the "fastest Route" switch.
4. You can use the <repeat:xxx> profile even if the route is already calculated by the service interface.

**Comment by Thunichgud** [comment]
@afischedev:
For my opinion BRouter will actually not be developed forward. The actual API is no argument, because Android goes since version 10 the wrong way: More and more restrictions. Many good apps don't work with these restrictions - as BRouter. It would be better when you look for workarounds against these restrictions - for a user-friendly software.
The way to use BRouter you described is an example of user-hostile software. This is not the art of software from tomorrow, today or yesterday, it is the art of software from the last century: Start app 1 and enter favorite points and nogo points, close app 1, open app 2 and manually copy files from A to B others from C to D, close app 2, open app 3 and calculate the route, close app 3, again open app 2 and copy files from B to A, close app 2. Now you can open app 1 and use the calculated routes. Horrible !!

@vodie:
1. This way to calculate long distance routes in OSMand is a lame gimp. Absolutely inconvenient.
2. I sometimes need larger nogo areas. When I have to block 15 roads instead of one point it is inconvenient.
3. Inconvenient.
4. Inconvenient.

A very good app has gone to a lame gimp. Sorry again ! The kernel ist still brilliant, but the UI is an absolute disaster.

**Comment by Thunichgud** [comment]
I meant the UI and the service interface.
