### ISSUE TITLE
error caching remote profile

### ISSUE THREAD

**Issue by aakerbeere** [abrensch/brouter#492]
I actually get this when launching routing (android, Permission denied).
Don't know how to solve.
Hints are welcome.

**Comment by afischerdev** [comment]
No idea, sorry.

Any changes in your system? new Android version?

Do you have your BRouter data inside ./Android/media? Or external folder?

**Comment by aakerbeere** [comment]
thx @afischerdev 

9 PKQ1.180904.001. No new Android version actually. Updates to occur permanently, but nothing relating to brouter as i can say so far.
BRouter data inside "/storage/emulated/0/brouter/profiles2/". File to be accessed is "remote.brf" which there is present.

**Comment by afischerdev** [comment]
My recommendation would be to install new with storage path /Android/media/...
Android 9 should not be affected and file access should work as usual - but who knows.

**Comment by aakerbeere** [comment]
Much simpler :)

Storage permissions have been set to deny somehow. BRouter App considered by Android as "never" being used and maybe  therefore storage permissions set to "deny" by OS. Don't know how this happens. I use BRouter very frequent through locus. Setting storage access to "allow" again does it.

thx @afischerdev for comment.

Closing issue as solved.

**Comment by afischerdev** [comment]
@aakerbeere 
Thanks for sharing this solution. Good to know.
