### ISSUE TITLE
Update of the maps is not possible

### ISSUE THREAD

**Issue by macro182** [abrensch/brouter#527]
Hi,
I cannot update the maps (or remove/install others).

When I access to the app, it always shows the 'select a routing profile'.
No way to show the 'maps manager' interface.

Reboot of the phone does not solve.

Thank you

**Comment by afischerdev** [comment]
I had a look at the old sources.
There is a check for being online. If this fails the app starts with profile selection.
Please monitor that environment.

**Comment by macro182** [comment]
I've found out what's wrong.
I use rise-vpn on my phone, disabling it did the trick!

thank you
