### ISSUE TITLE
Gebäude wird nicht angezeigt - Building is not shown

### ISSUE THREAD

**Issue by guegafue** [abrensch/brouter#533]
In OpenStreetmap wird ein Gebäude, das es seit vielen Jahren gibt, nicht angezeigt. Relativ neue Gebäude dagegen schon. In TopPlusOpen wird das Bestandgebäude angezeigt, jedoch die neueren nicht. Liegt das evtl. daran, dass die in OpenStreetMap nicht angezeigten Gebäude mit Building:part erfasst wurden, die angezeigten mit Building=yes?

In OpenStreetmap, a building that has been there for many years is not shown. Relatively new buildings, on the other hand, do. In TopPlusOpen, the existing building is displayed, but the newer ones are not. Is this possibly because the buildings not shown in OpenStreetMap were recorded with Building:part and the ones shown with Building=yes?

![2023-04-17_111548](https://user-images.githubusercontent.com/130976219/232441872-2922c32e-5756-4698-b727-ab3a9911e2cf.jpg)
![2023-04-17_111614](https://user-images.githubusercontent.com/130976219/232441879-20679bcd-9d2f-4a74-8fc9-751f702c073a.jpg)

**Comment by nrenner** [comment]
Not really a brouter question, but still:

Yes, I think the standard OSM layer doesn't render `building:part`. The wiki recommends:

> building:part=* areas should always be within a separate [building](https://wiki.openstreetmap.org/wiki/Key:building)=* area representing the entire building.

https://wiki.openstreetmap.org/wiki/Key:building:part

That `building` outline in [way 277031322](https://www.openstreetmap.org/way/277031322/history#map=19/49.48253/10.94741) was deleted in changeset [133914911 (OSMCha)](https://osmcha.org/changesets/133914911/), including address and other information. So I think that way should be restored.

[TopPlusOpen](https://gdz.bkg.bund.de/index.php/default/wmts-topplusopen-wmts-topplus-open.html) shows an old state as of 12/2022 (see "Aktuelle Änderungen") and is only updated once a year.
