### ISSUE TITLE
update URL of Sonny's LiDAR Digital Terrain Models

### ISSUE THREAD

**Issue by SonnyLidarDTM** [abrensch/brouter#534]
Hi,
please update the URLs of Sonny's LiDAR Digital Terrain Models on both sites https://brouter.de  and  https://brouter.de/brouter/elevation.html to "**https://sonny.4lima.de**",
Thank you!

**Comment by nrenner** [comment]
Ideally, we should not only attribute the compiler, but also the actual data sources used (see also [OSM community discussion](https://community.openstreetmap.org/t/lidar-digital-terrain-models-dtm-of-european-countries/98043)).

**Comment by abrensch** [comment]
Done updating the links.

Completing attribution for underlying lidar data sources should be done in the context of https://github.com/abrensch/brouter/issues/539 (extending lidar usage to all europe)
