### ISSUE TITLE
Roundabouts and Slip-Roads

### ISSUE THREAD

**Issue by MotoUKRider** [abrensch/brouter#545]
Hello - Cruiser user here.

I've just updated to v1.7 and found that a Route didn't load - further investigation reveals it boils down to roundabouts and slip-roads as starting points - replicated in several places on a map using duplicate "preferences" on 2 devices, the other using the previous BRouter from GooglePlay Store.

If you attempt to start from a roundabout (ie: a place where fuel/services may be) then it won't "route". The on/off-ramp/slip-road does not route, either. You have to start the Route on the main carriageway or a little back from the roundabout.

See example below:
It will "route" on the main A15 towards the Humber Bridge, but not on the entry-ramp, so you have to find a "clear" piece of road.
![cruiser-brouter-issue](https://user-images.githubusercontent.com/125696109/235622691-7a45a1b1-ff3b-4f85-be23-fbf5e0146e22.jpg)

**Comment by afischerdev** [comment]
I've tried to get the fail with your description. And used it with this [sample](https://brouter.de/brouter-web/#map=18/53.68787/-0.45524/standard&lonlats=-0.455723,53.687695;-0.449084,53.695384&profile=car-fast) - I always need exact data for producing an error. I have no web server wiht 1.7.0 lib but in offline generation this is the result. 

![a15](https://user-images.githubusercontent.com/23175706/235684952-805cbb69-ece0-4169-88ce-fc7b7dfa7fce.png)

Seems alright for me. It starts on ramp (near your point). Do I miss something?

**Comment by devemux86** [comment]
@MotoUKRider 

Can you export a small route example in the (offline) GPX navigation gpx format?

Then I can check the parameters sent to the BRouter app
and @afischerdev can see what's happening in BRouter.

**Comment by afischerdev** [comment]
@MotoUKRider 
I got that. Anyway on my phone this is Cruiser and BRouter last versions:

![Screenshot_20230502-161410](https://user-images.githubusercontent.com/23175706/235694124-a69a6254-d664-43bc-b20b-d292a2ff30e2.png)

Still not see the problem.

**Comment by devemux86** [comment]
@MotoUKRider @afischerdev 

What routing settings do you use?
- Navigation profile
- Route type
- Avoidance options

So we can see what BRouter profile and extra parameters are called.

**Comment by afischerdev** [comment]
Same as mem just as it comes out of the box. Download tiles are from today as this is not my area.

**Comment by devemux86** [comment]
cc @0709wiwiwi

It should be valid to have a turn instruction at the 1st point (start) of a route.
Mostly it is a simple "straight", but in some cases it can even be a u-turn.

The old format has a different structure.
In the new format we use a limited number of tags, we have to fit everything in them.

**Comment by 0709wiwiwi** [comment]
1. Surely this is sure a rare and rather surprising discovery.
2. The snap to street action causes the start to fall on the roundabout. 
3. Roundabout indication locations are where the oncoming road connects to the roundabout.
4. So if you only start at the roundabout itself, the condition 3 is not present.
5. You start on a "crooked" road and so the indication should be "pass_place".  
(Compare with the first (rtept) waypoint but here it is one that snapped to the nearest road).
6. Where you leave that "crooked" road then, a standard L/R directional indication is expected.

**Comment by devemux86** [comment]
For now I will make Cruiser reader more flexible in the next update,
so it has no problem reading such responses.

- https://github.com/devemux86/cruiser/discussions/150

**Comment by afischerdev** [comment]
@0709wiwiwi 
I also tested the GH router inside Cruiser with our sample above. My result is:
![A15_gh](https://user-images.githubusercontent.com/23175706/235860381-345d4e4a-54b4-445d-9806-b96b893bf109.png)
Shows GH also delivers roundabout logic. When I export this to GPX I get a similar result as you in your gpx file. The start point is inside but no turn instruction.
But this is not a fall back from roundabout to 'normal' turn instruction logic. 
For me it seems to be the conflict between start point vs. voice hint goes to the start point.
And on a fall back I would expect a right on 1. exit and and a left on 2. exit.

When you export this as a kurviger file you have the 'take exit 2' inside at position index 0.

@devemux86 
Yes, we have a different structure now. But the output format changes not the routing logic.
All other export formats accept a turn instruction on the first point.

**Comment by afischerdev** [comment]
Anyway, we have a problem in this example:

The result of the roundabout is RNDB2 for right-hand traffic.
It should be RNLB2 on the left side.

**Comment by 0709wiwiwi** [comment]
Alex, 
Surprising was the modified behavior compared to the Beta.

Presenting a theoretical start on a traffic circle optimally ?
See my example: In practice, you probably won't start there.
Unless you want to drive through that private closure. 

What is important however is that a routing start up is not blocked.

Leaving the sym "pass_place" can't , as this also used as navtrack "marker".
In Locus import, a sym "pass_place" is the only possible routing point reference. 
Cruiser and Locus map see imports containing <type> Via_Shaping also slightly different.
Cruiser can so combine every trkpt <sym>text with a <type>Via or Shaping.
In Cruiser, the trackpoint can contain both a turn and be route ref point thus.
According to Menion, this combination is not technically possible in Locus.
So in Locusmap, by a trkpt sym u-turn, you so will lose the route ref marker.

**Comment by devemux86** [comment]
> For now I will make Cruiser reader more flexible in the next update, so it has no problem reading such responses.
> 
>     - https://github.com/devemux86/cruiser/discussions/150

It works properly in [Cruiser 3.0.19](https://play.google.com/store/apps/details?id=gr.talent.cruiser).

**Comment by quaelnix** [comment]
@devemux86, is there anything left to do, or can we close this?

**Comment by devemux86** [comment]
@quaelnix thanks for asking, I have already updated the reader in Cruiser.

So we can close this issue, as a turn instruction in the first trkpt is valid.
