### ISSUE TITLE
Brouter routing Problem.

### ISSUE THREAD

**Issue by Bernd747** [abrensch/brouter#559]
Hello friends,
I have a problem with the routing engine.
If at a certain point on the map the car wants to drive over a certain a bridge, the routing engine always aborts and chooses another route. The system probably means you can only cross the bridge with a bicycle. But you can definitely drive over this bridge by car.
Here are the details of the bridge in the North of Germany:

Gieselauer Schleuse 54°11'01.6"N 9°26'26.4"E

It would be very nice if someone could solve the problem.
Many thanks for the help.

Best regards
Bernd
![csm_Gieselauschleuse_20007_7a133af2_b090_486a_9954_7a22f468c4b6_c_30ec1fc64b](https://github.com/abrensch/brouter/assets/134950957/ace991be-1837-4bf4-9ddd-12f9f2c2c060)

**Comment by afischerdev** [comment]
This is not a routing problem. The definition of the bridge is `access=no`.
So the router will not pass it. 
When the text is correct and the work on the bridge is finished, a mapper should change the definition.

```
access=no
bridge=movable
bridge:movable=bascule
description=Sperrung der Gieselauschleuse (Info von www.wsa-nord-ostsee-kanal.wsv.de) Datum 17.11.2022 In den Wintermonaten vom 01.11.2022 bis zum 31.03.2023 ist die Gieselauschleuse geschlossen. Diese Zeit wird für Wartungs- und kleinere Instandsetzungsmaßnahmen g
foot=no
highway=unclassified
layer=1
maxweight=12
name=Gieselauschleuse
surface=wood
width=3
wikimedia_commons=File:Oldenbüttel NIK 1193.JPG

```

**Comment by Bernd747** [comment]
Many thanks for the quick response. But the German text says: 
In the winter months from November 1st, 2022 to March 31st, 2023 the Gieselau lock is closed. This time is used for maintenance and minor repairs. 
Today is May 29, 2023 the text is out of date.

I drove over this bridge in my car last week. 
What can I do so that the router takes me back over the bridge?

**Comment by devemux86** [comment]
BRouter has the "Straight line" for connecting routable areas.

**Comment by afischerdev** [comment]
I already send a message to the mapper. So just wait.

**Comment by afischerdev** [comment]
The dataset is changed. May be the update is in the BRouter data the next days - normally daily updates.
