### ISSUE TITLE
right distances, wrong times

### ISSUE THREAD

**Issue by ajay-gh** [abrensch/brouter#564]
A few days ago I have updated the app (under Android 8), and the relevant router files.Next went on a vacation and wanted to use Locu Map and brouter for offline routing. To my surprise any routing I do (here in south-west France) provides valid routes and the correct distances, but the resulting times for the proposed route are 2x longer then one would expect. A few test routes along a 100km long straight stretch of national road (departmental, no villages, no intersections, etc.) always show the same results, the router suggests that it is going to take over 2h to drive down 90km of road (speed limit on such highways). As I am not aware of a way to set (different, odd) speed limits in Locus or in brouter, I have to believe it is a bug.

**Comment by afischerdev** [comment]
I made a test with this [sample on BRouter-Web](http://brouter.de/brouter-web/#map=9/44.5836/4.8270/osm-mapnik-german_style&lonlats=4.887586,44.956959;4.781629,44.137317&profile=car-fast)

![original_brf](https://github.com/abrensch/brouter/assets/23175706/5a240493-f441-4dd7-a846-cb6e582090e9)

It has the expected result.

Locus uses it own profiles. When I use this in BRouter-Web I get the result you are talking about. 

![locus_brf](https://github.com/abrensch/brouter/assets/23175706/902daced-9143-4250-b52f-afa7243441ed)

**Comment by ajay-gh** [comment]
I am sorry, but I am not familiar enough with the profiles in Locus. As far as I can see I can select a profile *walk, car, bike ...) and I can change whether motorways or unpaved are allowed or not, but that is it. No speed parameters. And a quick search in the Locus docs did not help. 
I do understand it's a Locus problem, not a brouter problem. But ... could you still show me where I find the profiles in the Locus directories and a word or two which parameters to edit in order to get the results in your first picture ?
Thanks !!

**Comment by afischerdev** [comment]
I didn't find a profile in folder. Could be intern.

> I do understand it's a Locus problem

Yes, I think so. I've cross checked with the older BRouter version, same wrong result.
