### ISSUE TITLE
brouter-web: OSM data update is broken since 2023-06-04

### ISSUE THREAD

**Issue by Zyolix** [abrensch/brouter#571]
brouter-web doesn't reflect OSM changes anymore. The nightly data update from OSM seems to be broken. The files at brouter.de/brouter/segments4/ persistently show a timestamp of 04-Jun-2023.

**Comment by abrensch** [comment]
thanx, I will check later this day. Currently there's some friction cause we are mooving to new server infrastructure.

**Comment by tensleepslav25** [comment]
Any update on this?

**Comment by abrensch** [comment]
Closing this issue since processing seems stable now.  brouter.de domain now pointing to the new (dedicated) server.
