### ISSUE TITLE
"Expecting waypoint selection" when selecting profile

### ISSUE THREAD

**Issue by Fabian42** [abrensch/brouter#576]
When I select any profile, I get "`Expecting waypoint selection
(coordinate-source: /storage/F639-0906/Android/media/btools.routingapp/brouter/import)`". This looks like an error message, but I'm not sure. It's definitely confusing.
![image](https://github.com/abrensch/brouter/assets/10481506/23216fc6-e51c-42ce-b636-2f52ba0824a7)
Clicking "Server mode" lets me select modes and seems to succeed. Clicking the (cut off?) "Select from" leads to something that is definitely an error message ("`coordinate source does not contain any waypoints!`"):
![image](https://github.com/abrensch/brouter/assets/10481506/145a7bd9-2fa4-421e-b1b9-d33e2dbf9013)

**Comment by afischerdev** [comment]
Yes, the first message tells you where you can place a `favourites.gpx` to do some routing around the point you have in there.
This prevents the second message and shows you a list of the points found.

**Comment by Fabian42** [comment]
Why should that be needed for selecting a profile? Those are totally separate actions. I select my destinations in another app.
The text of the right button is definitely wrong then. And the left one may be too, what server?
When I click "server mode", is it supposed to be set up correctly? When I try to use it in OsmAnd, I get this error:
![Screenshot_20230707-195337_OsmAnd_1](https://github.com/abrensch/brouter/assets/10481506/19301fe1-1639-4adf-8379-ca419ce05d30)
And no, I'm not trying to do trekking, everything is set to "fast bike".

**Comment by afischerdev** [comment]
> Why should that be needed for selecting a profile? 

That is not needed. You have already done that when you see the message.

> I select my destinations in another app.

Yes, so you don't need, but your are not the only user.

Please understand BRouter as a tool for setup your routing. When ready you will not see it for a while and only for tiles download. So we don't invest much time for usability. There are enough other things to do.

The error message from BRouter is new and fixed with #581. Meanwhile you could download all tiles to get a correct lookups.dat

**Comment by Fabian42** [comment]
> Yes, so you don't need, but you are not the only user.
Isn't that the only way to use it? I can't do navigation in BRouter.

How do I download all tiles? There's no button for that (although it would be nice to have one). I'm currently running `wget -r -np -R "index.html" -e robots=off -o log http://brouter.de/brouter/segments4/`, in case you meant that, but it's very slow, ~200kB/s.

**Comment by afischerdev** [comment]
> download all tiles

That was not a correct description, I mean update all tiles.

When you have copied your tiles via USB, you could remove lookups.dat and rename lookups.dat.tmp to it. This will solve the parser error message.

**Comment by Fabian42** [comment]
I had just uninstalled the app to try the beta from [here](https://github.com/abrensch/brouter/actions/runs/5487486607) (installation fails), so I downloaded two tiles again and did that deletion/rename, now it works.

Since this is basically a sub-issue of #346 , I'll close this issue now.

**Comment by afischerdev** [comment]
> beta from [here] (installation fails),

It is not merged, so the signature is not correct. Only when merged this will work.
