### ISSUE TITLE
[New Profile] Long Distance Trekking

### ISSUE THREAD

**Issue by fm-sys** [abrensch/brouter#577]
Hello, 

I somehow feel like the brouter trekking profile is "too bike friendly". When using the `ignore_cycleroutes` flag it gets a bit better, but I'm still not confident with the results.

I tried the `fastbike-lowtraffic` - quite nice - however it doesn't seem to use the bicycle infrastructure at all.

Therefore I wrote a `trekking-fast.brf` profile. I would be interested to get some feedback for fine-tuning. Maybe we could even add the profile to the brouter default profiles?

https://github.com/fm-sys/brouter-profiles

Edit: Changed the name to `Trekking-longdistance.brf`

Core changes:
- higher turn cost (avoid zigzag shortcuts through residential areas) 
- penalize unpaved tracks while being more tolerant with larger roads
- make cost factor depending on speed limit
    - primary roads with speed limit <50 get penalized less than primary roads outside built-up areas

**Comment by poutnikl** [comment]
There may be profile name clashing with my trekking-fast profile, see https://github.com/poutnikl/Brouter-profiles/BikeProfiles

**Comment by quaelnix** [comment]
> I would be interested to get some feedback for fine-tuning.

At least for my taste way too much `highway=secondary` and `highway=tertiary`, but to each their own.

**Comment by poutnikl** [comment]
Usage tip: As I have done for long distance variants of my trekking profiles (probably in dev branch of the template), I suggest fine tuning of the bikepower value to match BRouter ETA with real travel time for a known route (possibly involving various physiological, cultural or technical breaks). I use 85 W for long distance loaded bike, but each has his own ideal value.

**Comment by fm-sys** [comment]
> > I would be interested to get some feedback for fine-tuning.
> 
> At least for my taste way too much `highway=secondary` and `highway=tertiary`, but to each their own.

Yes, everyone has different preferences. The profile is more optimized for driving many kilometers in a short time, not for finding the nicest route for a multi day trip. Actually more like a fastbike profile, but still preferring bike infrastructure. Accepting unpaved paths, but not preferring them as much as a gravel profile.

I will try the ETA tip, thanks for the suggestion!

---


And meanwhile I feel we shouldn't add any more user created profiles to brouter. 5 different cyclists, 10 profiles ;-)

Let's just hope we get persisted profiles for brouter web one day... (https://github.com/nrenner/brouter-web/issues/127)
