### ISSUE TITLE
Unknown lookup name: estimated_noise_class

### ISSUE THREAD

**Issue by devemux86** [abrensch/brouter#580]
New BRouter installation: route calculations with fastbike or trekking or hiking-mountain profiles fail with the following exceptions.

It seems BRouter downloads profiles that already have the new rules not compatible with the database?

`ParseException /storage/emulated/0/Android/media/btools.routingapp/brouter/profiles2/fastbike.brf at line 198: unknown lookup name: estimated_noise_class`

`ParseException /storage/emulated/0/Android/media/btools.routingapp/brouter/profiles2/trekking.brf at line 193: unknown lookup name: estimated_noise_class`

`ParseException /storage/emulated/0/Android/media/btools.routingapp/brouter/profiles2/hiking-mountain.brf at line 323: unknown lookup name: estimated_noise_class`

**Comment by afischerdev** [comment]
@devemux86 
Did you have a look at the lookups.dat version number? It should be 10.14
When you update your rd5 tiles the first step is downloading a new lookups.dat and/or standard profiles.

**Comment by devemux86** [comment]
>  Did you have a look at the lookups.dat version number? It should be 10.14

I see (new installation):
```
---lookupversion:10
---minorversion:13
```

**Comment by afischerdev** [comment]
@devemux86 
Yes, at a new installation you get the lookups.dat from apk assets.
But when you load your first rd5 tile, you should get an update on the lookups.

**Comment by devemux86** [comment]
After the new installation of BRouter there were not any rd5 files.
So I downloaded a rd5 tile, but the lookups.dat has not changed.

**Comment by afischerdev** [comment]
Hm, you are right. When I test this now, new lookups.dat become only a lookups.dat.tmp file
I got my version 10.14 last week on all my phones. So I thought everything is fine.

**Comment by devemux86** [comment]
> When I test this now, new lookups.dat become only a lookups.dat.tmp file

@afischerdev indeed, I have a lookups.dat.tmp file with version 10.14 and the new content.
