### ISSUE TITLE
How to handle backward incompatible change to voice hint indexing?

### ISSUE THREAD

**Issue by rkflx** [abrensch/brouter#584]
c9ae7c8681 changed indexing of voice hints, e.g. it now has `TRU = 12; // Right U-turn` which was `OFFR = 12; // Off route` before, breaking everyone depending on those ids (see also nrenner/brouter-web#751).

As far as I can see those changes have not been approved in a review, neither is there any discussion in the commit message on why those changes are needed, nor any mention in the release notes or even tests to catch such regressions. This way it is hard to know what the original motivation for that re-indexing was.

Since the breakage already shipped in 1.7.0, there are now two options:

1. Revert the re-indexing and append new ids only at the end.

- This will restore backward compatibility somewhat, but there would still be a regression (i.e. an unknown hint) in old clients for `TLU`, which probably was emitted as `TU` or something else before.

- It will also require clients which already incorporated the changes to yet again adapt their code, possibly having to support pre-1.7.0, 1.7.0 and post-1.7.0.

2. Keep the changes as-is.

- This will require clients which did not yet adapt to be changed, which might be an issue for unmaintained projects.

- It might require clients to support two different indexing schemes in parallel, i.e. pre-1.7.0 and 1.7.0.

Do we know which projects are already aware of this or still need to adapt? There is BRouter-Web, fit-route, OsmAnd, Locus, QMapShack and probably many more...

Which option should we implement?

**Comment by afischerdev** [comment]
>  changes have not been approved in a review, neither is there any discussion

Yes, this was part of a larger PR #441, we splitted into smaller peaces. Please see for discussion:
> Changes on turn instruction are mainly discussed in https://github.com/abrensch/brouter/issues/375.
> The main discussion for the lib 1.6.4 is found in https://github.com/abrensch/brouter/pull/441.

Locus, Cuiser was part of the discussion

Output PR is found here #510

OsmAnd was present there. 
The output of the lib/apk is still conform to older versions like OsmAnd, Orux, Gpsies.  
Only json or comment-style export using clients need an update.

**Comment by devemux86** [comment]
[Cruiser](https://github.com/devemux86/cruiser) with BRouter version:
- before 1.7 used the timode 3 (osmand-style) that has turn strings (not turn ids).
- after 1.7 uses the timode 2 (new locus-style) with the new offline gpx navigation track also having turn strings.

**Comment by afischerdev** [comment]
> If you could provide a link to the specific comment where re-indexing was discussed, I would appreciate it.

No, I couldn't. May be there was none.
Anyway `append new ids only at the end` will not do the job in this case. There are different arrays with ids (or shortcuts) and when the first new id comes out the routing it will break.

Means for me you should change to the new ones or do a wrapper around.

**Comment by afischerdev** [comment]
What I see is the function in [Voicehint.js](https://github.com/nrenner/brouter-web/blob/b64b3c6910655663d105c5a960188cdf5e167e08/js/format/VoiceHints.js#L116)
I don't know javascript that much, but I think you have to add two lines to become conform with [VoiceHint.java](https://github.com/abrensch/brouter/blob/993a3aa85987553434b8fe7be5c650f04a2b05bc/brouter-core/src/main/java/btools/router/VoiceHint.java#L22), or something similar 

```
            10: new Command('TLU', 13, 1003, 'TU', 'u-turn', 'u-turn'), // Left U-turn
            11: new Command('TU', 13, 1003, 'TU', 'u_turn', 'u-turn'), // 180 degree U-turn
            12: new Command('TRU', 14, 1003, 'TU', 'u_turn', 'u-turn'), // Right U-turn
            13: new Command('OFFR', undefined, undefined, undefined, 'danger', undefined), // Off route
            14: new Command('RNDB', 26, 1008, 'RNDB', 'generic', 'Take exit '), // Roundabout
            15: new Command('RNLB', 26, 1008, 'RNLB', 'generic', 'Take exit '), // Roundabout left
            16: new Command('BL', undefined, undefined, undefined, 'beeline', undefined),  // beeline
```
Anyway when you dealing with own gpx export you also have add a new Locus export (voicehints on trkpt)

**Comment by afischerdev** [comment]
Ok, lets go it your way, step by step:

The task is **add a 180 degree u-turn**

We have this ids. If you don't mind I ignore beeline for a moment, it is not relevant here.
What we had in the past:
```
 10: TU
 11: TRU
 12: OFFR
 13: RNDB
 14: RNLB
```    
This brings as output of your little [sample](https://brouter.de/brouter-web/#map=19/52.55228/13.45100/standard&lonlats=13.450806,52.552211;13.450911,52.552334) the voicehints:
```
forward 10 - TU
reverse 11 - TRU
```

Now you want to add a new line in the back - I hope I understand it the right way:
```
 10: TU
 11: TRU
 12: OFFR
 13: RNDB
 14: RNLB
 15: TLU
```    
But, ups, the challenge was to add a **180degree U-turn** and not a **Left U-turn**.
And our output now looks like:
```
forward 15 - TLU
reverse 11 - TRU
```
Shouldn't it be **10 - TLU**? To get that we need a this list 
```
 10: TLU
 11: TRU
 12: OFFR
 13: RNDB
 14: RNLB
 15: TU
```   
Now we have a perfect output and added a 180degree u-turn at the end.
But we got changes in the old running team.

Every path ends in a mess. The problem is: in the past the number 10: TU wasn't a **180degree u-turn** it always was a **left u-turn**

That's why I still think it is the better way to make a break and keep the u-turns together. It beautifies your code and makes it more readable / understandable for other people.

And I understand you problem. You are using hard coded ids - e.g for RNDB, RNLB. I don't know if this is the way Javascript needs. In Java I can use constants which makes changes easier.

**Comment by quaelnix** [comment]
Could someone please explain me why we need three different types of u turns?

**Comment by quaelnix** [comment]
Ok thanks, here is the answer to my question: https://github.com/abrensch/brouter/issues/436#issuecomment-1159795615

**Comment by afischerdev** [comment]
Alright, I give up. I jumped too short and in the wrong direction.
But I would have liked a correction a little earlier.

I would prefer option one. A little overhead, but smart.

If no one else has another vote, you could start a PR.

**Comment by quaelnix** [comment]
Is it really too late to go back and do it as described in the "What you should have done ..." section?

**Comment by afischerdev** [comment]
No, I think it is no to late.
As this issue shows no other has a problem with the new version. Or they are all sleeping.
The rewind could go this way:
```
 10: TU
 11: TRU
 12: OFFR
 13: RNDB
 14: RNLB
 15: T180
```

**Comment by devemux86** [comment]
> 15: T180

This will break compatibility in apps using BRouter 1.7.X with the already published `TLU` tag.

At least we should keep the current strings.

**Comment by afischerdev** [comment]
@devemux86 
This are the input values and should not affect the current output.
Only json export will get other output values and comment-style may be other labels.

**Comment by devemux86** [comment]
@afischerdev
The turn strings like the "TLU" are used in the timode=3 answer, so it affects the output.

Cruiser already uses the new timode=2, so it is not affected.

But maybe other apps using timode=3 will have a problem?

**Comment by afischerdev** [comment]
@devemux86 
I'm not sure how OsmAnd ir running. The [issue](https://github.com/osmandapp/OsmAnd/issues/16253) is still open and the [voicehint turntype](https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd-java/src/main/java/net/osmand/router/TurnType.java) are the old one. I think I already have mapped it to get the old export, and only the 'getCruiserCommandString' function has the new output.

**Comment by quaelnix** [comment]
> This will break compatibility in apps using BRouter 1.7.X with the already published TLU tag.

Yes, but these are the unproblematic applications that are well maintained. If we announce the rollback properly, it should go pretty smoothly. And the many not well maintained apps (which did not add support for the new logic yet) would no longer need to be changed at all. But I also agree with all the solutions proposed by @rkflx. I'm just thinking out loud.

**Comment by afischerdev** [comment]
@rkflx 
> I'll prepare a PR in the next days, so we will be able to make an informed decision on how to go forward with this.

Maybe wait a little longer, perhaps there will be more opinions on these changes

I see three options:
- stay with id export on json, re-index and offer ids as [above](https://github.com/abrensch/brouter/issues/584#issuecomment-1635407445)
- switch to 'named' export on json, do not re-index
- switch to 'named' export on json and use the new Command class offered here [BRouter](https://github.com/abrensch/brouter/compare/master...rkflx:brouter:PR/use-strings-and-enums-for-voicehints)

**Comment by afischerdev** [comment]
@quaelnix 
> And the many not well maintained apps (which did not add support for the new logic yet) would no longer need to be changed at all. 

What are the not well maintained apps that are using json export? 
And I'm not sure about `no longer need to be changed at all`. When new re-indexed BRouter deliver `T180` or `BL` they are unprepared and in the best way they return nothing.

All options above should only affect the json export, all other candidates should remain as before.

**Comment by quaelnix** [comment]
> What are the not well maintained apps that are using json export?

I don't know, but I guess the "don't know" part is the whole reason why full backwards compatibility is desirable?

**Comment by afischerdev** [comment]
> See #591 for PR reverting the reindexing, with optional cleanup.

I've seen, please let me do some tests.
As additional test I use [this](https://brouter.de/brouter-web/#map=18/52.55221/13.45073/standard&lonlats=13.450806,52.552211;13.451549,52.55283;13.451471,52.552213;13.451675,52.55221&profile=hiking-mountain).
