### ISSUE TITLE
Heading, give route a start direction

### ISSUE THREAD

**Issue by devemux86** [abrensch/brouter#589]
[IBRouterService.aidl](https://github.com/abrensch/brouter/blob/master/brouter-routing-app/src/main/aidl/btools/routingapp/IBRouterService.aidl) mentions the heading parameter to give routes a start direction.

However it does not seem to work. For example this [simple route](https://brouter.de/brouter-web/#map=16/42.5319/1.5474/standard&lonlats=1.546154,42.529064;1.546004,42.534172&profile=car-fast) on a 2-way street.

When we pass via the Android service the `heading=160` (i.e. south),
BRouter keeps returning the same route going north to the destination.

Other routers calculate the route correctly, i.e. first going south.
The routing heading direction must be enforced. Is it possible?

_Originally reported in https://github.com/devemux86/cruiser/discussions/175#discussioncomment-6406441._

**Comment by abrensch** [comment]
The heading does not really enforce the start-direction, just penalizes the wrong direction.

For the Standard-Model (=bike profiles) that should be twice the "turncost" for 180 deg.

For the Kinematic model (=car) it's added as an extraTme, hardcoded 40 seconds for 180 degree (see https://github.com/abrensch/brouter/blob/master/brouter-core/src/main/java/btools/router/KinematicPath.java )

But in your example the extra cost of going forward is much higher than this 40 seconds.

Please also note that the AIDL-interface has two params, the original one ("direction") made for Locus Maps is only applied for "fast recalculations" because Locus delivers the param also when not mooving and then it's just noise.

The "heading" parameter does the same as "direction" but is always applied.

**Comment by devemux86** [comment]
@abrensch thanks for the explanation.

I already use the "heading" parameter, but the results are not correct.
So users keep complaining that BRouter calculates backward routes.

> But in your example the extra cost of going forward is much higher than this 40 seconds.

This is a small example. If you check the reported route above in the first post,
start is 14.8 km / 19 min away from first waypoint, but heading is not respected.

In the example heading=160, we cannot expect  cars to make u-turn or go backwards, must go south.
All other routers that support heading (GraphHopper, OpenRouteService, Valhalla, etc) work correctly.

We need to think about real road conditions (motor vehicles move forward), not just  graph mathematics.

A better solution could be a new parameter "forcedHeading" that does what drivers expect on the road?
Existing parameters can continue to work as they are now for compatibility.

**Comment by abrensch** [comment]
I just do not believe that solutions according to "go forward for now and u-turn a bit further ahead where the OSM network allows it." are correct in the majority of cases.

This is because the OSM network is not correct in this respect.

Another related problem is the lane-matching: sometimes I get a backward solution though my 40 seconds would be enough to favour the forward solution. This can happen because the re-routing catched the backward-lane in waypoint matching  due to GPS jitter.

So yes I agree we are far from poviding "the most intuitive" soluion.

But no, I don't believe that GraphHopper and friends provide the "correct" solution.

**Comment by abrensch** [comment]
>> This is because the OSM network is not correct in this respect.

It's possible o show examples for bad u-tun solutions by triggering them via turn-restrictions:

http://brouter.de/brouter-web/#map=15/50.4627/8.0643/osm-mapnik-german_style&lonlats=8.057876,50.464222;8.057715,50.464771&profile=car-fast

http://brouter.de/brouter-web/#map=14/50.4081/7.7818/osm-mapnik-german_style&lonlats=7.802141,50.419268;7.802246,50.41921&profile=car-fast

**Comment by devemux86** [comment]
We seem to mean different things. :slightly_smiling_face: 

In real life driving, users expect the routes to always guide them to drive forward (regardless the route length).

The above example (with help of a no-go area to force heading 160 south) becomes like this [expected route](https://brouter.de/brouter-web/#map=15/42.5318/1.5492/standard&lonlats=1.546154,42.529064;1.546004,42.534172&nogos=1.545821,42.529354,19&profile=car-fast).

A much longer route, but it is the expected result in real life vehicle navigation.

**Comment by abrensch** [comment]
>> A much longer route, but it is the expected result in real life vehicle navigation.

For cruiser to outperform G-maps in market share, it should be a bit more economical in terms of mileage :-)

BTW, my (G**gle-based) car navi suggests strange forward solutions u-turning by an extra lap in someones backyard. Quite annoying.

**Comment by afischerdev** [comment]
We have at the moment penalty only in car profiles (via KinematicPath).
I would like to see that for bike and foot as well.
My favorite routing app should recalculate this [example routing suggestion](https://brouter.de/brouter-web/#map=17/50.00120/8.71633/standard&lonlats=8.715441,50.002016;8.718209,50.001774&profile=hiking-mountain)  if I prefer to walk along the lake.
The problem I see is the routing restarts to target. What when we use via points? It this still a valid point at re-routing? [Sample](https://brouter.de/brouter-web/#map=17/50.00120/8.71633/standard&lonlats=8.715441,50.002016;8.718209,50.001774&profile=hiking-mountain)

**Comment by devemux86** [comment]
> It this still a valid point at re-routing?

At re-routing the heading is much more important, as users are already using their devices to navigate.
They cannot stop (eg drive) to correct the wrong routing that sends them backwards.

**Comment by afischerdev** [comment]
Yes, I think so. 
But what to do with the via point - drop it or use it? There is no intuitive answer.

**Comment by devemux86** [comment]
> But what to do with the via point - drop it or use it?

What do you mean?

Do you mean to place a via point above the lake? This could work in manual route planning. [Example](https://brouter.de/brouter-web/#map=17/50.00120/8.71633/standard&lonlats=8.715441,50.002016;8.717297,50.002767;8.718209,50.001774&profile=hiking-mountain)

But adding automatically a via point in front of start to force a forward routing is not enough. [Example](https://brouter.de/brouter-web/#map=17/50.00120/8.71633/standard&lonlats=8.715441,50.002016;8.715731,50.002215;8.718209,50.001774&profile=hiking-mountain)

Extra via points to influence the routing heading can only work in manual route planning, where we can adjust the routes.
Not in re-routing during a running navigation where users drive and do not plan routes.

**Comment by afischerdev** [comment]
I mean my second [sample](https://brouter.de/brouter-web/#map=17/50.00120/8.71633/standard&lonlats=8.715441,50.002016;8.716922,50.001457;8.718209,50.001774&profile=hiking-mountain), but I see it hasn't a via point, sorry. But when it is a little off the route after re-routing - may be in this small case 'correctMisplacedViaPoints' will do the job, but not always.

**Comment by devemux86** [comment]
@afischerdev I do not clearly understand what you mean?

The "forced" heading is required for the start point of re-routing, where user is when navigating.

Other routers also offer heading in the via points, but we should start with the basic requirement.

**Comment by afischerdev** [comment]
@devemux86 
Yes, agree, a heading is needed. 
But re-routing would ends in this [result](https://brouter.de/brouter-web/#map=17/50.00120/8.71633/standard&lonlats=8.715634,50.002216;8.716922,50.001457;8.718209,50.001774&profile=hiking-mountain). An now the via point is misplaced.

**Comment by devemux86** [comment]
If the route can be forced forward, then we do not seem to need the extra via point. [Example](https://brouter.de/brouter-web/#map=17/50.00120/8.71633/standard&lonlats=8.715634,50.002216;8.718209,50.001774&profile=hiking-mountain)

**Comment by afischerdev** [comment]
The via point was there before re-routing.

**Comment by devemux86** [comment]
> The via point was there before re-routing.

@afischerdev Thanks, now I understand.

But the via points are not relevant with the start heading. They could be near, they could be far away.

**Comment by afischerdev** [comment]
So far I haven't found a satisfactory result.
But I have an other idea:
The use of a nogo point has already been discussed. But this will become a [breaking situation](http://brouter.de/brouter-web/#map=15/63.3844/10.3709/standard&lonlats=10.364699,63.382947;10.372295,63.383794&nogos=10.364029,63.383186,27&profile=car-eco) when user enters a dead end situation.
To avoid this, a weighted NoGo point can be used. Replace `&nogos=10.364029,63.383186,27` with `&nogos=10.364029,63.383186,27,10000` then an exit will be found.
This also work with the [first sample](https://brouter.de/brouter-web/#map=14/42.5363/1.5499/standard&lonlats=1.546154,42.529064;1.546004,42.534172&nogos=1.546026,42.530313,30,10000&profile=car-fast).

At the end we have the same situation as before, user hear the 'please u-turn'. But is has a stronger meaning then 'only' bring user back to old route. May be user needs a better advise and a new turntype 'deadend u-turn' is born.

**Comment by devemux86** [comment]
@afischerdev thanks for looking into this!

It's unfortunate that it can't be solved inside the router, even with a weighted solution.

In any case, your advice with the weighted NoGo is important, thanks!
It is always better to avoid failed route calculations on the user side.

**Comment by devemux86** [comment]
I implemented the routing heading with the no-go area in [Cruiser 3.0.30](https://github.com/devemux86/cruiser):
- https://github.com/devemux86/cruiser/discussions/191

**Comment by afischerdev** [comment]
@devemux86 
Thanks for let us know about the new feature.
