### ISSUE TITLE
"indoor" to lookups.dat

### ISSUE THREAD

**Issue by Erelen-Laiquendi** [abrensch/brouter#59]
Please, add "indoor" key to lookups.dat (and to data :)
https://wiki.openstreetmap.org/wiki/Key:indoor

Reason: ability to don't use "highway=footway indoor=yes" for bicycle routes.

**Comment by zossebart** [comment]
+1

I also think this would be a necessary enhancement, see for example

[http://brouter.de/brouter-web/#zoom=17&lat=51.347679&lon=12.47447&layer=OpenStreetMap&lonlats=12.473624,51.347897|12.478924,51.348963&nogos=&profile=trekking&alternativeidx=0&format=geojson](http://brouter.de/brouter-web/#zoom=17&lat=51.347679&lon=12.47447&layer=OpenStreetMap&lonlats=12.473624,51.347897|12.478924,51.348963&nogos=&profile=trekking&alternativeidx=0&format=geojson)

, where the trekking profile routes straight through the (indoor) shoppingcentre.

**Comment by abrensch** [comment]
done for 1.4.9
