### ISSUE TITLE
NullPointerException thow in VoiceHintProcessor class

### ISSUE THREAD

**Issue by oruxmanpower** [abrensch/brouter#603]
With some frequently used .rd5 segment files in Korea, a NullPointerException is thrown at this point in the code:

https://github.com/abrensch/brouter/blob/master/brouter-core/src/main/java/btools/router/VoiceHintProcessor.java#L253

In other parts of the code the VoiceHint.badWays property is checked for nullity but at that point in the code it is not checked.

I don't know if at that point it should never be null, but the reality is that sometimes, with the aforementioned segment files, a NullPointerException is thrown.

**Comment by afischerdev** [comment]
Thanks for the pointer.
We also have some errors collected by the Play Store. 
An update soon would be appropriate.
