### ISSUE TITLE
No "Share gpx" button

### ISSUE THREAD

**Issue by Stapawe** [abrensch/brouter#607]
In https://github.com/abrensch/brouter/issues/429#issuecomment-1212728409 from a year ago there is a screen recording, in Locus Classic, of calculating of alternatives from BRouter master branch.
I recently updated BRouter from 1.6.1 api10 to 1.7.2 and BRouter displays only "Exit" button and there is no "Info" and "Share GPX" buttons visible in the 7th second of the recording. I don't know whether it is intentional, but after finding a folder with tracks, I can live with this, especially when Locus Classic is a niche now.

**Comment by afischerdev** [comment]
When I use the recalc offer from <repeat:remote> I get this box:

![share](https://github.com/abrensch/brouter/assets/23175706/694ecaa9-1926-4e33-9937-25ca233e6a8c)

It seems to me that everything you wanted is in there.
Or do you have something else?

**Comment by Stapawe** [comment]
:) It seems I was so persuaded by the recording that I didn't even read it. Sorry for the confusion, but I propose using conventional borders to distinguish ordinary text from buttons. Thanks for your work.
