### ISSUE TITLE
Rework on voicehint process

### ISSUE THREAD

**Issue by afischerdev** [abrensch/brouter#613]
It seems the post process for voicehint generation needs a rework.
Please see [doc for voicehint](https://github.com/abrensch/brouter/blob/8d123e337516664f1bbd05c0802aab30ec698726/docs/features/voicehints.md?plain=1#L21) for the current rules.

Related to this [discussion](https://github.com/devemux86/cruiser/discussions/164#discussioncomment-6738015) in Cruiser forum we have some smaller irritation for the users (I hope I got it correct):

| Sample | Result | Expected Result |
| :--- | :--- | :--- |
| [1. sample](https://brouter.de/brouter-web/#map=18/52.23631/21.08689/standard&lonlats=21.084926,52.235957;21.086953,52.236789&profile=car-eco) | left, continue | left |
| [2. sample](https://brouter.de/brouter-web/#map=18/52.23665/21.08697/standard&lonlats=21.086803,52.23691;21.087645,52.236062&profile=car-eco) | continue, left | left |
| 1. sample with [trekking](https://brouter.de/brouter-web/#map=18/52.23631/21.08689/standard&lonlats=21.084926,52.235957;21.086953,52.236789) | continue, left, continue, continue | left |
| [3. sample u-turn](https://brouter.de/brouter-web/#map=18/52.23622/21.08662/standard&lonlats=21.086803,52.23691;21.086959,52.236654&profile=car-eco) | continue, u-turn-left, continue | u-turn-left |
| [4. sample u-turn](https://brouter.de/brouter-web/#map=18/52.23622/21.08662/standard&lonlats=21.087704,52.23622;21.087656,52.236056&profile=car-eco) | u-turn-left | u-turn-left |

The rule `keep continue when bad way is on higher prio` is working fine. But it has its side effects.

Are there any other examples that should be revised as well?

**Comment by afischerdev** [comment]
An other point for this rework is the handling of two near turn instructions left/right.
Here two examples
[5 meter difference](http://brouter.de/brouter-web/#map=18/49.97455/8.56916/osm-mapnik-german_style&lonlats=8.567633,49.974327;8.569221,49.974934&profile=car-eco) - result for all straight
[7 meter distance](http://brouter.de/brouter-web/#map=19/51.06202/3.94846/standard&lonlats=3.945481,51.062231;3.948759,51.063007) - result for trekking right/left, for car straight

The different results come from the [minimal distance](https://github.com/abrensch/brouter/blob/8d123e337516664f1bbd05c0802aab30ec698726/brouter-core/src/main/java/btools/router/OsmTrack.java#L1385) table:
foot = 3m - with a speed of 5 km/h we have 1,4 m/s = 7 meter cost 5 seconds
bike = 5 m - speed 10 km/h - 2,8 m/s = 2.5 seconds
car = 20 m - speed 30 km/h - 8,3 m/s = 0.8 seconds
I don't know how long a sentence like 'turn left and follow for 7 meter' will take in audio but I guess on a car driving you will not hear very much.

**Comment by 0709wiwiwi** [comment]
> I don't know how long a sentence like 'turn left and follow for 7 meter' will take in audio but I guess on a car driving you will not hear very much.

The last announcement before turns should be very short and clear.
Example:
- TTS by small distance: **After 30 meters turn left**   	(TTS)
- TTS last announcement: After 10 meters turn **left**     (TTS)   As compact as possible !
- TTS by small distance: **After 30 meters track at 9 o’ clock**   	(TTS)
- TTS last announcement: After 10 meters **[Beeline_clock_sym_guiding.docx](https://github.com/abrensch/brouter/files/12439224/Beeline_clock_sym_guiding.docx)** o’ clock	(TTS)   As compact as possible !
Alternatively the last announcement as a loud and clear compact Morse beep “T” - “dash”

**Comment by afischerdev** [comment]
Two new samples from #625:
1. turn instruction left with [starting straight](https://brouter.de/brouter-web/#map=17/50.91122/6.94500/standard&lonlats=6.94334,50.910697;6.945859,50.912178&profile=car-eco)
2. missing turn instruction [sample](https://brouter.de/brouter-web/#map=18/52.22817/21.08547/standard&lonlats=21.085237,52.22843;21.086476,52.22807&profile=car-eco)

**Comment by afischerdev** [comment]
During my research for this issue I found further inconsistencies - like the number 2 above.
Some hints are dropped like this [right instruction](http://brouter.de/brouter-web/#map=18/49.87262/8.65051/standard&lonlats=8.647042,49.872198;8.650972,49.872091)
This means to me it is not only a postprocess problem.

**Comment by afischerdev** [comment]
1. sample 2 above:
   in my eyes the exclusion of this voicehint is done in [VoicehintProcessor](https://github.com/abrensch/brouter/blob/90fbe8345a5c16fc2857b08e922a20b62974c230/brouter-core/src/main/java/btools/router/VoiceHintProcessor.java#L160).

`boolean hasSomethingMoreStraight = (Math.abs(turnAngle) - minAbsAngeRaw) > 20.;
`
The angles are `turnAngle= -88` `minAbsAngeRaw= 180`, so the result is -92

I didn't use a correction on this for now - just to keep the results comparable. But I used a new logic in post process.
In the past we had a collection of nearby voicehints, now I tried a comparing of two voicehints a time. This brings better results and make lost voichints visible.
Here a the results of differents on this [track](http://brouter.de/brouter-web/#map=16/49.8725/8.6485/standard&lonlats=8.646215,49.87207;8.693455,49.40987) current logic against new one.

left = old 

![track_diff_11](https://github.com/abrensch/brouter/assets/23175706/8f218eab-d4dd-4f84-82ce-a91dbd685a61)

![track_diff_19](https://github.com/abrensch/brouter/assets/23175706/4f36a5c7-e51d-4373-aefe-ca9a982efb8d)

![track_diff_397](https://github.com/abrensch/brouter/assets/23175706/d543c5fd-6b58-4e46-91e5-750152d6bcae)

![track_diff_480](https://github.com/abrensch/brouter/assets/23175706/ea976ba4-8b2d-4a82-8773-4a84f510691a)

![track_diff_518](https://github.com/abrensch/brouter/assets/23175706/29055c11-f096-4d81-935b-43e8b862db77)

The source is located in my [repo](https://github.com/afischerdev/brouter/tree/rework-voicehint)

Before I go on with the 'left' problem and the exclusion of the straight voicehints in nearby situation, I like to hear what you are thinking about. Is this a way it could go?

**Comment by afischerdev** [comment]
@devemux86 
Please hang on a minute. I'll continue here in a few days.

**Comment by devemux86** [comment]
@afischerdev 

A Beta version of Cruiser is available where I post process the turn instructions to fix the nearby "continue":
- https://github.com/devemux86/cruiser/discussions/390#discussioncomment-7801924

**Comment by devemux86** [comment]
More examples of a route missing a "turn left" instruction were reported:
- https://github.com/devemux86/cruiser/discussions/307#discussioncomment-7802822

**Comment by devemux86** [comment]
More examples of a route missing a "turn left" instruction were reported:
- https://github.com/devemux86/cruiser/discussions/307#discussioncomment-7803155

**Comment by afischerdev** [comment]
Next version for voice hints

The first step was to start a new transportMode - announced here #544
But this changes only the internal use, no changes in profile at the moment

To remenber the old [rules from doc](https://github.com/abrensch/brouter/blob/bcf6a7f630257d7ae8012b00c49024663507a1ce/docs/features/voicehints.md?plain=1#L21)

* show 'continue' only if the way crosses a higher priority way
* roundabouts have an exit marker
* u-turn between -179 and +179 degree
* merge two hints when near to each other - e.g. left, left to u-turn left
* marker when highway exit and continue nearly same direction
* beeline goes direct from via to via point

There are two steps of control for the voice hint list:

- add voice hint to the list when it passes the first control
  rules are around the good way/bad way turn angles, priorities or link to highway
  only small changes here - e.g. enable the left turn (see above)
  
- remove voice hint from list when it passes the second control
  here we check the old rules (ignore roundabouts and beeline at the moment)
  these rules need some updates
  * show 'continue' 
    only if the way crosses a higher priority way
    and ignore a possible second crossing
    and ignore on tranport mode car when near to an other voice hint
  * merge two hints when near to each other
    use e.g. left / left = u-turn only for transport mode car
    use e.g. left / right = straight only for minimal range (different on foot, bike, car)

Results for trekking samples above:
![New_58](https://github.com/abrensch/brouter/assets/23175706/e3b0f4ff-b443-4e1a-b2ba-89cb0f01dfae)
![New_393](https://github.com/abrensch/brouter/assets/23175706/3b1027e0-b97e-4cd7-982a-a91b9cde0a7e)
![New_479](https://github.com/abrensch/brouter/assets/23175706/a5898198-8fa3-4332-81c8-9a27a06120b1)
![New_518](https://github.com/abrensch/brouter/assets/23175706/79ed1294-7a7c-4176-8a79-5e237cf7f69e)

For a closer look:
Here are the comparable GPX files in new and old version. In the new versions the voice hints have an additional point name to have an easy entry for a point discussion.

[testtrack0.trekking_old.gpx.txt](https://github.com/abrensch/brouter/files/13755044/testtrack0.trekking_old.gpx.txt)
[testtrack0.trekking_new.gpx.txt](https://github.com/abrensch/brouter/files/13755045/testtrack0.trekking_new.gpx.txt)

[testtrack0.car_old.gpx.txt](https://github.com/abrensch/brouter/files/13755048/testtrack0.car_old.gpx.txt)
[testtrack0.car_new.gpx.txt](https://github.com/abrensch/brouter/files/13755052/testtrack0.car_new.gpx.txt)

[testtrack0.hiking_old.gpx.txt](https://github.com/abrensch/brouter/files/13755053/testtrack0.hiking_old.gpx.txt)
[testtrack0.hiking_new.gpx.txt](https://github.com/abrensch/brouter/files/13755056/testtrack0.hiking_new.gpx.txt)

The samples uses all the same coordinates [Darmstadt to Heidelberg](https://brouter.de/brouter-web/#map=11/49.8646/8.6328/standard&lonlats=8.646215,49.87207;8.693455,49.40987) 
Please don't look at the routing results, focus only to voicehints. 

So have fun the next days.

**Comment by afischerdev** [comment]
For the new issue #664 I changed the voicehint calculation on roundabouts.
I did it in this repository because I'm on the way to do a PR for this new features.
