### ISSUE TITLE
BRouter - OruxMaps mismatch since last update 

### ISSUE THREAD

**Issue by franconian** [abrensch/brouter#627]
I have used BRouter in combination with OruxMaps for biking and hiking for years. Finding routes and routing worked excellent till last update of BRouter app to v1.7.3 several days ago. 
Now, not all, but many of the routing signs normally containing an instruction are displayed and announced just as "Waypoint" without any further information and so routing becomes useless. 
What happened since v1.7.2?

**Comment by quaelnix** [comment]
@afischerdev, could this be caused by: https://github.com/abrensch/brouter/commit/b15bdf3192bcdce8877bab3d948eec703171b824?

**Comment by afischerdev** [comment]
Sorry for the delay.

@quaelnix 
Yes, that is the reason.

OruxMap becomes an update on Play Store very soon, and with a little time gap on the other versions.
