### ISSUE TITLE
Routing issue using Stairs

### ISSUE THREAD

**Issue by smallpixelStefan** [abrensch/brouter#631]
Hello, 
when trying to route using this link 
https://brouter.de/brouter-web/#map=18/50.87640/6.02425/osm-mapnik-german_style&lonlats=6.021119,50.877315;6.025829,50.875839;6.027653,50.873266

Is there a way to get the information which element was used for the routing? 
Maybe the routing uses the highway=pedestrian tag, but there are only stairs available. 
The question is, the problem caused by "wrong" tags or by another point. 

Thx
Stefan

**Comment by zod** [comment]
BRouter calculates a cost for each way and the way with the least cost is used for routing. The cost can be calculated using different tags on a way, so it's not a single tag which causes a way to be used or not

You can see the cost of a way using the data tab in the right sidebar.

In this case the area around the steps is mapped as `highway=pedestrian` without any additional tags. It doesn't route over the steps.

**Comment by poutnikl** [comment]
Rather, BRouter throws away all ways when it realizes they cannot have their final cost bigger than the best one from the first pass. It speeds up routing and saves computation resources.

**Comment by smallpixelStefan** [comment]
Thank you very much for the quick response. I have updated the tags. 
Should be fine after the next update.
