### ISSUE TITLE
How customizable are profiles?

### ISSUE THREAD

**Issue by rtwalz** [abrensch/brouter#636]
Hi there! I'm trying to understand just how customizable profiles are.

For example, could I have the router avoid any ways whose name starts with the letter M? That's quite an extreme example, but in this case, I couldn't find a way to manipulate strings in Brouter's scripting language. But maybe I missed something?

If it is true that that's not possible, are there are any known workarounds that I should look into? Could I swap in another programming language with string manipulation capabilities perhaps? Thanks!

**Comment by abrensch** [comment]
No, streetname-information is not contained in the RD5-Datafiles. No Way to evaluate it.

regards, Arndt

**Comment by abrensch** [comment]
closed
