### ISSUE TITLE
Conditional evaluation of user  profiles variables

### ISSUE THREAD

**Issue by poutnikl** [abrensch/brouter#64]
BRouter evaluates terms of logical expressions conditionally , as well as the branches of if/switch commands.  

OTOH, if I got it correctly when we talked about it in past, user defined variables are always evaluated, even if they occur only in expression branches unused for current way/node.

If not addressed yet, would be possible to implement conditional evaluation of variables as well ? As they are very useful to keep simplicity of code, but may cause profile performance decrease.

What about switching the paradigm from the variable based imperative one to macro based declarative one ? Assign would not be taken as assignment executive command for a variable, but as a declaration of macro expression. 

Variable=Macro would be evaluated only when called for its value the first time. Then it would get expanded to  `( macro expression code )` and its value would be stored for the eventual reuse for multiple occurences.

In such case, user variables would be evaluated only if used, what can increase performance of profile processing.

**Comment by abrensch** [comment]
Please just don't worry about the Efficiency of Profile evaluation.

There's an LRU-Cache for expression results. It was not always as efficient as it could be, but I recently did some work on that cache, with the last impovement (not yet released) beeing a filter on unused tags in the decoder, so the number of distinct tag/value combinations is reduced signfificantly and the cache hit rate improved accordingly.

So currently, profile evaluation is not a signfificant part of the processing time.
