### ISSUE TITLE
Profile settings 

### ISSUE THREAD

**Issue by troNpo** [abrensch/brouter#643]
Hello, when I go into profile settings in the app, for example in mountain hiking, after selecting the settings I don't see how to save the settings. 
How do I get the app to record profile changes?

**Comment by afischerdev** [comment]
There is no extra save function. 
But all changes are stored to the [serviceconfig.dat](https://github.com/abrensch/brouter/blob/master/docs/users/android_advanced.md#serviceconfigdat) when you press back.
You see at the end a small summary: routing mode, used profile, counter used nogo areas, and a '+p' when parameter used.

**Comment by troNpo** [comment]
Sorry, but try as I might, profile settings aren't saved. 
Maybe for safety Adding a confirmation button would be a good idea. 
Thank you
![Screenshot_2023-12-14-09-26-21-36_426dd4b0df05b220d038e079e4dccfb1](https://github.com/abrensch/brouter/assets/97335264/18bfb62e-3b99-42f2-b95b-0d6b79256958)

![Screenshot_2023-12-14-09-27-42-70_754cf9a4094c34a8eeb04648e2e3eb8d](https://github.com/abrensch/brouter/assets/97335264/d14a7071-f620-4d02-b8e8-05e553dd30ba)

**Comment by afischerdev** [comment]
I'm sorry to say no.
The dialog is designed to get called not only from BRouter app. Other apps can do that as well.
So the dialog has return values when something is changed, and the apps can work with.

Please let us know what you have done around your both pics. 
May be there is an error in the way BRouter uses the returned values.
Testing the reactions:
- select a new profile (Server-Mode, this clears all params) 
- control the seviceconfig.dat
- select the same profile and then Profile Settings
- change one parameter
- control the seviceconfig.dat
- select the same profile and then Profile Settings again (should show your changes from last step)
- change the parameter back
- and control the seviceconfig.dat

**Comment by troNpo** [comment]
Thanks for the answer, I show a video with the process I do, maybe you can tell me where my mistake is. 

[https://youtube.com/shorts/azm1ORK6b6k?si=7MOy_bJ0IeGwvjmV](url)

**Comment by afischerdev** [comment]
Thanks for the video
I miss the last action in game. After leaving the dialog I get a result announce.

![Screenshot_20231214-115123](https://github.com/abrensch/brouter/assets/23175706/f1333fb9-0cd7-42ea-bd2b-2f7d3d1f1ff3)

Have you tried with the original profile?

**Comment by troNpo** [comment]
That result ad doesn't appear, with any profile. 
I have uninstalled and installed the Google play version and the apk
It doesn't work for me at all. 
Cin the original profiles.

**Comment by afischerdev** [comment]
Could it be that the installation is on sdcard?
I have only phones without sdcard. So it is hard to test.

**Comment by afischerdev** [comment]
I think I've found the problem - with a borrowed cell phone. 
Need more testing.

**Comment by troNpo** [comment]
Thanks for your interest, please refer the issue to a group of Oruxmaps users, With Android 13 it seems to go well, in Android 11 (my case) it doesn't. 
Later I'll try Android 10 and I'll tell you the result in case the Android version is related.

**Comment by troNpo** [comment]
Hi again, two more users and I, we have checked that the profile settings do not run on Android 10 and 11
In case this information is useful to you

**Comment by afischerdev** [comment]
I have posted a solution.
Please give us some time for a review. I'll inform here when we get a usable version.

**Comment by troNpo** [comment]
Great news!! I love planning routes with brouter, the ability to make adjustments to profiles is an added plus
Thank you for your attention.
