### ISSUE TITLE
Don't make a turn instruction when way is almost straight and other way is minor

### ISSUE THREAD

**Issue by carg0cult** [abrensch/brouter#66]
In this example brouter issues a keep left instruction at lon="9.182407" lat="48.829950"
![brouterkeepleft](https://cloud.githubusercontent.com/assets/5933280/19399751/58d165c0-9253-11e6-9bcb-8109a1d2f308.png)
The road is almost straight and the crossing way is a footway. An instruction like this is unnecessary and should not be created to reduce noise/confusion.

**Comment by abrensch** [comment]
No idea what's the issue here.

Suspicous is that Haidenrainstrasse is split at this point. If the "priotity-classifier" would change along the road, I would expect an instruction. However, for all profiles I tried this is not the case.

**Comment by carg0cult** [comment]
I'm glad it works with the default profiles. I will rewrite my profiles to match that structure.
Here is the profile that causes this behavior, if you ever want to find out why.

[lieger.brf.txt](https://github.com/abrensch/brouter/files/534183/lieger.brf.txt)
[Uploading lieger.brf.txt…]()

**Comment by abrensch** [comment]
Seems your profile does not define the turn-instruction specific variables.

If priorityclassifier defaults to 0, all is equal priority...

Just copy the stuff between:

assign priorityclassifier =
...
assign classifiermask
