### ISSUE TITLE
Confusing U-turn instruction

### ISSUE THREAD

**Issue by poutnikl** [abrensch/brouter#67]
I was asked to forward the U turn  versus Left U-turn + Right U-turn issue ( action 12 vs 13+14 ), related to  
 [confusing-u-turn-instruction](http://help.locusmap.eu/topic/confusing-u-turn-instruction#comment-33745l)   thread at Locus Helpdesk.  
Locus users and the author have the opinion you may want to  implement Left/Right U-turn actions, eventually review the sharp turn versus U-turn evaluation.

My understanding is sharp turn  = 135 +- 22.5 degress, U-turn is  157.5..180 degress.
Perhaps such a U-turn versus Turn Around are to be distinguished, if possible.

**Comment by poutnikl** [comment]
Perhaps the action 12 U turn should be used in sense of  Turn around, if there is no dedicated action,  while actions 13+14 Left/right U turn should be used as very sharp turns as above.

**Comment by menion** [comment]
Thanks Libor, appreciate it.
Just to make suggestion precise, [here is a link](https://github.com/asamm/locus-api/blob/master/locus-api/src/main/java/locus/api/objects/enums/PointRteAction.java) to fresh new class in Locus API made for these routing instructions. As Libor suggest, U-Turn should be divided into left/right direction if possible and also used in best case for real u-turns and not for shart right/left branches.
Thanks for consideration.

**Comment by abrensch** [comment]
fixes that in the upcoming release
