### ISSUE TITLE
include "informal" tags in datafiles

### ISSUE THREAD

**Issue by zossebart** [abrensch/brouter#68]
What about including "informal" tag ([http://wiki.openstreetmap.org/wiki/Key:informal](http://wiki.openstreetmap.org/wiki/Key:informal)) in the way context into the routingfiles? This way routing over inofficial paths could be penalized, as they are not guaranteed to be maintained or save.

**Comment by poutnikl** [comment]
Closely related is consideration ( as not yet implemented in my profiles ) the quantitative parameters    **class:bicycle:mtb** and **class:bicycle** both with values -3 .. +3, already included in lookups.dat.

[class:bicycle on OSM wiki](https://wiki.openstreetmap.org/wiki/Key:class:bicycle)

**Comment by abrensch** [comment]
done for 1.4.9
