### ISSUE TITLE
Brouter Java error

### ISSUE THREAD

**Issue by anten1222** [abrensch/brouter#695]
I use BRouter in conjunction with Osmand. Up to version 1.6.3 it was possible to start the BRouter app after a time out of 60 seconds and it said "repeat:Fastbike" and the route was calculated. Since version 1.7.4 it says "repeat:null". When I click on this point, a Java error appears. The app is therefore unusable.

**Comment by afischerdev** [comment]
Could you please provide us with some more data? 
What are your points from - to?
I'm not familiar with OsmAnd. But I have it installed and might try it with your input.
I tested with other app around 500 km beeline with fastbike profile - took nearly 2 minutes (mesured from out side BRouter). It produced sometimes interface errors (to many data).

**Comment by EssBee59** [comment]
> Since version 1.7.4 it says "repeat:null". When I click on this point, a Java error appears. The app is therefore unusable.

Ok, with the current version, a time out is reported after 60 seconds...but only by VERY VERY long routes!
(I am using Brouter-app 1.7.4 and Osmand 4.7.17 on a MI 12T pro, never see the problem before, as it only appear by routes > 300 km, and my daily bike-route is max 200 km!)

Here an extract of the debug.txt where  I tried to calculate different very long routes

...
collected, nodes/paths before=298183/37732 after=279174/34107 maxTotalCost=1000000000
collected, nodes/paths before=297091/38288 after=277064/34569 maxTotalCost=1000000000
Error (linksProcessed=10090523 open paths: 34571): pass0 timeout after 60 seconds
expression cache stats=requests=16203302 requests2=16085302 cachemisses=117975
NodesCache status before close=collecting=false noGhosts=false cacheSum=0 cacheSumClean=0 ghostSum=0 ghostWakeup=0

...

**Comment by anten1222** [comment]
Startpoint 53.70898° N, 9.38858° E
Target point 48.00866° N, 7.82568° E
Osmand 4.7.17
Brouter 1.7.3
Everything ok
![XRecorder_11052024_190402](https://github.com/abrensch/brouter/assets/73232079/d2f48b5e-50dc-424f-ba02-34d312ca1e6d)

Brouter 1.74
Brouter App
"repeat:null"
Brouter error
![XRecorder_11052024_191510](https://github.com/abrensch/brouter/assets/73232079/f5cd98fe-4689-4d22-9842-652a84550488)

**Comment by vodie** [comment]
@anten1222 

I also use Osmand 4.7.17 with Brouter 1.7.4 and the <repeat:...> profile still works.

Does your configuration work with "short calculations" or is the problem only with the <repeat:...> calculations? Maybe there is something wrong with your BRouter or Osmand configuration.

By the way, if you know that your calculation will take more than 60 seconds, you can cancel the calculation in osmand immediately and go to the BRouter app and start the <repeat:...> profile. No need to wait for the 60 second time out.

**Comment by anten1222** [comment]
All routes that are calculated in 60 seconds work. Otherwise always repeate:null

**Comment by afischerdev** [comment]
@anten1222 
Thanks for your additional info.

Now  I can follow the error. 
On my phone a file 'timeoutdata.txt' with size of 0 byte is generated. That ends in an entry with repeat:null.  
The minimum we need is a check for the file size. 
I could start on Wednesday with more checks.

**Comment by afischerdev** [comment]
Should be run in next version
