### ISSUE TITLE
Make timestamp format in server log to ISO8601 compatible

### ISSUE THREAD

**Issue by mjaschen** [abrensch/brouter#699]
When running in server mode, BRouter emits log entries for each calculation. A log line starts with the current timestamp formatted in `dd.MM.yy HH:mm` (the standard German format for date and time):

```
14.05.24 06:01  35 ip=10.0.0.1 ms=21 -> GET /brouter?lonlats=8.511111,51.133333|8.522222,51.144444&profile=Fastbike-lowtraffic-tertiaries&alternativeidx=0&format=geojson HTTP/1.0
```

I suggest to change the timestamp (first two whitespace separated fields) into an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) compatible format (the example could look like `2024-05-14T08:01:34+02:00` or `2024-05-14T06:01:34+00:00`).

This allows easier processing of log entries. For example sorting/grouping merged log files would be possible without parsing the timestamp first.

I'd create a pull request if such a change has chances to be merged (it would break backward compatibility).

----

With this issue, I also want to find out whether a change to the logfile format is possible or desired at all, as this would break backward compatibility. If such changes are possible, I would like to discuss the structure of a logfile line in general in a separate issue, as I think there's some potential for improvement.

**Comment by abrensch** [comment]
Sure Go ahead. I have a Parser as flying Code to create Access Frequeny Diagramms, but can easily adapt it. Most Analysis I use simply "grep". Daily Rotation would bei a +
