### ISSUE TITLE
bug with brouter.damsy

### ISSUE THREAD

**Issue by vincevelo** [abrensch/brouter#708]
hello , when i choose extra layer (camping, restaurant...) , it bugs the app, i cannot move ... or create a trace ? any pb ? 
[https://brouter.damsy.net/latest/#map=11/47.2594/3.5527/cyclosm,camp_site&lonlats=3.522996,47.457455;3.617195,47.362023;3.870792,47.281546;3.90786,47.292602;3.90563,47.36709;3.753871,47.461865;3.63234,47.534805;3.515446,47.962306](url)

**Comment by afischerdev** [comment]
@vincevelo 
You went to [BRouter-web](https://github.com/nrenner/brouter-web/issues/813) with this issue. So I think we can close it here.
If you do not agree, it can be reopened.
