### ISSUE TITLE
Cycling overlay doesn't work

### ISSUE THREAD

**Issue by Adelheid9** [abrensch/brouter#709]
Today (14.6.2024) I logged into Brouter on my Mac to continue my bicycle route planning from yesterday.

I clicked on Radfahren and no marked Trails showed up.

I am using an Imac.

What did I do wrong.

Regards Adelheid

**Comment by zod** [comment]
This is an issue of brouter-web, this repository is only about the routing engine & android app.

It uses tiles from waymarkedtrails which is currently broken.

**Comment by Adelheid9** [comment]
Oh, da bitte ich um Entschuldigung. Ich war leider nicht darauf vorbereitet, dass ein Link auf Brouter.de Web zum falschen Forum führt. Ich hatte gedacht, dass brouter.de von mir im Browser aufgerufen wurde.
Grüße
Adelheid
PS: Hat jemand eine Ahnung, wann die unterbrochene Verbindung wieder steht, da ohne Rad- und Wanderwege die Anwendung ziemlich nutzlos los.

**Comment by zod** [comment]
Don't worry, you're not the first person and certainly won't be the last person to be confused if an issue should be reported to brouter or brouter-web.

It seems like Waymarked Trails is working again. There are also other map tiles which provide cycling and hiking trails, e.g. CyclOSM (cycling) or Refuges.info (hiking). They can be activated using the "More" button in the layer sidebar and afterwards selected as active layer.

![image](https://github.com/abrensch/brouter/assets/49181/c060a7a2-c0f0-46a1-b895-d3b38aa66f46)
