### ISSUE TITLE
little bug in hight model at waypoints

### ISSUE THREAD

**Issue by MasiMaster** [abrensch/brouter#71]
If a waypoint is set behind a OSM node with a following long segment of incline without a OSM node in the route, the hight model will show a peek. Example:
http://brouter.de/brouter-web/#zoom=16&lat=50.97287&lon=7.19881&layer=OpenStreetMap&lonlats=7.207654,50.972292|7.201576,50.972663|7.196796,50.974305&nogos=&profile=trekking&alternativeidx=0&format=geojson

If than the annoying waypoint is deleted, you can see the incline without the peek.

**Comment by abrensch** [comment]
I fixed that (active in brouter-web, release coming...)
