### ISSUE TITLE
Car Profiles Not Working v1.7.5

### ISSUE THREAD

**Issue by troNpo** [abrensch/brouter#712]
Hello on the latest update the default 
car profiles of the app, do not generate route, tested in two app Oruxmaps GP and Locus Maps. 
Both apps generate the same message of not being able to do the route. 
Best regards

**Comment by poutnikl** [comment]
Assuming you have tried different routes to be sure it is not issue of particular OSM mapping.

**Comment by devemux86** [comment]
I can also see this with Cruiser and external BRouter option, using a fresh install of BRouter 1.7.5.

`getTrackFromParams` returns null for driving profiles, even for valid routes of some meters.
(cycling and walking profiles seem to work)

**Comment by devemux86** [comment]
Checking the Logcat, there is an exception from BRouter:
```java
java.lang.RuntimeException: Cannot create path-model: java.lang.ClassNotFoundException: btools.router.KinematicModel
    at d2.j.i(SourceFile:480)
    at d2.k.<init>(SourceFile:514)
    at a2.a.a(SourceFile:1456)
    at e2.n.d(SourceFile:1097)
    at e2.n.onTransact(SourceFile:1)
    at android.os.Binder.execTransactInternal(Binder.java:1344)
    at android.os.Binder.execTransact(Binder.java:1275)
```

BRouter 1.7.5 updated the build environment. Probably a ProGuard rule is needed [here](https://github.com/abrensch/brouter/blob/master/brouter-routing-app/proguard-rules.pro) now:
```
-keep class btools.router.KinematicModel { *; }
```

**Comment by afischerdev** [comment]
My guess is, the build process optimized the kinetic class away. It is only called with the car profiles.

**Comment by afischerdev** [comment]
Actually the `minifyEnabled true` is the problem.
It also prevented the direct call of the profile dialog in BRouter app from other apps.

**Comment by afischerdev** [comment]
@troNpo 
Thanks for the support.
Next version should do the job.

**Comment by troNpo** [comment]
Successfully tested!! Thanks a lot. 
@devemux86 Thank you for verifying my report
