### ISSUE TITLE
Update in F-Droid? 

### ISSUE THREAD

**Issue by tomcat-xx** [abrensch/brouter#716]
Will there be an update to 1.7.6 in F-Droid? Don't need the update itself but Google Play Store is showing it since it has been released there. By the way, is that because of same package name? I only have same issue with one other app (wikipedia) even I use a lot that are in Play Sore and F-Droid. 

Regards
Thomas

**Comment by afischerdev** [comment]
Just for info:

I think I found the reason:
BRouter build system moves to groovy build. Please see PR #689 
The version number moves to a new location.

FDroid need to know that.
I've started an update for the build script [btools.routingapp.yml](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/btools.routingapp.yml).
But the FDroid test ends with an error and I can't imagine why. And I don't have time to continue at the moment. Sorry.
Please see [FDroid build test](https://gitlab.com/afischerdev/f-droid-data/-/jobs/7267087291)

**Comment by afischerdev** [comment]
@zod 

The test for FDroid is running now. But the build [fails](https://gitlab.com/afischerdev/f-droid-data/-/jobs/7309936323) on an other place.
It breaks at new file [brouter.library-conventions.gradle](https://github.com/search?q=repo%3Aabrensch%2Fbrouter+%24System.env.REPO&type=code)

Do you have any idea on this?

**Comment by afischerdev** [comment]
@zod @tomcat-xx 
Ok, the merge request on FDroid is running. If it's done the FDroid generation should go on.

**Comment by tomcat-xx** [comment]
Build is done successfully.

**Comment by tomcat-xx** [comment]
Now it is deployed. Thanks a lot!
