### ISSUE TITLE
v1.7.7 is rejected by the Play Store

### ISSUE THREAD

**Issue by afischerdev** [abrensch/brouter#720]
> Action Required: Your app is not compliant with Google Play Policies (BRouter Offline Navigation)
>
> Issue found: Permission use is either not declared or incorrectly declared
>
> bring your app into compliance, follow these steps:
>
> - Please submit an updated declaration, being sure to include all uses of the `foreground service permission` in your app.
> - Ensure that all use cases declared match the app experience.
> - Review the list of `foreground service type` permissions to ensure that the appropriate type is being used for each declared use case.
> - Remove the use of `FOREGROUND_SERVICE` in cases where it is not required.

In my eyes we got all things defined in the [docs](https://developer.android.com/about/versions/14/changes/fgs-types-required#data-sync) 

Do any of you have any idea what else could be wrong?

Only idea I have at the moment is the double declaration of FOREGROUND_SERVICE in [AndroidManifest.xml](brouter-routing-app/src/main/AndroidManifest.xml) - but this also follows the docs
```
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_DATA_SYNC" />
```
Service [declaration](https://github.com/abrensch/brouter/blob/e63cc9888fcada42464dc9b0114ec20c1736e7fb/brouter-routing-app/src/main/AndroidManifest.xml#L104)
Api [call in DownloadWorker](https://github.com/abrensch/brouter/blob/e63cc9888fcada42464dc9b0114ec20c1736e7fb/brouter-routing-app/src/main/java/btools/routingapp/DownloadWorker.java#L174)

**Comment by devemux86** [comment]
@afischerdev please my pull request:
- https://github.com/abrensch/brouter/pull/649

Have you made a new declaration in "App content" page in Play Console (Policy > App content)?

A video is also required demonstrating the foreground permission:
display the download of the routing tiles.

**Comment by afischerdev** [comment]
@devemux86 
Thanks for your response. Yes, all that is done.
Video is now on [BRouter.de](https://brouter.de/brouter_data_sync.mp4). @EssBee59 was kind enough to place it there. 
I think I'm going to object first.

**Comment by afischerdev** [comment]
Before I appeal, I checked the explanation again. I may need to change from import to download description. Just another try.

**Comment by devemux86** [comment]
> I may need to change from import to download description. Just another try.

This may be the reason, the use case should be "[Network transfer: Upload or download](https://support.google.com/googleplay/android-developer/answer/13392821)".

---

Also using the Android [DownloadManager](https://developer.android.com/reference/android/app/DownloadManager) is simpler without the need of foreground services and permissions.

**Comment by afischerdev** [comment]
v1.7.7 is online

@devemux86 
Import / download seems to be the reason
