### ISSUE TITLE
Feature request : allow for initial download to be done using mobile data, not only over wifi ?

### ISSUE THREAD

**Issue by sedha344** [abrensch/brouter#721]
Hi my Hero could it be possible please / has it been possible in previous versions by any chance ? 

It seems initial download is stuck if one uses mobile data instead of wifi. Not everyone has access to wifi network :disappointed: 

By thanking you :pray: :medal_sports:

**Comment by afischerdev** [comment]
BRouter app is not restricted to Wifi. So please try a new installation with only phone network. It should work.
Otherwise please come again.
