### ISSUE TITLE
Android 15

### ISSUE THREAD

**Issue by devemux86** [abrensch/brouter#736]
Android 15 forces the display of content edge-to-edge in the apps:
https://developer.android.com/about/versions/15/behavior-changes-15#window-insets

In installer activity we could move the items to not be on screen edges on Android 15
or use the `fitsSystemWindows` and avoid completely the edge-to-edge forced display.

This is how the installer activity appears now when target sdk is 35:

<img src="https://github.com/user-attachments/assets/4ec5b769-df5b-433c-9dea-472f52e1c4af" width="50%"/>

**Comment by devemux86** [comment]
It is easier to set it in [styles.xml](https://github.com/abrensch/brouter/blob/master/brouter-routing-app/src/main/res/values/styles.xml) for the whole app.

```xml
<style name="Theme.App" parent="Theme.AppCompat.Light.NoActionBar">
    ...
    <item name="android:fitsSystemWindows" tools:targetApi="VANILLA_ICE_CREAM">true</item>
</style>
```

You can also see it in Mapsforge:
- https://github.com/mapsforge/mapsforge/pull/1556

**Comment by afischerdev** [comment]
@devemux86 
Good idea

**Comment by devemux86** [comment]
@afischerdev 

After more tests, setting it in styles.xml is not a good idea, as it will affect everything, i.e. it breaks the dialogs.

So it is best to just set it on the main layout file.

**Comment by afischerdev** [comment]
@devemux86 
Hm, I'm using a modified version with an Android 15 phone and see 'only' the point cloud screen of the routing (avaible when starting some favorites routing) with a missplaced top line.
Or do you have other screens in mind?

**Comment by devemux86** [comment]
@afischerdev I only checked the installation screen (seen at the 1st post).

It seems that we can still use the styles.xml as a global and most convenient way.
But in order to not break the old Androids, we need to use the tag only for Android 15 in `values-v35/styles.xml`.

See here for how I implemented it in Mapsforge:
- https://github.com/mapsforge/mapsforge/pull/1560

**Comment by afischerdev** [comment]
@devemux86 
I'll try it with your suggestion.

**Comment by devemux86** [comment]
This should be fixed by https://github.com/abrensch/brouter/pull/739.

**Comment by afischerdev** [comment]
@devemux86 
Thank you for the preparation
The favorites routing page with a missplaced top line works well now.
