### ISSUE TITLE
Error at Arth Goldau

### ISSUE THREAD

**Issue by daveymills** [abrensch/brouter#737]
Please could this issue with the track be fixed ?

https://brouter.damsy.net/latest/#map=17/47.04852/8.55918/standard&profile=rail

cheers
davey

**Comment by poutnikl** [comment]
They would probably want you to provide the link to generated track. 
the link you have provided is an ordinary map zoom link.

**Comment by daveymills** [comment]
thanks but i do not understand what you suggest

**Comment by afischerdev** [comment]
> This has nothing to do with BRouter

I think so

**Comment by daveymills** [comment]
thanks all involved. i am a user of BRouter - I have no idea of  the architecture behind it nor of other systems.

**Comment by poutnikl** [comment]
@daveymills Brouter does not use its Owen map data, but relies on Open maps data project Openstreetmap, where any registered user can update or fix maps.

Brouter just process these data to be better suited for routing purposes.
