### ISSUE TITLE
add 4wd_only tag to lookups.dat

### ISSUE THREAD

**Issue by SearchingForDottedLines** [abrensch/brouter#74]
Hi team,

Brouter is awesome :-)

I'm using the web version of Brouter for offroad 4wd track routing, and unlike most other modes of transport we active seek out poor quality roads.

I see you expose tracktype, smoothness and surface via lookups.dat - but would it be possible to also add the 4wd_only tag?

This tag is used quite a lot, particularly in Australia where it is used as a standalone (tracktype, smoothness and surface not set)
http://wiki.openstreetmap.org/wiki/Tag:4wd_only%3Dyes
http://taginfo.openstreetmap.org/tags/4wd_only=yes#map

Thanks in advance...

**Comment by abrensch** [comment]
done for 1.4.9
