### ISSUE TITLE
following build instructions failes on debian 12

### ISSUE THREAD

**Issue by pcace** [abrensch/brouter#751]
Hi there, following the build instructions failes like this: 

```
./gradlew clean build -x :brouter-routing-app:build
Note: To include Android app add 'local.properties' with 'sdk.dir=...' 

FAILURE: Build failed with an exception.

* What went wrong:
Cannot locate excluded tasks that match ':brouter-routing-app:build' as project 'brouter-routing-app' not found in root project 'brouter'.

* Try:
> Run gradlew projects to get a list of available projects.
> For more on name expansion, please refer to https://docs.gradle.org/8.4/userguide/command_line_interface.html#sec:name_abbreviation in the Gradle documentation.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 679ms

```

**Comment by devemux86** [comment]
> Note: To include Android app add 'local.properties' with 'sdk.dir=...' 

@pcace Have you followed the above instructions?

For more details also see:
https://developer.android.com/build#properties-files

`local.properties`
Configures local environment properties for the build system, including the following: 
- `sdk.dir` - Path to the Android SDK.

**Comment by pcace** [comment]
> > Note: To include Android app add 'local.properties' with 'sdk.dir=...'
> 
> @pcace Have you followed the above instructions?
> 
> For more details also see: https://developer.android.com/build#properties-files
> 
> `local.properties` Configures local environment properties for the build system, including the following:
> 
>     * `sdk.dir` - Path to the Android SDK.

Hi, as i understand the readme this: 

```
Build BRouter without the Android app:

./gradlew clean build -x :brouter-routing-app:build

```
means i do not need the android SDK? 
In the meantime i figured out, i can build it by just leaving this part `-x :brouter-routing-app:build` out. 

i think this issue is fixed for me, so i will close it.
