### ISSUE TITLE
Overnight Stays on Multi-Day Trips

### ISSUE THREAD

**Issue by GyrosGeier** [abrensch/brouter#80]
I've used BRouter to plan a trip from Munich to Berlin, which took five minutes to route, but gave a really excellent route in the end.

Along the route I was delighted to find camping sites near the route approximately every 100 km, which made this an excellent 7 day trip, but it was some effort to manually search around the route and add waypoints, so it would be great if that could be automated.

Algorithm I used:

1. Route without intermediate waypoints
2. Go to a point on the route that is 100 km from the start point
3. Look for a campsite nearby
4. Add a waypoint at the campsite
5. Check whether the first segment is shorter than 110 km
6. If yes, repeat from step 2 for remaining route. If no, erase waypoint, go back 10km on the original route, try to find a campsite again.
7. Finally, sanity check that the last segment is longer than 10 km, otherwise erase last waypoint.

Obviously all of these parameters (type of accomodation, maximum segment length, minimum length for last segment, ...) need to be somewhat tunable, and there needs to be a way to blacklist campsites as they might be closed or full -- in which case a different site needs to be selected.

**Comment by poutnikl** [comment]
Hmm..  IMHO, such a task would suit more to a GUI front-end like a GPS map/navigation application or an online trip planner. Perhaps [Brouter-web](https://github.com/nrenner/brouter-web/).  But it would probably need huge coding demand for POI proximity search. Routing search work with other principles and has different data structure.
