### ISSUE TITLE
brouter not interfacing with OSMAnd ver. 1.8 on Android 2.3

### ISSUE THREAD

**Issue by ghost** [abrensch/brouter#81]
BRouter supports Android 2.3 (thankfully).  The latest OSMAnd that works on 2.3 is 1.8.  So naturally there is an expectation that Brouter work with OSMAnd 1.8.

The problem: although both BRouter 1.4.8 and OSMAnd 1.8 install and download maps correctly, they do not interface.  BRouter does not find OSMAnd so a scan (from the "help" feature) is necessary.  The scan does not find anything.  OSMAnd also does not see BRouter, as the "Navigation Service" config does not offer a brouter choice.

**Comment by natrius** [comment]
Out of curiosity: Why do you need brouter when using osmand and vice versa? I don't understand.

**Comment by ntruchsess** [comment]
Regarding the problem of OSMAnd not finding BRouter:
On startup OSMAnd tries to get access to the brouter-service by binding to an Intend via classname. This works as long the installed BRouter is allowed to start a background-service to service this intent.
If anything hinders the BRouter-service to start before OSMAnd is initializing it will not find the BRouter-service. So if you face this issue check in android app-settings whether BRouter is allowed to start as a service at boot-time.

**Comment by libBletchley** [comment]
Thanks for the tip. I've not had a chance to retry, but I'll give feedback if there are still issues.

**Comment by Phyks** [comment]
Hi, are you still having issues with this?
