### ISSUE TITLE
Mofa, possible in brouter

### ISSUE THREAD

**Issue by AllroadsNL** [abrensch/brouter#85]
Is it possible to make mofa routing?

In the Netherlands we have many cycleway which we can ride with a mofa but not with a moped.

There is not a good mofa routing, which can make a .gpx.

**Comment by poutnikl** [comment]
As the first step there must be mofa[:*]=* tags  exposed in lookup.dat file and present in RD5 files.
Then a profile can be written to consider these tags.
Until then a work around could be in checking combinations of other access tags, like combination of access for bicycle and particular or general vehicles.

**Comment by poutnikl** [comment]
Hmm, reading the mofa Wikipedia DE article ( what my bad German allows ), I am more and more confused, what is difference between mofa and moped. What I have thought it would be mofa is rather "leichtmofa".

**Comment by AllroadsNL** [comment]
The problem is that a lot of people tagging motor_vehicle, but forget to tag mofa=yes moped=yes, they think MV is only motorcycle car hgv,  etc.

Waiting for the change.

But is this the place to ask for it?

**Comment by poutnikl** [comment]
Well, this is place to ask @abrensch - the BRouter author - to involve moped= and mofa= tags, 
not to ask people to do OSM mapping for them.

**Comment by poutnikl** [comment]
Just small statistics from [taginfo OSM site](https://taginfo.openstreetmap.org/) about access tag occurences for ways
bicycle=   3 150 000
mofa=          49 000
motorcycle= 284 000
motor_vehicle= 855 000
vehicle= 155 000
motorcar= 299 000
access= 6 080 000

https://taginfo.openstreetmap.org/keys/bicycle

**Comment by abrensch** [comment]
I can certainly add the mofa tag to the lookup table, though I don't think is in the "official access hirachy", so I will not adapt standard profiles. Missed that for 1.4.9, will keep an eys on that.

moped.brf should also work for mofas, but of course it does not find the mofa-allowed cycleways.

Current statistics (worldwide) is:

mofa;0000024647 yes
mofa;0000020173 no
mofa;0000003473 designated
mofa;0000000391 use_sidepath
mofa;0000000060 destination
mofa;0000000058 permissive
