### ISSUE TITLE
Allow custom name instead of brouter_profile_alternativeidx when writting GPX

### ISSUE THREAD

**Issue by bagage** [abrensch/brouter#90]
Currently brouter [automatically writes](https://github.com/abrensch/brouter/blob/c517ccc2dffc1ae345e4b93b1f3b00bfabbfe4de/brouter-core/src/main/java/btools/router/RoutingEngine.java#L170) `<name>brouter_{profile}_{alternative_idx}</name>` in the output gpx file. 

Since some GPS devices (garmin) displays that name in the list of available traces, it would be great if we could choose the name, for instance via an extra parameter, for instance:

```
0.0.0.0:17777/?lonlats=4.588401,44.821284|4.591126,44.820797&profile=trekking&alternativeidx=0&format=gpx&name="Paris - Lisbone (4303km)"'
```

**Comment by Phyks** [comment]
Hi!

This should be implemeted in https://github.com/abrensch/brouter/pull/132. Let me know if this fits your need.

Best,

**Comment by bagage** [comment]
Yes indeed, thanks @Phyks!
