### ISSUE TITLE
lookup.dat request: cycleway:left/right:oneway

### ISSUE THREAD

**Issue by utack** [abrensch/brouter#98]
Hi Arndt,  
could you please consider adding cycleway:left/right:oneway to the lookup.dat?
Combined they are used nearly 8000 times on the planet.
Thanks for consideration

**Comment by charlesmillet** [comment]
Hi,
I agree it would be very useful.
Regards.

**Comment by Phyks** [comment]
Hi, would you have an example of a non-trivial case where the cycleway:left/right:oneway tag could be useful for the current profiles?

The only ones I found so far are such as [this one](https://www.openstreetmap.org/way/210127196) which could be useful to match the direction of circulation with the cycleways and then, with an infrastructure type. Was it the intend you had in mind (preferring tracks over lanes for instance)?

**Comment by utack** [comment]
https://www.openstreetmap.org/way/175725446
And many more

**Comment by Phyks** [comment]
Thanks! I know this kind of infrastructure but always saw it tagged as a separate way so far :)

**Comment by Phyks** [comment]
For the record, I think I got a nice example of a case where it can be easily tested on [this route](http://brouter.de/brouter-web/#map=17/51.16159/13.56077/OpenStreetMap&lonlats=13.561168,51.160763|13.562155,51.1623). It could just follow the secondary road as there is a cycleway on it.

Thanks @utack for pointing the location to me! :) I'll integrate it in https://github.com/Phyks/BrouterTesting.

**Comment by abrensch** [comment]
done as part of PR#122. New lookups.dat was effective in last nights preprocessing run
